import {audit,getHospitalSession,getPatientSession} from "@/lib/demo-auth";
export type CareEvent="page_viewed"|"cta_clicked"|"patient_invited"|"invite_opened"|"registration_started"|"registration_completed"|"first_checkin_completed"|"patient_registered"|"patient_onboarding_started"|"patient_onboarding_completed"|"checkin_started"|"checkin_question_answered"|"checkin_completed"|"checkin_abandoned"|"recovery_summary_viewed"|"patient_status_changed"|"care_signal_created"|"care_signal_viewed"|"hospital_patient_opened"|"care_task_assigned"|"care_action_started"|"care_action_completed"|"signal_feedback_submitted"|"followup_started"|"followup_created"|"followup_viewed"|"followup_completed"|"outpatient_summary_viewed"|"care_completed";
export type CareAnalyticsEvent={id:string;eventType:CareEvent;patientId?:string;hospitalId?:string;staffId?:string;careSignalId?:string;careTaskId?:string;timestamp:string;metadata?:Record<string,unknown>};
const CARE_ANALYTICS_KEY="oneul-anbu:care-analytics:v1",DEMO_ANALYTICS_KEY="oneul-anbu:public-demo:care-analytics:v1";
export function loadCareAnalyticsEvents(demo=false):CareAnalyticsEvent[]{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(demo?DEMO_ANALYTICS_KEY:CARE_ANALYTICS_KEY)||"[]") as CareAnalyticsEvent[]}catch{return[]}}
export function clearDemoAnalyticsEvents(){if(typeof window!=="undefined")localStorage.removeItem(DEMO_ANALYTICS_KEY)}
// Analytics is deliberately best-effort: failure must never roll back or mask a clinical workflow save.
export function trackCareEvent(name:CareEvent,properties:Record<string,unknown>={}){
 if(typeof window==="undefined")return;
 try{
  const hs=getHospitalSession(),ps=getPatientSession(),demo=properties.demo===true,event:CareAnalyticsEvent={id:`event_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,eventType:name,patientId:typeof properties.patientId==="string"?properties.patientId:ps?.patientId,hospitalId:typeof properties.hospitalId==="string"?properties.hospitalId:hs?.hospitalId||ps?.hospitalId,staffId:typeof properties.staffId==="string"?properties.staffId:hs?.userId,careSignalId:typeof properties.careSignalId==="string"?properties.careSignalId:undefined,careTaskId:typeof properties.careTaskId==="string"?properties.careTaskId:undefined,timestamp:new Date().toISOString(),metadata:Object.fromEntries(Object.entries(properties).filter(([key])=>!["patientId","hospitalId","staffId","careSignalId","careTaskId","demo"].includes(key)))};
  const key=demo?DEMO_ANALYTICS_KEY:CARE_ANALYTICS_KEY,events=loadCareAnalyticsEvents(demo);localStorage.setItem(key,JSON.stringify([...events,event].slice(-10000)));window.dispatchEvent(new CustomEvent("todayanbu:analytics",{detail:event}));const patientId=event.patientId||"";
  if(name==="checkin_completed"&&ps)audit({actorType:"patient",actorId:ps.patientId,actorRole:"patient",hospitalId:ps.hospitalId,action:"checkin_completed",resourceType:"checkin",resourceId:patientId});
  if(name==="patient_status_changed"&&ps)audit({actorType:"patient",actorId:ps.patientId,actorRole:"patient",hospitalId:ps.hospitalId,action:"patient_status_changed",resourceType:"patient_status",resourceId:patientId});
  if(name==="hospital_patient_opened"&&hs)audit({actorType:"hospital_user",actorId:hs.userId,actorRole:hs.role,hospitalId:hs.hospitalId,action:"patient_record_viewed",resourceType:"patient",resourceId:patientId});
  if(name==="care_action_completed"&&hs)audit({actorType:"hospital_user",actorId:hs.userId,actorRole:hs.role,hospitalId:hs.hospitalId,action:"care_action_created",resourceType:"care_action",resourceId:String(properties.careActionId||patientId),metadata:{careTaskId:event.careTaskId}});
  if(name==="followup_created"&&hs)audit({actorType:"hospital_user",actorId:hs.userId,actorRole:hs.role,hospitalId:hs.hospitalId,action:"followup_created",resourceType:"followup",resourceId:String(properties.followUpId||patientId)});
  if(name==="followup_completed"&&hs)audit({actorType:"hospital_user",actorId:hs.userId,actorRole:hs.role,hospitalId:hs.hospitalId,action:"followup_completed",resourceType:"patient",resourceId:patientId});
  if(name==="care_completed"&&hs)audit({actorType:"hospital_user",actorId:hs.userId,actorRole:hs.role,hospitalId:hs.hospitalId,action:"care_completed",resourceType:"patient",resourceId:patientId});
 }catch{/* best-effort by design */}
}
