export const PRODUCT_COPY = {
  corePromise: "매일 묻지 않아도, 평소와 다른 날을 알려드립니다.",
  radarName: "생활 변화 레이더",
  radarDescription: "평소 생활을 조용히 살펴보고, 다른 흐름이 이어질 때 가족이 먼저 확인하도록 돕습니다.",
  engineName: "Personal Baseline Engine",
  engineDescription: "다른 사람의 평균이 아닌, 부모님 본인의 평소 생활과 비교하는 생활 변화 분석 엔진입니다.",
  parentBehavior: "부모님은 매일 기록하지 않습니다. 확인이 필요한 날에만 질문 하나에 답합니다.",
  parentSkip: "답하기 어려운 날은 건너뛰어도 괜찮습니다.",
  familyBehavior: "가족은 평소와 다른 날에 달라진 이유와 행동 하나를 확인합니다.",
  noChange: "오늘도 평소와 비슷한 생활입니다.",
  changeDetected: "오늘은 평소와 조금 다릅니다.",
  learning: "생활 흐름을 알아가는 중입니다.",
  noAction: "지금 필요한 행동은 없습니다.",
  callAction: "오늘 짧게 전화해보세요.",
} as const;
