const baseKey = "today-anbu";

export const storageKeys = {
  base: baseKey,
  onboardingCompleted: `${baseKey}:onboarding-completed`,
  familyOnboardingCompleted: `${baseKey}:family-onboarding-completed`,
  stepsPermission: `${baseKey}:permission-steps`,
  usagePermission: `${baseKey}:permission-usage`,
  recordStreak: `${baseKey}:record-streak`,
  seenMilestones: `${baseKey}:seen-milestones`,
  pendingEntryEvent: `${baseKey}:pending-entry-event`,
  seenEntryEvents: `${baseKey}:seen-entry-events`,
  parentProfile: `${baseKey}:parent-profile`,
  schedules: `${baseKey}:care-schedules`,
  messageHistory: `${baseKey}:family-message-history`,
  checkinRecords: `${baseKey}:checkin-records`,
  trustedContacts: `${baseKey}:trusted-contacts`,
  isSample: `${baseKey}:is-sample`,
  selfMedicine: `${baseKey}:self-medicine`,
  selfCheckinCondition: `${baseKey}:self-checkin-condition`,
  selfCheckinMedicine: `${baseKey}:self-checkin-medicine`,
  selfCheckinSchedule: `${baseKey}:self-checkin-schedule`,
  selfCheckinMessage: `${baseKey}:self-checkin-message`,
  consumerSettings: `${baseKey}:consumer-settings`,
  consumerRoutine: `${baseKey}:consumer-routine`,
  consumerSchedules: `${baseKey}:consumer-schedules`,
  notificationSettings: `${baseKey}:notification-settings`,
  kakaoSession: `${baseKey}:kakao-session`,
  lovedOneProfile: `${baseKey}:loved-one-profile`,
  dailyCareCheck: `${baseKey}:daily-care-check`,
  dailyCheckIn: `${baseKey}:daily-check-in`,
  kakaoNotificationHistory: `${baseKey}:kakao-notification-history`,
  careRequestHistory: `${baseKey}:care-request-history`,
  careAutomationSchedule: `${baseKey}:care-automation-schedule`,
  tasksForDate(date: string) {
    return `${baseKey}:care-tasks:${date}`;
  },
};
