import Link from "next/link";
import { ArrowLeft, Check, ChevronRight, CircleAlert, Sparkles } from "lucide-react";

const hospitals=[
  {name:"서울온병원",stage:"30일 활성 운영",health:"Good",reason:"환자 등록과 Alert 처리가 안정적입니다.",newPatients:"18",checkin:"87%",alert:"94%",active:"높음"},
  {name:"해온정형외과",stage:"첫 주간 Review",health:"Watch",reason:"최근 7일 신규 환자 등록이 32% 감소했습니다.",newPatients:"7",checkin:"72%",alert:"81%",active:"보통"},
  {name:"나음병원",stage:"첫 Alert 처리",health:"Risk",reason:"관리자 9일 미사용, 환자 등록이 31명에서 6명으로 감소했습니다.",newPatients:"2",checkin:"51%",alert:"43%",active:"낮음"},
];
const steps=["계약/파일럿 등록","관리자 계정 생성","첫 환자 등록","환자 10명 등록","첫 Check-in","첫 Alert 처리","첫 주간 Review","30일 활성 운영"];
export default function Page(){return <main className="min-h-screen bg-[#f2f4f4] p-5 text-[#18231f] lg:p-10"><div className="mx-auto max-w-[1380px]"><Link href="/internal" className="flex items-center gap-2 font-black text-[#62736c]"><ArrowLeft size={18}/>Hospital CRM</Link><div className="mt-7"><p className="text-sm font-black text-[#1d6b5b]">HOSPITAL ACTIVATION</p><h1 className="mt-2 text-4xl font-black">계약 후 실제 사용까지</h1><p className="mt-2 font-semibold text-[#687771]">병원이 제품을 활성화하고 계속 가치를 만들고 있는지 확인합니다.</p></div><section className="mt-7 overflow-x-auto rounded-3xl border border-[#dbe2df] bg-white p-6"><div className="flex min-w-[1000px] items-start">{steps.map((s,i)=><div key={s} className="flex flex-1 items-center"><div className="text-center"><span className={`mx-auto grid size-9 place-items-center rounded-full ${i<6?"bg-[#1d6b5b] text-white":"bg-[#dfe7e3] text-[#73817c]"}`}>{i<6?<Check size={17}/>:i+1}</span><p className="mt-2 text-xs font-black">{s}</p></div>{i<steps.length-1&&<span className={`mb-6 h-1 flex-1 ${i<5?"bg-[#87b6a9]":"bg-[#e1e7e4]"}`}/>}</div>)}</div></section><section className="mt-6 space-y-4">{hospitals.map(h=><article key={h.name} className="rounded-3xl border border-[#dbe2df] bg-white p-6"><div className="grid gap-5 lg:grid-cols-[1.2fr_2fr_auto] lg:items-center"><div><div className="flex items-center gap-3"><h2 className="text-xl font-black">{h.name}</h2><Health value={h.health}/></div><p className="mt-2 text-sm font-bold text-[#70807a]">현재 단계 · {h.stage}</p></div><div className="grid grid-cols-4 gap-3"><Small label="7일 신규" value={`${h.newPatients}명`}/><Small label="Check-in" value={h.checkin}/><Small label="Alert 처리" value={h.alert}/><Small label="담당자 활동" value={h.active}/></div><Link href="/internal" className="flex min-h-11 items-center justify-center gap-1 rounded-xl bg-[#edf4f1] px-4 font-black text-[#1d6b5b]">Account 360 <ChevronRight size={16}/></Link></div><div className={`mt-5 flex items-center gap-3 rounded-xl p-4 text-sm font-bold ${h.health==="Good"?"bg-[#edf7f3] text-[#286654]":h.health==="Watch"?"bg-[#fff8e8] text-[#8b651d]":"bg-[#fff0eb] text-[#a34329]"}`}><CircleAlert size={18}/><strong>근거</strong> · {h.reason}</div><div className="mt-4 flex flex-col justify-between gap-3 border-t pt-4 sm:flex-row sm:items-center"><p className="font-bold"><span className="text-[#1d6b5b]">Next Action</span> · {h.health==="Good"?"8/27 Pilot 30일 Review":h.health==="Watch"?"환자관리 담당자 UX 피드백 확인":"담당자 활성도 회복 미팅"}</p><p className="text-sm font-bold text-[#71807a]">담당 · 김지원 · 8/27</p></div></article>)}</section><section className="mt-6 rounded-3xl bg-[#172f2a] p-6 text-white"><div className="flex items-start gap-3"><Sparkles className="text-[#91c7b8]"/><div><h2 className="text-xl font-black">Health는 복잡한 AI Score가 아닙니다.</h2><p className="mt-2 font-semibold leading-7 text-white/65">현재는 환자 등록, Check-in, Care Manager 활동, Alert 처리의 관찰 상태를 Good·Watch·Risk로만 표시하며 항상 근거를 함께 보여줍니다.</p></div></div></section></div></main>}
function Health({value}:{value:string}){return <span className={`rounded-full px-3 py-1 text-xs font-black ${value==="Good"?"bg-[#dff1ea] text-[#286654]":value==="Watch"?"bg-[#fff0c9] text-[#8b651d]":"bg-[#fde4dc] text-[#a34329]"}`}>{value}</span>}
function Small({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold text-[#7a8883]">{label}</p><p className="mt-1 font-black">{value}</p></div>}
