import Link from "next/link";
import { ArrowRight, Check, ChevronRight, ClipboardCheck, Footprints, HeartHandshake, Hospital, Radar, Smartphone, UserRound } from "lucide-react";

export default function HospitalLandingPage() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F8FAF8] text-[#18251F]">
    <Header />
    <section className="border-b border-[#DCE5E0] bg-[#EEF4F0] px-5 py-12 sm:px-8 sm:py-16 lg:py-20"><div className="mx-auto grid max-w-[1220px] items-center gap-10 lg:grid-cols-[.95fr_1.05fr]"><div><p className="typo-label font-semibold text-[#2D6A50]">퇴원 후 생활 회복 관리</p><h1 className="typo-display mt-4">퇴원하면,<br/>병원 밖의 회복은<br className="sm:hidden"/> 잘 보이지 않습니다.</h1><p className="typo-body-readable mt-5">오늘안부는 퇴원 후 환자의 일상 변화를 살펴봅니다.<br/>평소와 다른 변화가 이어질 때 확인하도록 돕습니다.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/app?role=hospital" className="flex min-h-[64px] items-center justify-center gap-2 rounded-2xl bg-[#245C45] px-6 text-xl font-bold text-white">병원용 서비스 살펴보기 <ArrowRight size={22}/></Link><Link href="/app?role=parent" className="flex min-h-[64px] items-center justify-center rounded-2xl border-2 border-[#9EB5A9] bg-white px-6 text-xl font-bold text-[#245C45]">퇴원환자 화면 보기</Link></div></div><DashboardPreview /></div></section>
    <section className="px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto max-w-[1040px]"><p className="typo-label font-semibold text-[#B6532A]">퇴원 후 관리의 빈 구간</p><h2 className="typo-section-title mt-3">병원의 시야는 퇴원과 함께 끊어집니다.</h2><p className="typo-body-readable mt-4">다음 외래까지 환자가 집에서 어떻게 지내는지 확인하기 어렵습니다.</p><div className="mt-8 grid items-center gap-3 sm:grid-cols-[1fr_auto_1fr]"><FlowBox items={["입원","치료","퇴원","?","다음 외래"]} highlight="?"/><ArrowRight className="mx-auto rotate-90 text-[#819087] sm:rotate-0"/><FlowBox items={["퇴원","오늘안부","생활 변화 확인","필요 시 후속 확인"]} highlight="오늘안부"/></div></div></section>
    <section className="border-y border-[#DCE5E0] bg-white px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto max-w-[1120px]"><p className="typo-label font-semibold text-[#2D6A50]">오늘안부의 역할</p><h2 className="typo-section-title mt-3">병원 밖의 생활 변화를 연결합니다.</h2><div className="mt-8 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[[UserRound,"퇴원환자"],[Smartphone,"생활 데이터"],[Footprints,"개인별 평소 기준"],[Radar,"변화 감지"],[ClipboardCheck,"확인 필요 환자"],[Hospital,"병원 / 가족"]].map(([Icon,label],index)=><div key={String(label)} className="relative rounded-2xl border border-[#DCE5E0] bg-[#F8FAF8] p-4 text-center"><Icon className="mx-auto text-[#2D6A50]" size={28}/><p className="mt-3 font-bold">{String(label)}</p>{index<5?<ChevronRight className="absolute -right-4 top-1/2 z-10 hidden -translate-y-1/2 text-[#92A097] sm:block"/>:null}</div>)}</div></div></section>
    <section className="px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto grid max-w-[1120px] gap-8 lg:grid-cols-2"><div><p className="typo-label font-semibold text-[#B6532A]">병원 Dashboard</p><h2 className="typo-section-title mt-3">확인이 필요한 환자를 먼저 봅니다.</h2><p className="typo-body-readable mt-4">전체 환자의 숫자보다 변화가 이어진 기간과 가족 확인 여부를 먼저 보여드립니다.</p><ul className="mt-6 grid gap-3 text-lg font-medium">{["개인 기준선 대비 변화","변화 지속기간","가족의 확인 여부","병원의 후속 확인"].map(item=><li key={item} className="flex gap-3"><Check className="mt-1 shrink-0 text-[#2D6A50]"/>{item}</li>)}</ul><Link href="/app?role=hospital" className="mt-7 inline-flex min-h-[60px] items-center gap-2 rounded-2xl bg-[#245C45] px-6 text-lg font-bold text-white">병원 Dashboard 체험 <ArrowRight size={20}/></Link></div><DashboardPreview /></div></section>
    <section className="bg-[#244D3C] px-5 py-14 text-white sm:px-8 lg:py-20"><div className="mx-auto grid max-w-[1040px] items-center gap-8 lg:grid-cols-2"><div><p className="typo-label font-semibold text-[#BFD8CA]">퇴원환자 경험</p><h2 className="typo-section-title mt-3 text-white">환자는 평소처럼 생활하면 됩니다.</h2><p className="mt-4 max-w-[600px] text-xl font-medium leading-8 text-white/80">매일 긴 내용을 기록하지 않습니다. 필요한 날에만 짧은 안내를 확인합니다.</p></div><div className="rounded-[26px] bg-white p-6 text-[#18251F]"><p className="text-lg font-semibold text-[#52635C]">오늘 상태</p><h3 className="mt-2 text-[1.75rem] font-bold">오늘도 평소와 비슷해요.</h3><p className="mt-3 text-lg text-[#52635C]">지금은 따로 하실 일이 없습니다.</p><div className="mt-5 border-t border-[#E1E7E3] pt-5"><p className="font-bold">가족에게 소식이 왔어요.</p><p className="mt-2 text-[#52635C]">가족 소식은 환자의 지속 사용을 돕고 병원에는 공유되지 않습니다.</p></div></div></div></section>
    <section className="px-5 py-14 text-center sm:px-8 lg:py-20"><HeartHandshake className="mx-auto text-[#2D6A50]" size={42}/><h2 className="typo-section-title mx-auto mt-4 max-w-[760px]">퇴원 후 생활 변화와 필요한 후속 확인을 연결하세요.</h2><Link href="/app?role=hospital" className="mx-auto mt-7 flex min-h-[64px] max-w-[360px] items-center justify-center gap-2 rounded-2xl bg-[#245C45] px-6 text-xl font-bold text-white">병원용 오늘안부 살펴보기 <ArrowRight size={22}/></Link><p className="mx-auto mt-5 max-w-[720px] text-sm leading-6 text-[#68756E]">오늘안부는 질병 진단, 응급 판별 또는 의료진의 판단을 대신하는 서비스가 아닙니다.</p></section>
  </main>;
}

function Header(){return <header className="border-b border-[#DCE5E0] bg-white"><div className="mx-auto flex min-h-[70px] max-w-[1220px] items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-2 text-lg font-bold text-[#245C45]"><span className="flex size-10 items-center justify-center rounded-xl bg-[#E6F0EA]"><Hospital size={22}/></span>오늘안부</Link><Link href="/app?role=hospital" className="font-bold text-[#245C45]">병원 화면</Link></div></header>}
function DashboardPreview(){return <div className="rounded-[28px] border border-[#CBD8D1] bg-white p-5 shadow-[0_20px_55px_rgba(36,77,60,.12)]"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#617068]">퇴원환자 관리</p><h2 className="mt-1 text-xl font-bold">오늘 확인 필요</h2></div><span className="rounded-full bg-[#FFF0E8] px-3 py-1 text-sm font-bold text-[#A7441E]">7명</span></div><div className="mt-5 grid gap-3">{[["확인 필요","김○○ · 퇴원 8일차","활동 감소 4일 지속"],["관찰","박○○ · 퇴원 12일차","생활 리듬 변화 2일 지속"],["안정","이○○ · 퇴원 15일차","평소 생활 수준으로 회복 중"]].map(([state,name,detail],index)=><div key={name} className="rounded-2xl bg-[#F4F7F5] p-4"><div className="flex items-center justify-between gap-3"><strong>{name}</strong><span className={`text-sm font-bold ${index===0?"text-[#A7441E]":index===1?"text-[#80611A]":"text-[#356641]"}`}>{state}</span></div><p className="mt-2 text-sm text-[#627068]">{detail}</p></div>)}</div></div>}
function FlowBox({items,highlight}:{items:string[];highlight:string}){return <div className="flex flex-wrap items-center justify-center gap-2 rounded-[24px] border border-[#DCE5E0] bg-white p-5">{items.map((item,index)=><div key={`${item}-${index}`} className="flex items-center gap-2"><span className={`rounded-xl px-3 py-2 font-bold ${item===highlight?"bg-[#D95423] text-white":"bg-[#EEF3F0] text-[#405249]"}`}>{item}</span>{index<items.length-1?<ArrowRight size={17} className="text-[#8A9990]"/>:null}</div>)}</div>}
