import Link from "next/link";
import { ArrowRight, Check, ClipboardCheck, Footprints, HeartHandshake, Hospital } from "lucide-react";

export default function HospitalLandingPage() {
  return <main className="min-h-screen overflow-x-hidden bg-[#F8FAF8] text-[#18251F]">
    <Header />
    <section className="border-b border-[#DCE5E0] bg-[#EEF4F0] px-5 py-10 sm:px-8 sm:py-14 lg:py-16"><div className="mx-auto grid max-w-[1120px] items-center gap-8 lg:grid-cols-[1.05fr_.95fr]"><div><p className="typo-label font-semibold text-[#2D6A50]">퇴원 후 생활 회복 관리</p><h1 className="typo-display mt-4">퇴원 후 회복을<br/>병원 밖에서도 이어갑니다.</h1><p className="typo-body-readable mt-5">생활 변화를 살펴보고,<br/>확인이 필요한 환자를 먼저 알려드립니다.</p><Link href="/app?role=hospital" className="mt-7 inline-flex min-h-[64px] items-center justify-center gap-2 rounded-2xl bg-[#245C45] px-7 text-xl font-bold text-white">병원 화면 체험 <ArrowRight size={22}/></Link></div><RecoverySummary /></div></section>
    <section className="px-5 py-12 sm:px-8 lg:py-16"><div className="mx-auto max-w-[1040px] text-center"><p className="typo-label font-semibold text-[#B6532A]">왜 필요한가요?</p><h2 className="typo-section-title mt-3">다음 외래까지의 변화를 놓치지 않습니다.</h2><div className="mt-8 grid gap-3 sm:grid-cols-3"><SimpleCard icon={<Footprints/>} title="평소 기준 확인" text="환자마다 다른 생활 흐름을 봅니다."/><SimpleCard icon={<ClipboardCheck/>} title="이어지는 변화 확인" text="하루보다 변화의 지속을 봅니다."/><SimpleCard icon={<HeartHandshake/>} title="후속 확인 연결" text="필요한 환자부터 확인합니다."/></div></div></section>
    <section className="border-y border-[#DCE5E0] bg-white px-5 py-12 sm:px-8 lg:py-16"><div className="mx-auto grid max-w-[1120px] items-center gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="typo-label font-semibold text-[#2D6A50]">병원 화면</p><h2 className="typo-section-title mt-3">확인이 필요한 순서가<br/>한눈에 보입니다.</h2><p className="typo-body-readable mt-4">변화가 오래 이어진 환자를 위에 보여드립니다.</p></div><DashboardPreview/></div></section>
    <section className="bg-[#244D3C] px-5 py-12 text-white sm:px-8 lg:py-16"><div className="mx-auto grid max-w-[1040px] items-center gap-7 lg:grid-cols-[1fr_auto]"><div><p className="typo-label font-semibold text-[#BFD8CA]">환자와 가족은 간단하게</p><h2 className="typo-section-title mt-3 text-white">환자는 평소처럼 지내고,<br/>가족은 필요한 날만 확인합니다.</h2></div><Link href="/app?role=parent" className="inline-flex min-h-[64px] items-center justify-center rounded-2xl bg-white px-7 text-xl font-bold text-[#245C45]">환자 화면 체험</Link></div></section>
    <section className="px-5 py-12 text-center sm:px-8 lg:py-16"><h2 className="typo-section-title mx-auto max-w-[720px]">퇴원 후 확인이 필요한 환자를<br/>먼저 만나보세요.</h2><Link href="/app?role=hospital" className="mx-auto mt-7 flex min-h-[64px] max-w-[330px] items-center justify-center gap-2 rounded-2xl bg-[#245C45] px-6 text-xl font-bold text-white">병원 화면 시작 <ArrowRight size={22}/></Link><p className="mx-auto mt-5 max-w-[700px] text-base leading-7 text-[#68756E]">의료진의 진단과 판단을 대신하지 않습니다.</p></section>
  </main>;
}

function Header(){return <header className="border-b border-[#DCE5E0] bg-white"><div className="mx-auto flex min-h-[70px] max-w-[1120px] items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-2 text-lg font-bold text-[#245C45]"><span className="flex size-10 items-center justify-center rounded-xl bg-[#E6F0EA]"><Hospital size={22}/></span>오늘안부</Link><Link href="/app?role=hospital" className="font-bold text-[#245C45]">병원 화면</Link></div></header>}
function RecoverySummary(){return <div className="rounded-[28px] border border-[#CBD8D1] bg-white p-6 shadow-[0_20px_55px_rgba(36,77,60,.10)]"><p className="text-lg font-semibold text-[#52635C]">오늘의 회복 현황</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#F4F7F5] p-5"><strong className="text-3xl text-[#245C45]">24명</strong><p className="mt-2 text-base text-[#52635C]">회복 확인 중</p></div><div className="rounded-2xl bg-[#FFF0E8] p-5"><strong className="text-3xl text-[#A7441E]">7명</strong><p className="mt-2 text-base text-[#6E5549]">확인 필요</p></div></div><p className="mt-5 flex items-center gap-2 font-bold text-[#2D6A50]"><Check size={20}/>변화가 이어진 환자부터 보여드립니다.</p></div>}
function SimpleCard({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="rounded-[24px] border border-[#DCE5E0] bg-white p-6 text-left"><span className="flex size-12 items-center justify-center rounded-2xl bg-[#E8F1EB] text-[#2D6A50]">{icon}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-2 text-lg leading-7 text-[#52635C]">{text}</p></article>}
function DashboardPreview(){return <div className="rounded-[28px] border border-[#CBD8D1] bg-white p-5 shadow-[0_20px_55px_rgba(36,77,60,.12)]"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#617068]">퇴원환자 관리</p><h2 className="mt-1 text-xl font-bold">오늘 확인 필요</h2></div><span className="rounded-full bg-[#FFF0E8] px-3 py-1 text-sm font-bold text-[#A7441E]">7명</span></div><div className="mt-5 grid gap-3">{[["확인 필요","김○○ · 퇴원 8일차","활동 감소 4일 지속"],["관찰","박○○ · 퇴원 12일차","생활 리듬 변화 2일 지속"],["안정","이○○ · 퇴원 15일차","평소 생활 수준으로 회복 중"]].map(([state,name,detail],index)=><div key={name} className="rounded-2xl bg-[#F4F7F5] p-4"><div className="flex items-center justify-between gap-3"><strong>{name}</strong><span className={`text-sm font-bold ${index===0?"text-[#A7441E]":index===1?"text-[#80611A]":"text-[#356641]"}`}>{state}</span></div><p className="mt-2 text-sm text-[#627068]">{detail}</p></div>)}</div></div>}
