import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, LockKeyhole, UserRound, UsersRound } from "lucide-react";

export default function LandingPage() {
  return <main className="min-h-screen bg-[#FFF9F0] text-[#20302C]">
    <header className="border-b border-[#E3E8DF] bg-[#FFF9F0]/95"><div className="mx-auto flex min-h-[84px] max-w-[1240px] items-center justify-between px-6"><Link href="/" className="flex items-center gap-3 text-2xl font-black text-[#315B3D]"><Image src="/brand/brand-icon.png" alt="" width={46} height={46} className="rounded-xl"/>오늘안부</Link><Link href="/help" className="flex min-h-12 items-center px-4 text-lg font-black text-[#52635C] underline underline-offset-4">도움말</Link></div></header>

    <section className="mx-auto grid max-w-[1320px] items-center gap-8 px-6 py-8 lg:min-h-[600px] lg:grid-cols-[1.16fr_.84fr] lg:py-10 xl:gap-12">
      <div><p className="text-lg font-black text-[#D95C24]">부모님과 가족을 위한 오늘안부</p><h1 className="mt-4 max-w-[780px] text-[clamp(3rem,5vw,5rem)] font-black leading-[1.08] tracking-[-.045em]"><span className="block lg:whitespace-nowrap">매일 묻지 않아도,</span><span className="block lg:whitespace-nowrap">다른 날만 알려드립니다.</span></h1><div className="mt-5 max-w-[680px] text-[clamp(1.25rem,1.65vw,1.55rem)] font-bold leading-[1.55] text-[#3F554B]"><p>부모님은 필요한 날에만 답 하나를 누릅니다.</p><p>가족은 필요한 날만 확인합니다.</p></div><div className="mt-7 grid max-w-[720px] gap-4 sm:grid-cols-2"><RoleLink href="/parent-intro" icon={UserRound} title="부모님 30초 체험" text=""/><RoleLink href="/family-intro" icon={UsersRound} title="가족 화면" text=""/></div><p className="mt-4 text-lg font-black text-[#52635C]">체험만으로 가입되거나 결제되지 않습니다.</p></div>
      <div className="relative mx-auto w-full max-w-[620px] lg:justify-self-end"><Image src="/illustrations/todayanbu-hero.png" alt="편안히 생활하는 부모님과 안부를 확인하는 가족" width={760} height={680} priority className="h-auto w-full"/></div>
    </section>

    <section className="px-5 py-16 sm:py-20"><div className="mx-auto max-w-[980px]"><h2 className="text-3xl font-black sm:text-5xl">한쪽은 가볍게 답하고,<br/>한쪽은 필요한 날만 봅니다.</h2><div className="mt-9 grid gap-4 md:grid-cols-2"><Preview role="부모님 화면" title="오늘은 하실 일이 없어요" text="질문이 온 날에도 큰 답 하나만 누릅니다." action="괜찮아요"/><Preview role="가족 화면 · 데모" title="오늘은 평소와 비슷합니다" text="달라진 날에는 이유와 권장 행동을 함께 봅니다." action="지금 할 일은 없어요"/></div></div></section>

    <section className="bg-[#173F35] px-5 py-16 text-white sm:py-20"><div className="mx-auto max-w-[980px]"><h2 className="text-3xl font-black sm:text-5xl">안심하고 체험하세요.</h2><div className="mt-8 grid gap-4 text-xl font-bold sm:grid-cols-3"><p className="flex gap-3"><Check className="shrink-0 text-[#B9E1C0]"/>매일 답하지 않습니다.</p><p className="flex gap-3"><LockKeyhole className="shrink-0 text-[#B9E1C0]"/>카메라로 보지 않습니다.</p><p className="flex gap-3"><Check className="shrink-0 text-[#B9E1C0]"/>체험만으로 결제되지 않습니다.</p></div><Link href="/parent-intro" className="mt-8 flex min-h-16 max-w-[360px] items-center justify-center rounded-2xl bg-white px-6 text-xl font-black text-[#173F35]">부모님 30초 체험 <ArrowRight className="ml-2"/></Link><div className="mt-7 flex flex-wrap gap-5 text-lg font-black"><Link href="/privacy-simple" className="underline underline-offset-4">쉬운 개인정보 안내</Link><Link href="/pricing" className="underline underline-offset-4">요금 안내</Link><Link href="/help" className="underline underline-offset-4">도움말</Link></div></div></section>
    <footer className="border-t border-[#E4E8E1] px-5 py-8 text-center font-bold text-[#68756F]">오늘안부 · 의료 진단이 아닌 생활 변화 안내 서비스</footer>
  </main>;
}

function RoleLink({href,icon:Icon,title,text}:{href:string;icon:typeof UserRound;title:string;text:string}){return <Link href={href} className="group flex min-h-[104px] items-center gap-4 rounded-[24px] border-2 border-[#C9D8C5] bg-white p-5 text-left shadow-[0_12px_28px_rgba(45,70,50,.06)] hover:border-[#6F9471]"><span className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-[#EAF3E5] text-[#315B3D]"><Icon size={29}/></span><span className="flex-1"><strong className="block text-xl font-black sm:text-2xl">{title}</strong>{text&&<span className="mt-2 block text-lg font-bold text-[#65736C]">{text}</span>}</span><ArrowRight size={28} className="text-[#52725B] transition group-hover:translate-x-1"/></Link>}
function Preview({role,title,text,action}:{role:string;title:string;text:string;action:string}){return <article className="rounded-[28px] bg-[#EAF3E5] p-6 sm:p-8"><p className="font-black text-[#D95C24]">{role}</p><div className="mt-4 rounded-[24px] bg-white p-6 shadow-[0_14px_30px_rgba(49,78,58,.08)]"><h3 className="text-2xl font-black">{title}</h3><p className="mt-3 font-bold leading-7 text-[#65736C]">{text}</p><div className="mt-6 flex min-h-14 items-center justify-center rounded-2xl bg-[#2F6B46] px-5 text-lg font-black text-white">{action}</div></div></article>}
