import Link from "next/link";
import { Activity, ArrowDown, ArrowRight, Building2, CalendarCheck, CheckCircle2, ClipboardCheck, Footprints, HeartPulse, Home, MessageSquareText, PhoneCall, ShieldCheck, Stethoscope, UserPlus, Users } from "lucide-react";

const pilotHref="mailto:pilot@oneulanbu.kr?subject=%EC%98%A4%EB%8A%98%EC%95%88%EB%B6%80%20%EC%A0%95%ED%98%95%EC%99%B8%EA%B3%BC%20Pilot%20%EC%8B%A0%EC%B2%AD";
export default function Page(){return <main className="min-h-screen bg-[#FFFCF7] text-[#202923] [font-size:17px]">
  <header className="sticky top-0 z-40 border-b border-[#DDE5DF] bg-[#FFFCF7]/95 backdrop-blur"><div className="mx-auto flex min-h-[76px] max-w-[1220px] items-center justify-between px-5"><Link href="/" className="flex min-h-12 items-center gap-3 text-xl font-bold text-[#29483D]"><span className="grid size-10 place-items-center rounded-xl bg-[#315E50] text-white"><HeartPulse size={21}/></span>오늘안부</Link><nav aria-label="주요 메뉴" className="hidden items-center gap-8 md:flex"><Link href="/console" className="min-h-12 content-center font-semibold text-[#42554C] hover:text-[#315E50] focus-visible:outline focus-visible:outline-2">병원 화면</Link><a href="#pilot" className="min-h-12 content-center font-semibold text-[#42554C] hover:text-[#315E50]">Pilot 안내</a><a href="#faq" className="min-h-12 content-center font-semibold text-[#42554C] hover:text-[#315E50]">FAQ</a></nav><a href={pilotHref} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#315E50] px-5 text-base font-semibold text-white">Pilot 신청하기</a></div></header>
  <section className="border-b border-[#DFE7E1] bg-[#F1F6F2] px-5 py-20 lg:py-28"><div className="mx-auto grid max-w-[1220px] gap-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="max-w-[640px]"><p className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#BED0C7] bg-white px-4 text-base font-bold text-[#315E50]"><ShieldCheck size={19}/>정형외과 퇴원환자 Pilot</p><h1 className="mt-6 text-[2.25rem] font-bold leading-[1.15] tracking-[-.02em] sm:text-[2.65rem] lg:text-[3.25rem]">수술은 끝났지만,<br/>회복은 집에서도<br/><span className="text-[#315E50]">계속됩니다.</span></h1><p className="mt-7 text-xl font-semibold leading-[1.6] text-[#35483F]">퇴원환자 전체에게 연락하지 않아도,<br/>확인이 필요한 환자를 먼저 찾을 수 있습니다.</p><p className="mt-4 text-lg leading-[1.75] text-[#52645B]">환자의 활동과 간단한 회복 체크를 통해 변화를 확인하고 병원의 후속관리를 돕습니다.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={pilotHref} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-[#315E50] px-6 text-[17px] font-semibold text-white">정형외과 Pilot 신청하기 <ArrowRight size={19}/></a><Link href="/console" className="inline-flex min-h-14 items-center justify-center rounded-xl border-2 border-[#AFC2B9] bg-white px-6 text-[17px] font-semibold text-[#315E50]">병원 화면 미리보기</Link></div></div><HeroDashboard/></div></section>
  <section className="px-5 py-24 lg:py-28"><div className="mx-auto max-w-[1140px]"><SectionHead eyebrow="CARE GAP" title="퇴원 후, 병원이 보지 못하는 시간이 생깁니다." body={<>환자가 실제로 얼마나 움직이고, 회복 과정이 어떻게 변하는지<br className="hidden md:block"/> 다음 진료 전까지 확인하기 어렵습니다.</>}/><div className="mt-12 grid gap-3 md:grid-cols-4">{[[Stethoscope,"수술·입원"],[Building2,"퇴원"],[Home,"집에서 회복"],[ShieldCheck,"병원의 관리 공백"]].map(([Icon,label],i)=>{const I=Icon as typeof Home;return <FlowStep key={String(label)} icon={<I/>} label={String(label)} emphasized={i===3}/>})}</div></div></section>
  <section className="bg-[#F2F6F3] px-5 py-24 lg:py-28"><div className="mx-auto max-w-[1140px]"><SectionHead eyebrow="HOW IT WORKS" title="그 사이를 오늘안부가 연결합니다." body="긴 설문이나 복잡한 의료 판단 없이, 병원이 후속관리할 순서를 정리합니다."/><div className="mt-12 grid gap-3 md:grid-cols-4">{[[ClipboardCheck,"집에서 간단한 체크"],[Activity,"생활 변화 확인"],[Users,"확인 필요 환자 선별"],[PhoneCall,"병원 후속 연락"]].map(([Icon,label],i)=>{const I=Icon as typeof Home;return <FlowStep key={String(label)} icon={<I/>} label={String(label)} emphasized={i===2}/>})}</div></div></section>
  <section className="px-5 py-24 lg:py-28"><div className="mx-auto max-w-[1180px]"><SectionHead eyebrow="PRODUCT VALUE" title="모든 환자에게 전화하지 않아도 됩니다." body="오늘안부는 새로운 병원 업무를 만드는 것이 아니라, 기존 퇴원환자 관리의 우선순위를 정하도록 돕습니다."/><div className="mt-12 grid gap-5 lg:grid-cols-2"><Compare title="기존 관리 방식" tone="muted" steps={["퇴원환자 전체","상태 확인이 어려움","전화하거나 다음 내원까지 기다림"]}/><Compare title="오늘안부 사용 후" tone="active" steps={["퇴원환자 전체","회복 상태 확인","변화가 있는 환자 선별","필요한 환자 우선 연락"]}/></div><p className="mt-8 rounded-2xl bg-[#29483D] px-6 py-7 text-center text-2xl font-bold leading-[1.4] text-white">환자 전체 관리에서<br className="sm:hidden"/> 확인이 필요한 환자 중심 관리로</p></div></section>
  <section className="bg-[#F7F4ED] px-5 py-24 lg:py-28"><div className="mx-auto max-w-[1140px]"><SectionHead eyebrow="ORTHOPEDIC PILOT" title={<>퇴원 후 활동 변화가 중요한<br/>정형외과 환자부터 시작합니다.</>} body="정형외과는 오늘안부의 첫 번째 Pilot 대상입니다."/><div className="mt-12 grid gap-5 md:grid-cols-3"><PilotCard icon={<Footprints/>} title="인공관절" text={<>무릎·고관절 수술 후<br/>보행·활동 회복 확인</>}/><PilotCard icon={<Activity/>} title="척추" text={<>척추 수술 후<br/>가정 내 활동 변화 확인</>}/><PilotCard icon={<Home/>} title="골절" text={<>고령 골절 환자의<br/>퇴원 후 회복 확인</>}/></div></div></section>
  <section className="px-5 py-24 lg:py-28"><div className="mx-auto max-w-[1140px]"><SectionHead eyebrow="PILOT METRICS" title="Pilot에서 확인할 지표" body="검증되지 않은 효과를 미리 주장하지 않습니다. 실제 운영 과정에서 아래 지표를 함께 확인합니다."/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["환자 체크인 응답률","확인 필요 환자 비율","병원 후속 연락률","퇴원 이후 관리 지속률"].map(x=><div key={x} className="flex min-h-24 items-center gap-3 rounded-2xl border border-[#DCE4DF] bg-white p-5"><CheckCircle2 className="shrink-0 text-[#315E50]"/><strong className="text-xl">{x}</strong></div>)}</div></div></section>
  <section id="pilot" className="bg-[#F1F6F2] px-5 py-24 lg:py-28"><div className="mx-auto max-w-[1140px]"><SectionHead eyebrow="PILOT PROCESS" title="Pilot은 이렇게 시작합니다." body="복잡한 도입 프로젝트가 아니라, 대상 환자를 정하고 작게 시작합니다."/><ol className="mt-12 grid gap-3 md:grid-cols-5">{[[MessageSquareText,"01","병원 상담"],[Users,"02","대상 환자 설정"],[UserPlus,"03","환자 등록"],[ClipboardCheck,"04","Pilot 운영"],[CalendarCheck,"05","결과 확인"]].map(([Icon,n,label])=>{const I=Icon as typeof Home;return <li key={String(n)} className="relative rounded-2xl border border-[#D9E3DD] bg-white p-5"><I className="text-[#315E50]" size={27}/><span className="mt-8 block text-base font-bold text-[#75837C]">{String(n)}</span><strong className="mt-1 block text-xl">{String(label)}</strong></li>})}</ol></div></section>
  <section id="faq" className="px-5 py-20"><div className="mx-auto max-w-[900px] text-center"><p className="text-lg leading-[1.75] text-[#52645B]">오늘안부는 퇴원 이후<br/>병원이 보지 못했던 회복 기간을 연결합니다.</p></div></section>
  <section className="bg-[#29483D] px-5 py-20 text-white"><div className="mx-auto max-w-[1080px] text-center"><h2 className="text-[2rem] font-bold leading-[1.3] tracking-[-.02em] sm:text-[2.6rem]">퇴원 이후의 회복까지<br/>병원이 확인할 수 있도록</h2><p className="mt-5 text-lg leading-[1.7] text-white/75">정형외과 퇴원환자 Pilot으로<br/>오늘안부를 먼저 경험해보세요.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href={pilotHref} className="inline-flex min-h-14 items-center justify-center rounded-xl bg-white px-6 text-[17px] font-semibold text-[#29483D]">정형외과 Pilot 신청하기</a><Link href="/console" className="inline-flex min-h-14 items-center justify-center rounded-xl border-2 border-white/40 px-6 text-[17px] font-semibold text-white">병원 화면 미리보기</Link></div></div></section>
  <footer className="border-t border-[#DDE5DF] bg-[#FFFCF7] px-5 py-8 text-center text-base text-[#5F6F67]">© 2026 오늘안부 Care · 정형외과 퇴원환자 Pilot</footer>
</main>}
function HeroDashboard(){return <div className="rounded-[22px] border border-[#D3DED8] bg-white p-6 shadow-[0_18px_50px_rgba(37,73,61,.1)] sm:p-8"><div className="border-b border-[#E3E9E5] pb-5"><p className="text-base font-semibold text-[#5D6E66]">오늘의 퇴원환자 관리</p><h2 className="mt-2 text-2xl font-bold leading-[1.4]">128명의 환자 중<br/><span className="text-[#B65234]">오늘 먼저 확인할 환자 7명</span></h2></div><div className="mt-5 grid grid-cols-2 gap-3">{[["관리 중","128명","normal"],["오늘 확인 필요","7명","strong"],["관찰 필요","14명","normal"],["체크인 미응답","11명","normal"]].map(([label,value,tone])=><article key={label} className={`rounded-2xl border p-5 ${tone==="strong"?"border-[#E0A28C] bg-[#FFF0E9]":"border-[#DEE6E1] bg-[#F7F9F7]"}`}><p className={`text-base font-semibold ${tone==="strong"?"text-[#98472F]":"text-[#596A62]"}`}>{label}</p><strong className="mt-2 block text-[1.85rem]">{value}</strong></article>)}</div><p className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-[#EDF3EF] p-4 text-base font-semibold text-[#315E50]"><ArrowDown size={19}/>전체 환자 관리 → 확인 필요 환자 선별</p></div>}
function SectionHead({eyebrow,title,body}:{eyebrow:string;title:React.ReactNode;body:React.ReactNode}){return <div className="max-w-[760px]"><p className="text-base font-bold tracking-[.08em] text-[#315E50]">{eyebrow}</p><h2 className="mt-3 text-[1.75rem] font-bold leading-[1.3] tracking-[-.02em] sm:text-[2.1rem]">{title}</h2><p className="mt-5 text-lg leading-[1.75] text-[#52645B]">{body}</p></div>}
function FlowStep({icon,label,emphasized=false}:{icon:React.ReactNode;label:string;emphasized?:boolean}){return <div className={`relative flex min-h-24 items-center gap-4 rounded-2xl border p-5 md:flex-col md:items-start ${emphasized?"border-[#D79B85] bg-[#FFF0E9] text-[#8F422C]":"border-[#DCE5DF] bg-white"}`}><span className="text-[#315E50] [&>svg]:size-7">{icon}</span><strong className="text-xl">{label}</strong></div>}
function Compare({title,steps,tone}:{title:string;steps:string[];tone:"muted"|"active"}){return <article className={`rounded-[20px] border p-7 ${tone==="active"?"border-[#AFC7BC] bg-[#F0F6F2]":"border-[#E0E4E1] bg-[#FAFAF8]"}`}><h3 className={`text-2xl font-bold ${tone==="active"?"text-[#315E50]":"text-[#59655F]"}`}>{title}</h3><ol className="mt-6 grid gap-3">{steps.map((x,i)=><li key={x} className="flex min-h-14 items-center gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-full text-base font-bold ${tone==="active"?"bg-[#315E50] text-white":"bg-[#E6E9E7] text-[#59655F]"}`}>{i+1}</span><strong className="text-xl">{x}</strong></li>)}</ol></article>}
function PilotCard({icon,title,text}:{icon:React.ReactNode;title:string;text:React.ReactNode}){return <article className="rounded-[20px] border border-[#DEDCD5] bg-white p-7"><span className="grid size-13 place-items-center rounded-2xl bg-[#E8F1EA] p-3 text-[#315E50]">{icon}</span><h3 className="mt-7 text-2xl font-bold">{title}</h3><p className="mt-3 text-lg leading-[1.7] text-[#52645B]">{text}</p></article>}
