import Link from "next/link";
import { ArrowRight, Building2, FileText, Filter, Plus, Users } from "lucide-react";
import { carePatients,statusLabel } from "@/lib/care-demo";

export default function HospitalCarePage(){return <main className="min-h-screen bg-[#F1F5F4] text-[#17221B]"><header className="border-b border-[#D8E2E0] bg-[#173F46] px-5 py-5 text-white"><div className="mx-auto flex max-w-[1180px] items-center justify-between"><Link href="/" className="flex items-center gap-3 text-xl font-black"><Building2/>오늘안부 Care <span className="text-sm text-white/60">병원 Console Demo</span></Link><span className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">서울마음병원</span></div></header><div className="mx-auto max-w-[1180px] px-5 py-8">
  <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-black text-[#1F6F7A]">퇴원환자 Care</p><h1 className="mt-2 text-3xl font-black">확인이 필요한 변화부터 봅니다.</h1><p className="mt-2 font-bold text-[#65736C]">매일 모든 환자를 확인하지 않아도 됩니다.</p></div><Link href="/care/hospital/register" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#1F6F7A] px-5 font-black text-white"><Plus/>퇴원환자 등록</Link></div>
  <section className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={<Users/>} label="Care 진행" value="3명"/><Metric icon={<Filter/>} label="확인할 변화" value="1명"/><Metric icon={<FileText/>} label="30일 리포트" value="1건"/></section>
  <section className="mt-7 overflow-hidden rounded-[22px] border border-[#D9E2DF] bg-white"><div className="border-b border-[#E2E8E6] px-6 py-5"><h2 className="text-xl font-black">환자 목록</h2><p className="mt-1 text-sm font-bold text-[#718079]">생활 변화가 이어진 환자가 위에 표시됩니다.</p></div><div className="hidden grid-cols-[1.2fr_.7fr_.7fr_1.5fr_.25fr] gap-4 border-b bg-[#F7F9F8] px-6 py-3 text-sm font-black text-[#65736C] md:grid"><span>환자</span><span>퇴원</span><span>회복</span><span>최근 변화</span><span/></div>{carePatients.map(p=><Link key={p.id} href={`/care/hospital/${p.id}`} className="grid gap-3 border-b border-[#E8EDEB] px-6 py-5 last:border-0 md:grid-cols-[1.2fr_.7fr_.7fr_1.5fr_.25fr] md:items-center"><div><strong className="text-lg">{p.name}</strong><span className="ml-2 text-sm font-bold text-[#78857E]">{p.age}세</span></div><span className="font-black">D+{p.day}</span><div><strong className="text-[#1F6F7A]">{p.recovery}%</strong><div className="mt-1 h-1.5 rounded-full bg-[#E3EAE7]"><div className="h-full rounded-full bg-[#65A59B]" style={{width:`${p.recovery}%`}}/></div></div><span className={`w-fit rounded-full px-3 py-1.5 text-sm font-black ${p.status==="changed"?"bg-[#FFF0E6] text-[#A54824]":"bg-[#EAF3E5] text-[#315B3D]"}`}>{statusLabel[p.status]} · {p.summary}</span><ArrowRight className="hidden md:block"/></Link>)}</section>
  <p className="mt-5 text-sm font-bold text-[#74817B]">데모 데이터입니다. 의료적 정상·비정상 또는 응급 여부를 판단하지 않습니다.</p>
</div></main>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <article className="rounded-[20px] bg-white p-5"><span className="text-[#1F6F7A]">{icon}</span><p className="mt-3 text-sm font-black text-[#718079]">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></article>}
