import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, LockKeyhole } from "lucide-react";
import { PublicBottomNav } from "@/components/public-bottom-nav";

const roles = [
  { label:"부모님 휴대폰", title:<>평소처럼<br />생활하기</>, text:<>전화하고 산책하고 평소처럼 지내세요.<br />오늘안부가 생활 변화를 살펴드려요.</>, image:"/brand/hero-family.png", href:"/app?role=parent", tone:"bg-[#FFF0E4]", color:"text-[#D95423]", button:"평소처럼 시작하기" },
  { label:"가족 휴대폰", title:<>안심<br />확인하기</>, text:<>부모님의 생활 흐름을 안심 리포트로 보고,<br />필요할 때 따뜻한 응원을 전해요.</>, image:"/brand/family-report.png", href:"/guide", tone:"bg-[#F0F1E8]", color:"text-[#52725B]", button:"오늘 안심 보기" },
  { label:"농장", title:<>함께 키우는 농장<br />둘러보기</>, text:<>안부가 쌓이면 작물이 자라고,<br />시즌 수확의 기쁨으로 이어져요.</>, image:"/brand/farm-mascot.png", href:"/app/farm", tone:"bg-[#EAF3E5]", color:"text-[#52725B]", button:"농장 구경하기" },
];

export default function StartPage(){ return <main className="min-h-screen bg-[#FFF9F0] pb-24 text-[#20302C]"><div className="mx-auto w-full max-w-[760px] px-5 py-6 sm:px-8"><Link href="/" className="inline-flex min-h-12 items-center gap-2 font-black text-[#40534B]"><ArrowLeft size={23} aria-hidden />뒤로</Link><h1 className="mt-6 text-[2.35rem] font-black leading-tight sm:mt-8 sm:text-5xl">누가 먼저<br />시작하시나요? 😊</h1><p className="mt-3 text-lg font-bold text-[#68756F]">사용하실 휴대폰을 골라주세요.</p><div className="mt-6 grid gap-3 sm:mt-8 sm:gap-4">{roles.map((role)=><article key={role.label} className={`grid grid-cols-[minmax(0,1fr)_112px] overflow-hidden rounded-[22px] border border-[#E1E7DD] shadow-[0_16px_40px_rgba(55,72,55,0.07)] sm:grid-cols-[1fr_220px] ${role.tone}`}><div className="p-5 sm:p-6"><span className={`inline-flex rounded-full bg-white px-3 py-1.5 text-xs font-black sm:text-sm ${role.color}`}>{role.label}</span><h2 className="mt-3 text-[1.5rem] font-black leading-tight sm:mt-4 sm:text-[1.75rem]">{role.title}</h2><p className="mt-2 text-sm font-semibold leading-6 text-[#5E6A65] sm:mt-3 sm:text-base sm:leading-7">{role.text}</p><Link href={role.href} className="mt-4 flex min-h-14 w-full items-center justify-between rounded-2xl bg-white px-4 text-base font-black text-[#33473E] shadow-sm sm:mt-5 sm:px-5 sm:text-lg">{role.button}<ArrowRight size={20} className={role.color} aria-hidden /></Link></div><div className="relative min-h-full"><Image src={role.image} alt="" fill className="object-cover" sizes="(max-width:640px) 112px, 220px" /></div></article>)}</div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-white p-4 text-sm font-bold leading-6 text-[#68756F]"><LockKeyhole size={21} className="shrink-0 text-[#52725B]" aria-hidden />가족이 허용한 정보만 안전하게 연결합니다.</div></div><PublicBottomNav /></main>; }
