import Image from "next/image";
import Link from "next/link";
import {ArrowDown,ArrowRight,Building2,Check,CheckCircle2,Clock3,Database,Eye,HeartHandshake,HeartPulse,ShieldCheck,Stethoscope,UserRound,Workflow} from "lucide-react";

const pilotMail="mailto:pilot@oneulanbu.kr?subject=%EC%98%A4%EB%8A%98%EC%95%88%EB%B6%80%20Pilot%20%EB%8F%84%EC%9E%85%20%EB%AC%B8%EC%9D%98";
const solution=["병원에서 수술 정보 등록","환자가 매일 1분 상태 확인","시간에 따른 회복 변화 구조화","확인 필요 환자 우선 확인","후속관리와 결과 기록"];

export function CompanyV2(){return <main className="bg-[#F7F4EC] text-[#1D2923] [font-size:17px]"><Header/>
  <section className="border-b border-[#D9E1DC] px-5 py-20 sm:py-28"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><Eyebrow>오늘안부 CARE</Eyebrow><h1 className="mt-5 text-[2.7rem] font-black leading-[1.1] tracking-[-.045em] sm:text-[4.4rem]">퇴원 후 환자 관리를<br/><span className="text-[#315E50]">병원의 Workflow로.</span></h1><p className="mt-7 max-w-[710px] text-xl font-semibold leading-9 text-[#56675F]">오늘안부는 수술 후 환자의 회복 변화를 구조화하고, 병원이 오늘 확인할 환자와 후속조치를 한곳에서 관리하도록 돕습니다.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/hospital" className="primary-link">병원용 서비스 보기 <ArrowRight size={20}/></Link><a href={pilotMail} className="secondary-link">Pilot 도입 문의</a></div><p className="mt-5 font-bold text-[#6A7972]">정형외과 퇴원환자 관리부터 검증합니다.</p></div><HeroProduct/></div></section>

  <Section n="01" name="PROBLEM" title={<>퇴원하는 순간,<br/>병원에서 보이지 않는 시간이 시작됩니다.</>}><JourneyRow items={["수술","입원","퇴원","집에서 회복","다음 외래"]} accent={3}/><div className="mt-8 grid gap-4 md:grid-cols-3"><Card title="환자 상태가 보이지 않습니다" text="다음 외래까지 통증과 움직임의 변화가 단절됩니다."/><Card title="모든 환자에게 전화할 수 없습니다" text="관리 대상이 늘어날수록 동일한 전화관리는 지속하기 어렵습니다."/><Card title="먼저 보아야 할 환자를 찾기 어렵습니다" text="환자별 변화와 후속조치 기록이 흠어져 있습니다."/></div></Section>

  <Section id="service" n="02" name="SOLUTION" green title={<>모든 환자를 보는 것이 아니라<br/>오늘 확인할 환자를 찾습니다.</>}><JourneyRow items={solution}/><ProductFlow/></Section>

  <Section n="03" name="PATIENT / HOSPITAL VALUE" title="하나의 회복 흐름을 환자와 병원이 함께 보게 합니다."><div className="mt-9 grid gap-5 lg:grid-cols-2"><Value icon={<UserRound/>} label="환자" title="매일 1분, 내 회복을 기록합니다." items={["통증과 움직임","새로운 불편","어제와 다른 상태","내 회복 변화"]}/><Value icon={<Building2/>} label="병원" title="오늘 누구를 먼저 볼지 알 수 있습니다." items={["환자 상태 변화","확인이 필요한 이유","오늘 확인할 환자","후속조치와 처리 이력"]}/></div></Section>

  <Section n="04" name="DIFFERENTIATION" cream title="정형외과의 수술과 퇴원 이후에 집중합니다."><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="정형외과부터" text="정형외과 수술환자를 첫 검증 대상으로 시작합니다."/><Card title="퇴원 후 관리 공백" text="수술과 다음 외래 사이의 시간을 연결합니다."/><Card title="간편한 사용" text="복잡한 장비 없이 환자 상태 확인부터 시작합니다."/><Card title="닫힌 Workflow" text="환자 확인부터 병원의 후속조치와 기록까지 연결합니다."/></div></Section>

  <Section n="05" name="HOSPITAL ROI" title="병원이 얻는 변화"><div className="mt-9 grid gap-4 md:grid-cols-3"><Roi icon={<Clock3/>} title="관리시간 감소" text="모든 환자를 동일하게 확인하는 업무를 줄이는 것이 목표입니다."/><Roi icon={<Eye/>} title="관리 가시성 향상" text="퇴원 이후의 상태 변화와 병원의 후속조치를 한곳에서 확인합니다."/><Roi icon={<HeartHandshake/>} title="환자 관계 지속" text="퇴원이 병원과 환자의 관계가 끊기는 시점이 되지 않도록 합니다."/></div><BeforeAfter/></Section>

  <Section n="06" name="BUSINESS MODEL" green title="퇴원환자 관리 Workflow에 과금하는 B2B SaaS"><p className="mt-5 max-w-[820px] text-xl font-semibold leading-9 text-[#56675F]">병원 단위 구독과 관리환자 기반 과금 모델을 실제 Pilot을 통해 검증합니다.</p><div className="mt-8 grid gap-4 md:grid-cols-3"><Model n="01" title="병원 도입" text="정형외과 퇴원환자 관리 Workflow"/><Model n="02" title="Pilot 검증" text="실제 사용량, 지불의사, 적정 과금방식 확인"/><Model n="03" title="유료전환 검증" text="병원 단위 구독과 관리환자 기반 모델 비교"/></div></Section>

  <Section n="07" name="DATA MOAT" title="수술부터 병원의 실제 후속관리까지 연결합니다."><DataMoat/><p className="mx-auto mt-7 max-w-[850px] text-center text-xl font-semibold leading-9 text-[#56675F]">수술부터 퇴원 후 회복, 병원의 실제 후속관리까지 하나의 데이터 흐름으로 연결합니다.</p></Section>

  <Section n="08" name="DATA FLYWHEEL" cream title="사용할수록 병원의 관리 기준이 더 선명해집니다."><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["환자 상태 확인","회복 변화 누적","병원의 판단과 조치","관리 기준 개선 ↺"].map((x,i)=><div key={x} className="rounded-2xl border bg-white p-6 text-center"><span className="text-sm font-black text-[#3F7563]">0{i+1}</span><h3 className="mt-3 text-xl font-black">{x}</h3></div>)}</div><p className="mt-7 text-center text-xl font-black text-[#315E50]">단순한 환자 수가 아니라, 변화와 병원의 실제 행동이 함께 누적됩니다.</p></Section>

  <Section n="09" name="AI VISION" green title="데이터를 의료진의 시간을 줄이는 업무지원으로."><AiFlow/><div className="mt-7 flex items-start gap-4 rounded-2xl border bg-white p-5"><ShieldCheck className="shrink-0 text-[#315E50]"/><p className="font-semibold leading-8 text-[#56675F]">의료진이 환자를 선별하고 데이터를 확인하는 시간을 줄이는 것은 향후 검증할 목표이자 가설입니다. AI 진단·치료추천을 제공하지 않습니다.</p></div></Section>

  <Section n="10" name="VALIDATION" title="실제 의료현장에서 검증하고 있습니다."><p className="mt-5 max-w-[850px] text-xl font-semibold leading-9 text-[#56675F]">실제 의료현장에서 필요한 Workflow인지 의료진과 퇴원환자를 통해 검증하고 있습니다.</p><div className="mt-8 grid gap-5 lg:grid-cols-2"><Validation title="의료진" items={["현재 퇴원환자 관리시간","오늘안부 사용 시 예상 시간절감","병원 지불의사","적정 과금방식","실제 Pilot 참여의향"]}/><Validation title="퇴원환자" items={["고령 사용자의 사용 가능성","환자 상태 확인 완료율","반복사용 의향","회복 변화 이해도","입력 부담"]}/></div></Section>

  <Section n="11" name="ROADMAP" cream title="Pilot에서 유료전환 검증으로 이어집니다."><Roadmap/></Section>

  <section className="px-5 py-20"><div className="mx-auto max-w-[1050px] rounded-[36px] bg-[#29483D] p-8 text-white sm:p-14"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><Eyebrow>오늘안부 CARE</Eyebrow><h2 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">퇴원 이후의 회복까지<br/>병원과 연결합니다.</h2><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/hospital" className="inline-flex min-h-14 items-center justify-center rounded-xl bg-white px-6 font-black text-[#29483D]">병원용 서비스 보기</Link><a href={pilotMail} className="inline-flex min-h-14 items-center justify-center rounded-xl border-2 border-white/35 px-6 font-black">Pilot 도입 문의</a></div><Link href="/research/orthopedics" className="mt-5 inline-flex items-center gap-2 font-black text-[#C5E1D6]">의료진 제품 검증 참여 <ArrowRight size={18}/></Link></div><Image src="/assets/characters/care-default.png" alt="오늘안부 Care 캐릭터" width={150} height={150} className="mx-auto h-auto w-[130px]"/></div></div></section><Footer/>
</main>}

function Header(){return <header className="sticky top-0 z-40 border-b bg-[#F7F4EC]/95 backdrop-blur"><div className="mx-auto flex min-h-[74px] max-w-[1200px] items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 text-xl font-black text-[#29483D]"><HeartPulse/>오늘안부 Care</Link><nav className="hidden items-center gap-7 md:flex"><a href="#service" className="font-bold">서비스</a><Link href="/hospital" className="font-bold">병원용</Link><Link href="/company" className="font-black text-[#315E50]">오늘안부 소개</Link><Link href="/research/orthopedics" className="font-bold">의료진 검증</Link></nav><Link href="/hospital/dashboard" className="inline-flex min-h-11 items-center rounded-xl bg-[#315E50] px-4 font-black text-white">제품 체험</Link></div></header>}
function Footer(){return <footer className="border-t px-5 py-10"><div className="mx-auto flex max-w-[1200px] flex-col justify-between gap-5 sm:flex-row"><div><p className="font-black text-[#29483D]">오늘안부 Care</p><p className="mt-2 text-sm font-semibold text-[#68766F]">퇴원 후 회복을 병원과 연결합니다.</p></div><nav className="flex flex-wrap gap-5 font-bold text-[#52645B]"><Link href="/">서비스</Link><Link href="/hospital">병원용</Link><Link href="/company">오늘안부 소개</Link><Link href="/research/orthopedics">의료진 검증</Link></nav></div></footer>}
function Section({n,name,title,children,green=false,cream=false,id}:{n:string;name:string;title:React.ReactNode;children:React.ReactNode;green?:boolean;cream?:boolean;id?:string}){return <section id={id} className={`px-5 py-16 sm:py-20 ${green?"bg-[#EAF2ED]":cream?"bg-[#F2EEE4]":"bg-[#FFFCF7]"}`}><div className="mx-auto max-w-[1120px]"><Eyebrow>{n} · {name}</Eyebrow><h2 className="mt-4 text-[2.2rem] font-black leading-[1.2] tracking-[-.035em] sm:text-[3.2rem]">{title}</h2>{children}</div></section>}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="text-sm font-black tracking-[.12em] text-[#3F7563]">{children}</p>}
function Card({title,text}:{title:string;text:string}){return <article className="rounded-2xl border bg-white p-6"><h3 className="text-xl font-black">{title}</h3><p className="mt-3 font-semibold leading-7 text-[#617069]">{text}</p></article>}
function JourneyRow({items,accent=-1}:{items:string[];accent?:number}){return <div className={`mt-9 grid gap-3 ${items.length===5?"md:grid-cols-5":"md:grid-cols-4"}`}>{items.map((x,i)=><div key={x} className={`relative flex min-h-20 items-center justify-center rounded-2xl border p-4 text-center font-black ${i===accent?"border-[#C97755] bg-[#FFF0E8] text-[#9B452B]":"bg-white"}`}>{x}{i<items.length-1&&<ArrowRight className="absolute -right-5 top-1/2 z-10 hidden -translate-y-1/2 md:block" size={20}/>}</div>)}</div>}
function HeroProduct(){return <div className="mx-auto w-full max-w-[520px]"><div className="ml-auto w-[84%] rounded-[26px] border bg-white p-5 shadow-xl"><p className="text-sm font-black text-[#97482F]">오늘 확인 필요</p><h3 className="mt-2 text-xl font-black">통증 5 → 7 · 붓기 응답</h3><div className="mt-4 grid grid-cols-3 gap-2">{["통증 변화","움직임","새 불편"].map(x=><span key={x} className="rounded-xl bg-[#F2F5F3] p-3 text-center text-sm font-bold">{x}</span>)}</div></div><div className="relative -mt-7 w-[70%] rounded-[26px] bg-[#315E50] p-5 text-white shadow-xl"><p className="text-sm font-black text-[#B7D8CB]">오늘 상태 확인</p><p className="mt-2 text-3xl font-black">통증 6 / 10</p><div className="mt-4 h-2 rounded-full bg-white/20"><div className="h-full w-3/5 rounded-full bg-[#D9A16B]"/></div></div></div>}
function ProductFlow(){return <div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-[28px] bg-white p-6"><p className="text-sm font-black text-[#315E50]">환자 상태 확인</p><h3 className="mt-2 text-2xl font-black">오늘 상태를 1분 안에</h3><div className="mt-5 grid grid-cols-2 gap-3">{["통증","움직임","새로운 불편","어제 대비"].map(x=><div key={x} className="rounded-xl bg-[#F2F4F1] p-4 font-black">{x}</div>)}</div></div><div className="rounded-[28px] bg-[#29483D] p-6 text-white"><p className="text-sm font-black text-[#A9D2C2]">오늘 확인할 환자</p><h3 className="mt-2 text-2xl font-black">먼저 확인할 환자와 이유</h3>{[["김OO","통증 5 → 7 · 붓기"],["박OO","움직임이 더 불편해짐"]].map(([a,b])=><div key={a} className="mt-3 rounded-xl bg-white/10 p-4"><strong>{a}</strong><p className="mt-1 text-white/75">{b}</p></div>)}</div></div>}
function Value({icon,label,title,items}:{icon:React.ReactNode;label:string;title:string;items:string[]}){return <article className="rounded-[28px] border bg-white p-7"><span className="grid size-12 place-items-center rounded-xl bg-[#E5F0EA] text-[#315E50]">{icon}</span><p className="mt-5 font-black text-[#3F7563]">{label}</p><h3 className="mt-2 text-2xl font-black">{title}</h3><ul className="mt-6 grid gap-3 sm:grid-cols-2">{items.map(x=><li key={x} className="flex gap-2 font-bold"><CheckCircle2 size={19} className="shrink-0 text-[#56806F]"/>{x}</li>)}</ul></article>}
function Roi({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="rounded-2xl border bg-white p-6"><span className="grid size-12 place-items-center rounded-xl bg-[#E5F0EA] text-[#315E50]">{icon}</span><h3 className="mt-5 text-2xl font-black">{title}</h3><p className="mt-3 font-semibold leading-8 text-[#617069]">{text}</p></article>}
function BeforeAfter(){const before=["퇴원","상태 확인 어려움","개별 전화 또는 다음 외래","정보 분산"];const after=["퇴원","매일 상태 확인","변화 구조화","확인 필요 환자","병원 후속관리"];return <div className="mt-8 grid gap-4 lg:grid-cols-2"><FlowBox label="BEFORE" items={before} muted/><FlowBox label="AFTER" items={after}/></div>}
function FlowBox({label,items,muted=false}:{label:string;items:string[];muted?:boolean}){return <div className={`rounded-[28px] p-6 ${muted?"border bg-[#F6F3ED]":"bg-[#29483D] text-white"}`}><p className={`text-sm font-black ${muted?"text-[#8A766B]":"text-[#A9D2C2]"}`}>{label}</p><div className="mt-5 flex flex-col gap-2 sm:flex-row sm:items-center">{items.map((x,i)=><div key={x} className="contents"><span className={`flex min-h-14 flex-1 items-center justify-center rounded-xl px-3 text-center text-sm font-black ${muted?"bg-white":"bg-white/10"}`}>{x}</span>{i<items.length-1&&<ArrowRight className="mx-auto shrink-0 rotate-90 sm:rotate-0" size={18}/>}</div>)}</div></div>}
function Model({n,title,text}:{n:string;title:string;text:string}){return <article className="rounded-2xl bg-white p-6"><span className="text-sm font-black text-[#3F7563]">{n}</span><h3 className="mt-3 text-2xl font-black">{title}</h3><p className="mt-3 font-semibold leading-7 text-[#617069]">{text}</p></article>}
function DataMoat(){const data=["어떤 수술을 받았는가","퇴원 후 어떻게 변했는가","병원은 어떻게 판단했는가","실제로 어떤 조치를 했는가"];return <div className="mt-9"><div className="grid gap-3 md:grid-cols-4">{data.map((x,i)=><div key={x} className="relative flex min-h-28 items-center justify-center rounded-2xl border bg-white p-5 text-center font-black">{x}{i<data.length-1&&<span className="absolute -right-3.5 top-1/2 z-10 hidden -translate-y-1/2 rounded-full bg-[#F7F4EC] p-1 text-[#315E50] md:block">×</span>}</div>)}</div><ArrowDown className="mx-auto my-5 text-[#315E50]"/><div className="mx-auto max-w-[700px] rounded-[28px] bg-[#29483D] p-8 text-center text-white"><Database className="mx-auto text-[#A9D2C2]"/><h3 className="mt-4 text-3xl font-black">수술 후 연속 회복 데이터</h3></div></div>}
function AiFlow(){const steps=["구조화된 회복 데이터","회복 변화 분석","의료진용 변화 자동 요약","확인 필요 후보 추천 지원","환자 선별·확인 시간 감소 목표"];return <div className="mt-9 grid gap-3 md:grid-cols-5">{steps.map((x,i)=><div key={x} className={`relative flex min-h-28 items-center justify-center rounded-2xl p-5 text-center font-black ${i===4?"border-2 border-dashed border-[#315E50] bg-white":"bg-white"}`}>{x}{i<steps.length-1&&<ArrowRight className="absolute -right-5 top-1/2 z-10 hidden -translate-y-1/2 text-[#547A6C] md:block"/>}</div>)}</div>}
function Validation({title,items}:{title:string;items:string[]}){return <article className="rounded-[26px] border bg-white p-7"><h3 className="text-2xl font-black">{title}</h3><ul className="mt-5 space-y-3">{items.map(x=><li key={x} className="flex gap-3 font-semibold leading-7"><CheckCircle2 className="shrink-0 text-[#315E50]" size={20}/>{x}</li>)}</ul></article>}
function Roadmap(){const steps=[["01","MVP","Patient ↔ Hospital E2E"],["02","Validation","의료진 + 퇴원환자"],["03","Pilot","실제 정형외과 소규모 운영"],["04","Paid Validation","유료전환 및 과금모델 검증"],["05","Scale","다기관 확대"],["06","AI","의료진 업무지원"]];return <div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{steps.map(([n,t,d])=><article key={n} className="rounded-2xl border bg-white p-5"><span className="font-black text-[#4F7A6B]">{n}</span><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-3 font-semibold leading-7 text-[#617069]">{d}</p></article>)}</div>}
