"use client";
import {useState} from "react";
import {getHospitalSession} from "@/lib/demo-auth";
import {loadCareState,loadPublicDemoCareState,saveCareState,savePublicDemoCareState,type CareState} from "@/lib/care-mvp";
export function HospitalContactSettings({state,hospitalId,demo,onSaved}:{state:CareState;hospitalId:string;demo:boolean;onSaved:(state:CareState)=>void}){
 const hospital=state.hospitals.find(h=>h.id===hospitalId),[phone,setPhone]=useState(hospital?.phone||""),[hours,setHours]=useState(hospital?.openingHours||""),[address,setAddress]=useState(hospital?.address||""),[message,setMessage]=useState("");
 return <section className="max-w-2xl rounded-3xl bg-white p-6"><h1 className="text-2xl font-black">병원 연락 정보</h1><p className="mt-3 leading-7">환자가 바로 연락할 수 있도록 대표전화·진료시간·주소를 모두 등록해주세요. 저장한 정보는 환자 병원 안내에 표시됩니다.</p><form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();try{const session=getHospitalSession();if(!demo&&(!session||session.hospitalId!==hospitalId||!["owner","hospital_admin"].includes(session.role)))throw Error();if(!/^\+?\d{7,15}$/.test(phone.replace(/[\s().-]/g,""))){setMessage("연락 가능한 전화번호를 입력해주세요.");return;}const latest=demo?loadPublicDemoCareState():loadCareState();const next={...latest,hospitals:latest.hospitals.map(h=>h.id===hospitalId?{...h,phone:phone.trim(),openingHours:hours.trim(),address:address.trim()}:h)};(demo?savePublicDemoCareState:saveCareState)(next);onSaved(next);setMessage("병원 연락 정보를 저장했어요.");}catch{setMessage("저장하지 못했어요. 관리자 연결과 저장 설정을 확인해주세요.");}}}>
 {[["대표전화",phone,setPhone],["진료시간",hours,setHours],["주소",address,setAddress]].map(([label,value,setter])=><label key={String(label)} className="block font-bold">{String(label)}<input required value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border p-3" maxLength={200}/></label>)}<button className="min-h-12 rounded-xl bg-[#315E50] px-6 font-bold text-white">연락 정보 저장</button><p role="status">{message}</p></form></section>;
}
