"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { ArrowLeft, Check, LayoutDashboard, List } from "lucide-react";
import { AccessGuard } from "@/components/access-guard";
import { RecoveryTrend } from "@/components/recovery-trend";
import { comparisonLabels, daysSince, loadCareState, loadPublicDemoCareState, mobilityLabels, painValue, saveCareState, savePublicDemoCareState, shiftCareDate, statusLabels, TODAY, type CareState, type FollowUp } from "@/lib/care-mvp";
import { hasHospitalPermission, type HospitalSession } from "@/lib/demo-auth";
import type { ActionType, StaffDecision } from "@/domain/care-events";
import { trackCareEvent } from "@/lib/care-analytics";

const idMap: Record<string, string> = { kim: "patient_001", lee: "patient_002", jung: "patient_003", park: "patient_004" };
const actionTypes: Record<string, ActionType> = {
  "전화 확인": "phone_call", "문자 안내": "additional_monitoring", "경과관찰": "additional_monitoring",
  "의료진 확인 요청": "additional_monitoring", "외래 확인 검토": "visit_recommended", 기타: "other",
};

export default function PatientDetail({ demo = false }: { demo?: boolean }) {
  if (demo) return <Detail session={{kind:"hospital",sessionId:"public-demo",userId:"hu_a_nurse",hospitalId:"hospital_001",role:"nurse",expiresAt:"2999-12-31T00:00:00.000Z"}} demo />;
  return <AccessGuard area="hospital">{session => <Detail session={session as HospitalSession} />}</AccessGuard>;
}

function Detail({ session, demo = false }: { session: HospitalSession; demo?: boolean }) {
  const slug = usePathname().split("/").at(-1) || "kim";
  const [state, setState] = useState<CareState | null>(null);
  const [routePatientId, setRoutePatientId] = useState<string | null>(null);
  const [action, setAction] = useState("");
  const [recordStatus, setRecordStatus] = useState<"completed" | "scheduled">("completed");
  const [handler, setHandler] = useState(session.role === "doctor" ? "담당의" : "간호사");
  const [note, setNote] = useState("");
  const [followUpDueDate, setFollowUpDueDate] = useState("");
  const [followUpNote, setFollowUpNote] = useState("");
  const [contactResult, setContactResult] = useState<"connected" | "guardian" | "unreachable">("connected");
  const [patientCondition, setPatientCondition] = useState<"improved" | "same" | "worse" | "needs_review">("same");
  const [careResult, setCareResult] = useState<"monitor" | "daily_guidance" | "medication_check" | "clinician_handoff" | "outpatient_guidance" | "urgent_guidance">("monitor");
  const [assignedTo, setAssignedTo] = useState("");
  const [resultNotes, setResultNotes] = useState<Record<string, string>>({});
  const [resultHandlers, setResultHandlers] = useState<Record<string, string>>({});
  const [saved, setSaved] = useState(false);
  const [savedActionId, setSavedActionId] = useState("");
  const [feedbackSaved, setFeedbackSaved] = useState(false);
  const [completionReason, setCompletionReason] = useState<"program_completed"|"after_outpatient"|"transferred"|"patient_request"|"hospital_decision"|"other">("program_completed");
  const [guided,setGuided]=useState(false);
  const [saveError,setSaveError]=useState("");
  const [editingActionId,setEditingActionId]=useState(""),[editActionType,setEditActionType]=useState(""),[editActionNote,setEditActionNote]=useState("");
  const [confirmCompletion,setConfirmCompletion]=useState(false);
  const viewedSignalId=useRef("");

  useEffect(() => { const params=new URLSearchParams(location.search);setRoutePatientId(params.get("patientId"));setGuided(demo&&params.has("guided")); setState(demo ? loadPublicDemoCareState() : loadCareState()); }, [demo]);
  useEffect(()=>{if(!state||!routePatientId)return;const signal=state.careSignals?.find(item=>item.patientId===routePatientId&&item.status!=="resolved");if(!signal||viewedSignalId.current===signal.id)return;const task=state.careTasks?.find(item=>item.patientId===routePatientId&&item.status!=="done");viewedSignalId.current=signal.id;trackCareEvent("care_signal_viewed",{patientId:routePatientId,hospitalId:session.hospitalId,careSignalId:signal.id,careTaskId:task?.id,demo})},[state,routePatientId,demo,session.hospitalId]);
  if (!state) return <main className="p-10 text-center font-bold">환자 정보를 불러오고 있습니다.</main>;
  const current = state;

  const requestedPatientId = routePatientId || idMap[slug] || slug;
  const patient = state.patients.find(p => p.id === requestedPatientId && p.hospitalId === session.hospitalId)!;
  if (!patient) return <main className="grid min-h-screen place-items-center bg-slate-100 p-6"><section className="max-w-lg rounded-3xl bg-white p-8 text-center"><h1 className="text-2xl font-black">이 정보에 접근할 권한이 없습니다.</h1><p className="mt-3 text-slate-600">환자가 존재하지 않거나 현재 병원 소속이 아닙니다.</p><Link href={demo ? "/demo/hospital" : "/hospital/dashboard"} className="mt-6 flex h-12 items-center justify-center rounded-xl bg-[#315E50] font-black text-white">오늘 할 일로 돌아가기</Link></section></main>;
  const checks = state.checkIns.filter(c => c.patientId === patient.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const follows = state.followUps.filter(f => f.patientId === patient.id).sort((a, b) => eventTime(b).localeCompare(eventTime(a)));
  const actions = (state.careActions||[]).filter(item=>item.patientId===patient.id).sort((a,b)=>(b.updatedAt||b.createdAt).localeCompare(a.updatedAt||a.createdAt));
  const status = state.statuses.find(s => s.patientId === patient.id);
  const latest = checks[0], previous = checks[1], episode = state.episodes.find(e => e.patientId === patient.id);
  const task = state.careTasks?.filter(item => item.patientId === patient.id && item.status !== "done").sort((a,b) => b.createdAt.localeCompare(a.createdAt))[0];
  const activeAssignee = assignedTo || task?.assignedTo || patient.assignedNurse || "";
  const canManageActions = demo || hasHospitalPermission(session.role, "CREATE_CARE_ACTION");
  const params=typeof window!=="undefined"?new URLSearchParams(location.search):null,listHref=params?.get("returnTo")||(demo?"/demo/hospital":"/hospital/dashboard"),dashboardHref=demo?"/demo/hospital":"/hospital/dashboard";
  const priorityRank:Record<string,number>={needs_attention:0,no_response:1,watch:2,stable:3},orderedPatients=state.patients.filter(item=>item.hospitalId===session.hospitalId).sort((a,b)=>(priorityRank[state.statuses.find(s=>s.patientId===a.id)?.level||"stable"]-priorityRank[state.statuses.find(s=>s.patientId===b.id)?.level||"stable"])),patientIndex=orderedPatients.findIndex(item=>item.id===patient.id),previousPatient=orderedPatients[patientIndex-1],nextPatient=orderedPatients[patientIndex+1],patientHref=(id:string)=>`${demo?"/demo/hospital/patient":"/care/hospital/kim"}?patientId=${encodeURIComponent(id)}&returnTo=${encodeURIComponent(listHref)}`;

  function saveAction() {
    if (!canManageActions) { setSaveError("현재 역할에는 조치를 기록할 권한이 없습니다."); return; }
    if (!patient || !action || !handler.trim() || !episode || (recordStatus === "scheduled" && !followUpDueDate)) return;
    const latestState=demo?loadPublicDemoCareState():loadCareState(),latestTask=latestState.careTasks?.find(item=>item.id===task?.id);
    if(task&&((latestState.careActions||[]).some(item=>item.careTaskId===task.id)||latestTask?.status==="done")){setState(latestState);setSaveError("다른 담당자가 이 Care를 업데이트했습니다. 최신 상태를 확인해주세요.");return}
    setSaveError("");
    const now = new Date().toISOString();
    const staffDecision: StaffDecision = recordStatus === "scheduled" ? "monitor" : "needs_contact";
    const follow: FollowUp = {
      id: `follow_${Date.now()}`, episodeId: episode.id, patientId: patient.id, hospitalId: patient.hospitalId,
      triggeredFromCheckInId: latest?.id, action, actionType: actionTypes[action] || "other",
      outcomeCategory: recordStatus === "scheduled" ? "continue_monitoring" : "other", staffDecision, note,
      status: recordStatus, followUpDueDate: recordStatus === "scheduled" ? followUpDueDate : undefined,
      followUpNote: recordStatus === "scheduled" ? followUpNote : undefined, handledBy: handler.trim(),
      performedByRole: session.role, performedAt: now, source: "hospital_staff", createdAt: now, completedAt: now,
    };
    const decision = latest ? { id: `decision_${Date.now()}`, episodeId: episode.id, checkInId: latest.id, displayedPriority: status?.level || "stable", displayedReasons: status?.reasonCodes || [], staffDecision, ruleVersion: status?.ruleVersion || "demo-v1", createdAt: now, source: "hospital_staff" as const } : null;
    const careAction = { id: `action_${Date.now()}`, patientId: patient.id,hospitalId:patient.hospitalId, careTaskId: task?.id, actionType: actionTypes[action] || "other",status:recordStatus==="scheduled"?"follow_up" as const:"completed" as const, contactResult, patientStatus: patientCondition, result: careResult, assignedTo: activeAssignee || handler.trim(),staffId:session.staffId||session.userId,staffName:session.staffName||handler.trim(),staffRole:session.role, note,followUpAt:recordStatus==="scheduled"?followUpDueDate:undefined, createdAt: now,updatedAt:now, startedAt: now, completedAt: recordStatus === "completed" ? now : undefined };
    const next = { ...current, patients: current.patients.map(item => item.id === patient.id ? { ...item,assignedNurse:activeAssignee||item.assignedNurse,workflowStatus:recordStatus==="scheduled"?"follow_up" as const:"completed" as const } : item), followUps: [...current.followUps, follow], careActions: [...(current.careActions || []), careAction], careTasks: current.careTasks?.map(item => item.id === task?.id ? { ...item, assignedTo: activeAssignee || handler.trim(), assignedAt: item.assignedAt || now, firstReviewedAt: item.firstReviewedAt || now, status: recordStatus === "completed" ? "done" as const : "in_progress" as const } : item), careSignals: current.careSignals?.map(signal => signal.patientId === patient.id && signal.status === "open" ? { ...signal, status: "reviewed" as const } : signal), decisions: decision ? [...current.decisions, decision] : current.decisions };
    (demo ? savePublicDemoCareState : saveCareState)(next); setState(next); setSaved(true); setSavedActionId(careAction.id);trackCareEvent("care_action_completed",{patientId:patient.id,hospitalId:patient.hospitalId,careSignalId:task?.signalIds[0],careTaskId:task?.id,careActionId:careAction.id,durationSeconds:0,demo});if(recordStatus==="scheduled")trackCareEvent("followup_created",{patientId:patient.id,hospitalId:patient.hospitalId,careTaskId:task?.id,followUpDate:followUpDueDate,demo});setAction(""); setNote(""); setFollowUpDueDate(""); setFollowUpNote("");
  }

  function completeFollowUp(follow: FollowUp) {
    if(!patient)return;
    const resultNote = (resultNotes[follow.id] || "").trim();
    const resultHandler = (resultHandlers[follow.id] || handler).trim();
    if (!resultNote || !resultHandler) return;
    const latestState=demo?loadPublicDemoCareState():loadCareState(),latestFollow=latestState.followUps.find(item=>item.id===follow.id);if(latestFollow?.status==="completed"){setState(latestState);setSaveError("이미 완료된 Follow-up입니다. 최신 상태를 반영했습니다.");return}const now = new Date().toISOString();
    const outcome = { id: `outcome_${Date.now()}`, patientId: patient.id, careActionId: follow.id, outcomeType: resultNote, recordedAt: now };
    const next = { ...current, followUps: current.followUps.map(f => f.id === follow.id ? { ...f, status: "completed" as const, resultNote, followUpCompletedAt: now, followUpHandledBy: resultHandler, outcomeCategory: "other" as const, staffDecision: "needs_contact" as const } : f), careSignals: current.careSignals?.map(signal => signal.patientId === patient.id ? { ...signal, status: "resolved" as const } : signal), outcomes: [...(current.outcomes || []), outcome] };
    (demo ? savePublicDemoCareState : saveCareState)(next); setState(next); setResultNotes(v => ({ ...v, [follow.id]: "" })); setSaved(true);
  }

  function saveSignalFeedback(feedback: "useful"|"not_useful"|"unsure") {
    if(!patient)return;
    const signal=state?.careSignals?.find(item=>item.id===task?.signalIds[0]);if(!signal)return;const latestState=demo?loadPublicDemoCareState():loadCareState();if((latestState.signalFeedback||[]).some(item=>item.careSignalId===signal.id&&item.submittedBy===session.userId)){setFeedbackSaved(true);return}const submittedAt=new Date().toISOString(),entry={id:`feedback_${Date.now()}`,patientId:patient.id,careSignalId:signal.id,careTaskId:task?.id,careActionId:savedActionId||undefined,signalType:signal.type,ruleId:status?.ruleVersion,feedback,submittedBy:session.userId,submittedAt};const next={...latestState,signalFeedback:[...(latestState.signalFeedback||[]),entry]};(demo?savePublicDemoCareState:saveCareState)(next);setState(next);setFeedbackSaved(true);trackCareEvent("signal_feedback_submitted",{patientId:patient.id,hospitalId:patient.hospitalId,careSignalId:signal.id,careTaskId:task?.id,feedback,signalType:signal.type,ruleId:status?.ruleVersion,demo});
  }
  function completeCare(){const latestState=demo?loadPublicDemoCareState():loadCareState();if((latestState.careCompletions||[]).some(item=>item.patientId===patient.id)){setState(latestState);setSaveError("이미 관리 완료된 환자입니다.");return}const completedAt=new Date().toISOString(),patientChecks=latestState.checkIns.filter(item=>item.patientId===patient.id),days=Math.max(1,daysSince(patient.dischargeDate)+1),entry={id:`completion_${Date.now()}`,patientId:patient.id,completedAt,reason:completionReason,finalStatus:status?.reason||"Care 관리기간 종료",careActionCount:(latestState.careActions||[]).filter(item=>item.patientId===patient.id).length,followUpCount:latestState.followUps.filter(item=>item.patientId===patient.id).length,checkInParticipationRate:Math.min(100,Math.round(patientChecks.length/days*100))};const next={...latestState,patients:latestState.patients.map(item=>item.id===patient.id?{...item,careStatus:"completed" as const}:item),careTasks:latestState.careTasks?.map(item=>item.patientId===patient.id?{...item,status:"done" as const}:item),careSignals:latestState.careSignals?.map(item=>item.patientId===patient.id?{...item,status:"resolved" as const}:item),careCompletions:[...(latestState.careCompletions||[]),entry]};(demo?savePublicDemoCareState:saveCareState)(next);setState(next);trackCareEvent("care_completed",{patientId:patient.id,hospitalId:patient.hospitalId,reason:completionReason,demo});}
  function manageAction(actionId:string,mode:"edit"|"cancel"){if(!canManageActions){setSaveError("현재 역할에는 조치를 수정할 권한이 없습니다.");return;}const latestState=demo?loadPublicDemoCareState():loadCareState(),existing=latestState.careActions?.find(item=>item.id===actionId);if(!existing)return;const now=new Date().toISOString(),next={...latestState,careActions:latestState.careActions?.map(item=>item.id!==actionId?item:mode==="cancel"?{...item,status:"cancelled" as const,cancelledAt:now,updatedAt:now}:{...item,actionType:editActionType||item.actionType,note:editActionNote,updatedAt:now,status:"corrected" as const}),patients:latestState.patients.map(item=>item.id===patient.id&&mode==="cancel"?{...item,workflowStatus:"in_review" as const}:item)};(demo?savePublicDemoCareState:saveCareState)(next);setState(next);setEditingActionId("");setSaved(mode!=="cancel");setSaveError(mode==="cancel"?"조치 실행을 취소하고 이전 업무상태로 되돌렸습니다.":"")}

  return <main className="min-h-screen bg-[#F3F5F3] p-5 text-[#1E2923] lg:p-9"><div className="mx-auto max-w-[1180px]">
    <header className="sticky top-0 z-40 -mx-3 mb-4 rounded-2xl border bg-white/95 p-3 shadow-sm backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><nav className="flex flex-wrap gap-2"><Link href={listHref} className="flex min-h-11 items-center gap-2 rounded-xl border px-3 font-black"><List size={18}/>← 환자 목록</Link><Link href={dashboardHref} className="flex min-h-11 items-center gap-2 rounded-xl border px-3 font-black"><LayoutDashboard size={18}/>병원 대시보드</Link></nav><div className="text-right"><p className="font-black">{patient.name} · 수술 후 Day {daysSince(patient.surgeryDate||patient.dischargeDate)}</p><p className="text-xs font-bold text-slate-500">{demo?"DEMO · 가상 환자 데이터":`${session.hospitalName||state.hospitals.find(h=>h.id===session.hospitalId)?.name||"현재 병원"} · ${session.staffName||handler} ${session.role}`}</p></div></div></header>
    {saveError?<div role="alert" className="mb-4 rounded-2xl border border-amber-300 bg-amber-50 p-4 font-black text-amber-950">{saveError}</div>:null}
    {guided?<div className="mb-4 rounded-2xl border border-teal-200 bg-teal-50 p-4"><p className="font-black text-teal-800">의료진 체험 · 2~5/6</p><p className="mt-1 text-sm font-semibold text-teal-900/70">확인 이유와 Trend를 살펴본 뒤 Care Action을 기록하고 내일 Follow-up을 지정해보세요.</p></div>:null}
    {task?.status==="in_progress"&&task.assignedTo?<div className="mt-4 rounded-2xl border border-blue-200 bg-blue-50 p-4 font-black text-blue-900">{task.assignedTo}님이 확인 중입니다. 저장 전 최신 상태를 다시 확인합니다.</div>:null}
    <section className="mt-5 rounded-[24px] border bg-white p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-black text-[#596A62]">{demo ? "병원 데모 · 환자 기본정보" : "환자 기본정보"}</p><h1 className="mt-2 text-3xl font-black">{patient.name}</h1><p className="mt-2 font-bold text-slate-600">연령대 {Math.floor(patient.age / 10) * 10}대 · 담당 {activeAssignee || "미배정"}</p></div><span className="h-fit rounded-full bg-[#FFF0E9] px-4 py-2 font-black text-[#A74A2D]">{statusLabels[status?.level || "stable"]}</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><Info label="수술명/유형" value={patient.customProcedureName || patient.procedureDetail || patient.surgeryType} /><Info label="수술 부위" value={`${patient.laterality} ${patient.bodyPart}`} /><Info label="수술일" value={patient.surgeryDate || "-"} /><Info label="퇴원일" value={patient.dischargeDate} /><Info label="회복 경과" value={`수술 후 D+${daysSince(patient.surgeryDate || patient.dischargeDate)}`} /><Info label="주치의" value={patient.assignedDoctor || "미지정"} /><Info label="진료과" value={patient.department || "정형외과"} /><Info label="다음 외래" value={patient.nextAppointment ? formatDate(patient.nextAppointment) : "미정"} /></dl><div className="mt-5 flex flex-wrap items-center gap-2 rounded-2xl bg-[#F3F6F3] p-4 text-sm font-black text-[#315E50]"><span>수술 {patient.surgeryDate || "-"}</span><span aria-hidden="true">→</span><span>퇴원 {patient.dischargeDate}</span><span aria-hidden="true">→</span><span>오늘 D+{daysSince(patient.surgeryDate || patient.dischargeDate)}</span></div></section>
    <section className="mt-4 rounded-[26px] border border-[#315E50]/25 bg-[#E8F1EA] p-7"><p className="text-sm font-black text-[#315E50]">현재 상태</p>{latest ? <div className="mt-4 grid gap-4 lg:grid-cols-2"><Current label="최근 통증" value={`${painValue(latest)} / 10`} /><Current label="움직임" value={mobilityLabels[latest.mobilityScore ?? latest.mobility]} /><Current label="주요 불편 증상" value={latest.hasConcern ? latest.concernText : "없음"} /><Current label="전일 대비 변화" value={comparisonLabels[latest.dayComparison || "same"]} /></div> : <p className="mt-3 font-bold">최근 체크인 응답이 없습니다.</p>}</section>
    <section className="mt-4 rounded-[24px] border border-[#E7C7BA] bg-[#FFF8F4] p-6"><p className="text-sm font-black text-[#A74A2D]">오늘 확인 권장</p><p className="mt-3 font-bold leading-7 text-[#6E584F]">{state.careSignals?.find(signal => signal.patientId === patient.id && signal.status !== "resolved")?.reason || status?.reason || (previous && latest && painValue(latest) > painValue(previous) ? "통증 증가" : "현재 상태 확인")}</p>{checks.length >= 3 ? <p className="mt-2 font-bold text-[#6E584F]">최근 통증 {checks.slice(0,3).reverse().map(painValue).join(" → ")}</p> : null}<p className="mt-4 text-xs font-semibold text-[#6E584F]">환자 응답 변화를 기준으로 정리한 정보이며, 최종 판단은 의료진이 합니다.</p></section>
    <section className="mt-4 rounded-[24px] bg-[#243F36] p-6 text-white"><p className="text-sm font-black text-teal-200">지금 무엇을 해야 하나요?</p><h2 className="mt-2 text-2xl font-black">{status?.level==="no_response"?"체크인 다시 요청":status?.level==="stable"?"경과 관찰 유지":"전화로 상태 확인"}</h2><p className="mt-2 text-white/70">권장 조치는 업무 시작을 돕기 위한 안내이며 의료적 판단을 대신하지 않습니다.</p><a href="#hospital-action" onClick={()=>setAction(status?.level==="stable"?"경과관찰":"전화 확인")} className="mt-5 flex h-13 items-center justify-center rounded-xl bg-white px-5 font-black text-[#243F36]">{status?.level==="stable"?"경과 관찰 기록하기":"전화 확인 기록하기"}</a></section>
    <RecoveryTrend checks={checks} followUps={follows} audience="hospital" />
    <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_.9fr]">
      <section className="rounded-[24px] border bg-white p-6"><h2 className="text-xl font-black">최근 체크인</h2><div className="mt-4 space-y-3">{checks.slice(0, 7).map(c => <div key={c.id} className="rounded-xl bg-[#F3F5F3] p-4"><div className="flex flex-wrap items-center gap-2"><strong>{c.date}</strong>{c.source === "guardian" ? <span className="rounded-full bg-[#E8F1EA] px-2 py-1 text-xs font-black text-[#315E50]">보호자 대리 입력</span> : null}</div><p className="mt-1">통증 {painValue(c)} / 10 · {mobilityLabels[c.mobilityScore ?? c.mobility]}</p>{c.hasConcern ? <p className="font-bold">{c.concernText}</p> : null}</div>)}</div></section>
      <section id="hospital-action" className="rounded-[24px] border bg-white p-6"><h2 className="text-xl font-black">의료진 조치 기록</h2><p className="mt-1 text-sm font-semibold text-slate-500">실제 수행한 조치와 재확인 업무를 기록합니다. 전화·예약·처방을 실행하지 않습니다.</p>
        <label className="mt-4 block font-black">Care 담당자<select value={activeAssignee} onChange={e => setAssignedTo(e.target.value)} className="mt-2 h-12 w-full rounded-xl border-2 border-[#DCE4DF] bg-white px-3"><option value="">미배정</option><option>박간호사</option><option>김간호사</option><option>이코디네이터</option></select></label>
        <div className="mt-4 grid grid-cols-2 gap-2">{Object.keys(actionTypes).map(x => <Choice key={x} selected={action === x} onClick={() => {setAction(x);trackCareEvent("care_action_started",{patientId:patient.id,hospitalId:patient.hospitalId,careSignalId:task?.signalIds[0],careTaskId:task?.id,actionType:actionTypes[x],demo})}}>{x}</Choice>)}</div>
        {action ? <div className="mt-5 rounded-2xl bg-[#F5F7F5] p-4"><p className="font-black">연락 결과</p><div className="mt-2 grid grid-cols-3 gap-2">{[["connected","연결됨"],["guardian","보호자 연결"],["unreachable","연락 안 됨"]].map(([id,label]) => <Choice key={id} selected={contactResult === id} onClick={() => setContactResult(id as typeof contactResult)}>{label}</Choice>)}</div><p className="mt-4 font-black">확인한 상태</p><div className="mt-2 grid grid-cols-2 gap-2">{[["improved","호전"],["same","비슷"],["worse","악화"],["needs_review","추가 확인 필요"]].map(([id,label]) => <Choice key={id} selected={patientCondition === id} onClick={() => setPatientCondition(id as typeof patientCondition)}>{label}</Choice>)}</div><label className="mt-4 block font-black">조치<select value={careResult} onChange={e => setCareResult(e.target.value as typeof careResult)} className="mt-2 h-12 w-full rounded-xl border-2 border-[#DCE4DF] bg-white px-3"><option value="monitor">경과관찰</option><option value="daily_guidance">생활 안내</option><option value="medication_check">복약 안내 확인</option><option value="clinician_handoff">의료진 전달</option><option value="outpatient_guidance">외래 예약/안내</option><option value="urgent_guidance">응급 확인 안내</option></select></label></div> : null}
        <p className="mt-5 font-black">처리 상태</p><div className="mt-2 grid grid-cols-2 gap-2"><Choice selected={recordStatus === "completed"} onClick={() => setRecordStatus("completed")}>처리 완료</Choice><Choice selected={recordStatus === "scheduled"} warning onClick={() => setRecordStatus("scheduled")}>Follow-up 필요</Choice></div>
        <label className="mt-5 block font-black">간단 메모<textarea value={note} onChange={e => setNote(e.target.value)} placeholder="예: 통증 증가 관련 복약 여부 확인" className="mt-2 min-h-16 w-full rounded-xl border-2 border-[#DCE4DF] p-3 font-normal" /></label>
        <label className="mt-4 block font-black">담당자<input value={handler} onChange={e => setHandler(e.target.value)} className="mt-2 h-12 w-full rounded-xl border-2 border-[#DCE4DF] px-3" /></label>
        {recordStatus === "scheduled" ? <div className="mt-4 rounded-2xl bg-[#FFF8F4] p-4"><p className="font-black">다음 확인</p><div className="mt-2 grid grid-cols-3 gap-2"><Choice selected={followUpDueDate === shiftCareDate(TODAY,1)} onClick={() => setFollowUpDueDate(shiftCareDate(TODAY,1))}>내일</Choice><Choice selected={followUpDueDate === shiftCareDate(TODAY,2)} onClick={() => setFollowUpDueDate(shiftCareDate(TODAY,2))}>2일 후</Choice><Choice selected={Boolean(patient.nextAppointment) && followUpDueDate === patient.nextAppointment} onClick={() => patient.nextAppointment && setFollowUpDueDate(patient.nextAppointment)}>외래일까지</Choice></div><label className="mt-4 block font-black">날짜 직접 선택<input type="date" value={followUpDueDate} onChange={e => setFollowUpDueDate(e.target.value)} className="mt-2 h-12 w-full rounded-xl border-2 border-[#E7C7BA] bg-white px-3" /></label><label className="mt-4 block font-black">Follow-up 메모<textarea value={followUpNote} onChange={e => setFollowUpNote(e.target.value)} placeholder="재확인할 내용을 짧게 입력" className="mt-2 min-h-16 w-full rounded-xl border-2 border-[#E7C7BA] bg-white p-3 font-normal" /></label></div> : null}
        <p className="mt-4 text-sm font-bold text-slate-500">처리 시각은 저장 시점으로 자동 기록됩니다.</p><button disabled={!action || !handler.trim() || (recordStatus === "scheduled" && !followUpDueDate)} onClick={saveAction} className="mt-3 h-14 w-full rounded-xl bg-[#315E50] text-lg font-black text-white disabled:bg-[#BCC7C1]">조치 기록 저장</button>{saved ? <div className="mt-4 rounded-xl bg-[#E8F1EA] p-4"><p className="font-black text-[#315E50]"><Check className="mr-2 inline" />관리 기록에 반영했습니다.</p>{!feedbackSaved&&task?.signalIds[0]?<div className="mt-4 border-t border-[#C7DBCF] pt-4"><p className="font-black">이 환자를 확인하도록 알려준 것이 도움이 되었나요?</p><div className="mt-3 grid grid-cols-3 gap-2"><Choice selected={false} onClick={()=>saveSignalFeedback("useful")}>도움됨</Choice><Choice selected={false} onClick={()=>saveSignalFeedback("not_useful")}>불필요했음</Choice><Choice selected={false} onClick={()=>saveSignalFeedback("unsure")}>판단 어려움</Choice></div></div>:feedbackSaved?<p className="mt-3 font-bold text-[#315E50]">평가를 저장했습니다.</p>:null}{guided?<Link href="/demo/hospital/complete" className="mt-4 flex h-12 items-center justify-center rounded-xl bg-[#315E50] font-black text-white">외래 전 Summary 확인하고 체험 마치기</Link>:null}</div> : null}
        <div className="mt-6 border-t pt-5"><h3 className="font-black">관리 기록</h3><p className="mt-1 text-xs font-semibold text-slate-500">최근 기록이 먼저 표시됩니다.</p>{follows.length ? follows.map(f => <article key={f.id} className="mt-3 rounded-xl bg-slate-50 p-4 text-sm"><div className="flex flex-wrap items-center gap-2"><strong>{formatTime(f.performedAt || f.completedAt)} · {f.action}</strong><Status status={f.status} /></div>{f.note ? <p className="mt-2">{f.note}</p> : null}<p className="mt-1">담당: {f.handledBy}</p>{f.followUpDueDate ? <div className="mt-3 border-l-2 border-[#D28A65] pl-3"><strong className="text-[#A74A2D]">Follow-up 예정 · {formatDate(f.followUpDueDate)}</strong>{f.followUpNote ? <p>{f.followUpNote}</p> : null}</div> : null}{f.status === "scheduled" ? <div className="mt-4 rounded-xl border bg-white p-3"><label className="font-black">결과 메모<textarea value={resultNotes[f.id] || ""} onChange={e => setResultNotes(v => ({ ...v, [f.id]: e.target.value }))} placeholder="예: 통증 7 → 5로 감소 확인" className="mt-2 min-h-16 w-full rounded-lg border p-2 font-normal" /></label><label className="mt-3 block font-black">담당자<input value={resultHandlers[f.id] ?? handler} onChange={e => setResultHandlers(v => ({ ...v, [f.id]: e.target.value }))} className="mt-2 h-11 w-full rounded-lg border px-3" /></label><button onClick={() => completeFollowUp(f)} disabled={!(resultNotes[f.id] || "").trim() || !(resultHandlers[f.id] ?? handler).trim()} className="mt-3 h-11 w-full rounded-lg bg-[#315E50] font-black text-white disabled:bg-[#BCC7C1]">Follow-up 완료 기록</button></div> : null}{f.followUpCompletedAt ? <div className="mt-3 border-l-2 border-[#315E50] pl-3"><strong className="text-[#315E50]">{formatTime(f.followUpCompletedAt)} · Follow-up 완료</strong><p>{f.resultNote}</p><p>담당: {f.followUpHandledBy}</p></div> : null}</article>) : <p className="mt-3 text-sm font-bold text-slate-500">아직 관리 기록이 없습니다.</p>}</div>
      </section>
    </div>
    <section className="mt-5 rounded-[24px] border bg-white p-6"><h2 className="text-xl font-black">관리 기록 Timeline</h2><p className="mt-1 text-sm text-slate-500">누가 언제 무엇을 기록하고 수정했는지 확인합니다.</p>{actions.length?actions.map(item=><article key={item.id} className="mt-4 border-l-2 border-[#315E50] pl-4"><p className="text-xs font-bold text-slate-500">{formatTime(item.updatedAt||item.createdAt)}</p><div className="mt-1 flex flex-wrap items-center gap-2"><strong>{item.staffName||item.assignedTo||"병원 담당자"} · {actionLabel(item.actionType)}</strong><span className={`rounded-full px-2 py-1 text-xs font-black ${item.status==="cancelled"?"bg-slate-200 text-slate-600":"bg-[#E8F1EA] text-[#315E50]"}`}>{item.status==="cancelled"?"실행 취소":item.status==="corrected"?"수정됨":item.status==="follow_up"?"재확인 예정":"완료"}</span></div>{item.note?<p className="mt-2">{item.note}</p>:null}{item.followUpAt?<p className="mt-1 font-bold text-[#A74A2D]">다음 확인 {formatDate(item.followUpAt)}</p>:null}{item.status!=="cancelled"?<div className="mt-3 flex flex-wrap gap-2">{editingActionId===item.id?<><select value={editActionType} onChange={e=>setEditActionType(e.target.value)} className="h-10 rounded-lg border px-2">{Object.entries(actionTypes).map(([label,value])=><option key={value} value={value}>{label}</option>)}</select><input value={editActionNote} onChange={e=>setEditActionNote(e.target.value)} placeholder="수정 메모" className="h-10 min-w-0 flex-1 rounded-lg border px-3"/><button onClick={()=>manageAction(item.id,"edit")} className="rounded-lg bg-[#315E50] px-3 font-black text-white">수정 저장</button><button onClick={()=>setEditingActionId("")} className="rounded-lg border px-3 font-black">취소</button></>:<><button onClick={()=>{setEditingActionId(item.id);setEditActionType(item.actionType);setEditActionNote(item.note||"")}} className="rounded-lg border px-3 py-2 font-black">조치 수정</button><button onClick={()=>manageAction(item.id,"cancel")} className="rounded-lg border px-3 py-2 font-black text-[#A74A2D]">되돌리기</button></>}</div>:null}</article>):<p className="mt-4 rounded-xl bg-slate-50 p-4 font-bold text-slate-500">아직 기록된 조치가 없습니다.</p>}</section>
    <nav className="mt-5 grid grid-cols-2 gap-3"><span>{previousPatient?<Link href={patientHref(previousPatient.id)} className="flex h-14 items-center justify-center rounded-xl border-2 border-[#315E50] font-black text-[#315E50]">← 이전 환자 · {previousPatient.name}</Link>:null}</span><span>{nextPatient?<Link href={patientHref(nextPatient.id)} className="flex h-14 items-center justify-center rounded-xl bg-[#315E50] font-black text-white">다음 환자 · {nextPatient.name} →</Link>:null}</span></nav>
    <section className="mt-5 rounded-[24px] border bg-white p-6"><h2 className="text-xl font-black">Care 관리 종료</h2><p className="mt-2 text-sm font-semibold text-slate-500">제품 내 관리 프로그램을 종료하며 기존 회복 기록과 Action History는 유지됩니다.</p><select value={completionReason} onChange={e=>setCompletionReason(e.target.value as typeof completionReason)} className="mt-4 h-12 w-full rounded-xl border-2 border-[#DCE4DF] bg-white px-3"><option value="program_completed">예정된 관리기간 완료</option><option value="after_outpatient">외래 진료 후 종료</option><option value="transferred">다른 관리로 전환</option><option value="patient_request">환자 요청</option><option value="hospital_decision">병원 판단</option><option value="other">기타</option></select><button disabled={patient.careStatus==="completed"} onClick={()=>setConfirmCompletion(true)} className="mt-3 h-12 w-full rounded-xl border-2 border-[#315E50] font-black text-[#315E50] disabled:border-slate-300 disabled:text-slate-400">{patient.careStatus==="completed"?"관리 완료됨":"Care 관리 종료"}</button></section>
    {confirmCompletion?<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-5"><section className="w-full max-w-md rounded-3xl bg-white p-7"><h2 className="text-2xl font-black">이 환자의 회복관리를 완료 처리할까요?</h2><p className="mt-3 text-slate-600">기존 회복 기록과 관리 기록은 유지됩니다.</p><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setConfirmCompletion(false)} className="h-12 rounded-xl border font-black">취소</button><button onClick={()=>{completeCare();setConfirmCompletion(false)}} className="h-12 rounded-xl bg-[#315E50] font-black text-white">완료 처리</button></div></section></div>:null}
  </div></main>;
}

function eventTime(f: FollowUp) { return f.followUpCompletedAt || f.performedAt || f.completedAt; }
function formatTime(value: string) { return new Date(value).toLocaleString("ko-KR", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }); }
function formatDate(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString("ko-KR", { month: "numeric", day: "numeric" }); }
function actionLabel(value:string){return Object.entries(actionTypes).find(([,id])=>id===value)?.[0]||value}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="font-bold text-slate-500">{label}</dt><dd className="mt-1 font-bold">{value}</dd></div>; }
function Current({ label, value }: { label: string; value: string }) { return <article className="rounded-xl bg-white p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 font-black">{value}</p></article>; }
function Choice({ selected, warning, onClick, children }: { selected: boolean; warning?: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-pressed={selected} onClick={onClick} className={`min-h-12 rounded-xl border-2 px-2 font-black ${selected ? warning ? "border-[#A74A2D] bg-[#FFF0E9]" : "border-[#315E50] bg-[#E8F1EA]" : "border-[#DCE4DF]"}`}>{children}</button>; }
function Status({ status }: { status: FollowUp["status"] }) { return <span className={`rounded-full px-2 py-0.5 text-xs font-black ${status === "scheduled" ? "bg-[#FFF0E9] text-[#A74A2D]" : "bg-[#E8F1EA] text-[#315E50]"}`}>{status === "scheduled" ? "Follow-up 예정" : "처리 완료"}</span>; }
