import Link from "next/link";
import { ArrowRight, Check, Footprints, HelpCircle, Phone, Radar } from "lucide-react";
import { PRODUCT_COPY } from "@/lib/product-copy";

const problems = ["매일 전화하기는 어렵습니다.", "부모님은 걱정시키기 싫어합니다.", "작은 변화는 놓치기 쉽습니다."];
const flow = [["평소 생활", "부모님답게 지내세요.", Footprints], ["변화가 이어짐", "생활 흐름을 살펴봐요.", Radar], ["질문 하나", "필요한 날만 물어요.", HelpCircle], ["가족 행동", "할 일 하나를 알려드려요.", Phone]] as const;

export function LandingIA() {
  return <main className="senior-landing">
    <header className="senior-header"><div className="senior-header-inner"><Link href="/" className="senior-brand"><img src="/brand/brand-icon.png?v=6" alt="" width="52" height="52" /><span>오늘안부</span></Link><Link href="/about" className="senior-guide-link">서비스 소개</Link></div></header>
    <section className="senior-hero"><div className="senior-hero-copy"><p className="senior-kicker"><Radar aria-hidden /> 생활 변화 레이더</p><h1>매일 묻지 않아도,<br />평소와 다른 날을<br />알려드립니다.</h1><div className="readable-sentences senior-summary"><p>부모님은 매일 기록하지 않습니다.</p><p>필요한 날에만 질문 하나에 답합니다.</p></div><div className="senior-actions"><Link href="/app?role=family" className="senior-button senior-button-primary">가족 체험하기 <ArrowRight aria-hidden /></Link><Link href="/app?role=parent" className="senior-button senior-button-secondary">부모 체험하기</Link></div></div><div className="senior-hero-image"><img src="/illustrations/todayanbu-hero.png?v=6" alt="오늘안부를 사용하는 부모님과 가족" width="760" height="680" /></div></section>
    <section className="bg-white px-5 py-16 sm:py-24"><div className="mx-auto max-w-[1040px] text-center"><p className="senior-section-label">왜 필요할까요?</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">가족의 마음은 늘 가까이 있습니다.</h2><div className="mx-auto mt-10 grid max-w-[820px] gap-4 md:grid-cols-3">{problems.map(item=><article key={item} className="rounded-[24px] border-2 border-[#E1E7DE] bg-[#FAFCF9] p-6 text-xl font-black"><Check className="mx-auto mb-4 text-[#E9652B]" />{item}</article>)}</div></div></section>
    <section className="senior-how"><p className="senior-section-label">해결 방법</p><h2>생활 변화 레이더</h2><p className="mx-auto mt-5 max-w-[680px] text-xl font-bold leading-9 text-[#56675E]">평소와 다른 흐름이 이어질 때,<br />가족이 먼저 확인하도록 돕습니다.</p><div className="mx-auto mt-10 grid max-w-[1040px] gap-4 md:grid-cols-4">{flow.map(([title,text,Icon],index)=><article key={title} className="rounded-[24px] border-2 border-[#DCE6D9] bg-white p-6"><span className="mx-auto flex size-12 items-center justify-center rounded-full bg-[#2F6B46] text-white"><Icon size={24} /></span><p className="mt-5 text-sm font-black text-[#D95C24]">{index+1}</p><h3 className="mt-2 text-2xl font-black">{title}</h3><p className="mt-3 text-lg font-bold text-[#586960]">{text}</p></article>)}</div><Link href="/technology" className="mt-9 inline-flex min-h-14 items-center gap-2 rounded-2xl border-2 border-[#7E9F7A] bg-white px-6 text-lg font-black text-[#315B3D]">작동 방식 자세히 보기 <ArrowRight size={20} /></Link></section>
    <section className="bg-white px-5 py-16 sm:py-24"><div className="mx-auto max-w-[1040px]"><p className="senior-section-label text-center">실제 사용 화면</p><h2 className="mt-3 text-center text-3xl font-black sm:text-5xl">두 화면이면 충분합니다.</h2><div className="mt-10 grid gap-6 md:grid-cols-2"><ScreenPreview role="부모" title="필요한 날에만 질문 하나" question="오늘 식사는 어떠셨어요?" action="잘 먹었어요" /><ScreenPreview role="가족" title="평소와 다른 날만 확인" question="최근 움직임이 줄었어요." action="전화하기" /></div></div></section>
    <section className="bg-[#FFF5E8] px-5 py-16 sm:py-24"><div className="mx-auto max-w-[900px] text-center"><p className="senior-section-label">요금</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">먼저 무료로 체험하세요.</h2><p className="mt-5 text-xl font-bold leading-9 text-[#56675E]">현재 체험은 무료입니다.<br />실제 연결 요금은 출시 전에 안내합니다.</p><Link href="/plans" className="mt-8 inline-flex min-h-14 items-center gap-2 rounded-2xl bg-white px-6 text-lg font-black text-[#315B3D]">요금 원칙 보기 <ArrowRight size={20} /></Link></div></section>
    <section className="bg-[#173F35] px-5 py-16 text-center text-white sm:py-24"><h2 className="text-3xl font-black sm:text-5xl">먼저 연락할 날을<br />놓치지 마세요.</h2><Link href="/app?role=family" className="mt-8 inline-flex min-h-[68px] items-center gap-2 rounded-2xl bg-white px-8 text-xl font-black text-[#173F35]">가족 체험하기 <ArrowRight size={22} /></Link><p className="mt-5"><Link href="/app?role=parent" className="font-black text-white/80 underline underline-offset-4">부모 화면도 볼 수 있어요</Link></p></section>
    <section className="mx-auto w-[calc(100%-40px)] max-w-[900px] py-16 sm:py-24"><p className="senior-section-label">자주 묻는 질문</p><h2 className="mt-3 text-3xl font-black">궁금한 점만 확인하세요.</h2><div className="mt-8 space-y-3"><Faq question="부모님이 매일 입력해야 하나요?" answer={PRODUCT_COPY.parentBehavior} /><Faq question="한 번 답하지 않으면 가족에게 알리나요?" answer="아닙니다. 한 번의 응답보다 이어지는 생활 흐름을 함께 봅니다." /><Faq question="통화나 문자 내용을 보나요?" answer="아닙니다. 통화 내용, 문자 내용, 사진 내용은 확인하지 않습니다." /></div><p className="mt-8 text-center"><Link href="/guide" className="font-black text-[#315B3D] underline underline-offset-4">이용 방법 자세히 보기</Link></p></section>
    <footer className="senior-footer">오늘안부 · 평소와 다른 날을 알려드립니다.</footer>
  </main>;
}

function ScreenPreview({role,title,question,action}:{role:string;title:string;question:string;action:string}) { return <article className="rounded-[30px] bg-[#F2F7EF] p-6 sm:p-8"><p className="font-black text-[#D95C24]">{role} 화면</p><h3 className="mt-2 text-2xl font-black">{title}</h3><div className="mt-6 rounded-[26px] bg-white p-6 shadow-[0_14px_30px_rgba(49,78,58,.08)]"><p className="text-xl font-black">{question}</p><div className="mt-5 flex min-h-14 items-center justify-center rounded-2xl bg-[#2F6B46] px-5 text-lg font-black text-white">{action}</div></div></article> }
function Faq({question,answer}:{question:string;answer:string}) { return <details className="rounded-[20px] border border-[#DFE6DC] bg-white p-5"><summary className="cursor-pointer text-lg font-black">{question}</summary><p className="mt-4 font-bold leading-8 text-[#586960]">{answer}</p></details> }
