"use client";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3, FlaskConical, HeartHandshake, ShieldCheck } from "lucide-react";
import { CASES, DRAFT_KEY, emptyResponse, LEAD_KEY, readList, RESPONSE_KEY, ResearchLead, ResearchResponse, saveList } from "@/lib/orthopedics-research";

const TOTAL=10;
const opts={
 role:["정형외과 전문의","정형외과 전공의","간호사","진료/수술 코디네이터","원무/CS","병원 경영/관리","기타"],
 org:["의원","병원","종합병원","상급종합병원","기타"], exp:["1년 미만","1~3년","4~7년","8~15년","16년 이상"],
 workflow:["예정된 외래에서 확인","병원에서 전화","환자가 병원으로 전화","문자/메신저","별도 프로그램","별도로 확인하지 않음","기타"],
 period:["퇴원 후 1~3일","4~7일","8~14일","15~30일","수술 유형마다 다름","특별히 없음","기타"],
 pain:["모든 환자에게 연락하기 어렵다","누가 먼저 확인이 필요한지 알기 어렵다","환자가 먼저 연락하기 전에는 상태를 알기 어렵다","전화 연결이 잘 되지 않는다","기록 업무가 추가된다","담당자가 명확하지 않다","EMR과 별도 업무가 생긴다","특별한 어려움이 없다","기타"],
 signals:["통증 정도","통증 변화","움직임/보행","부종","발열","수술부위 상태","감각 이상","낙상","약 복용","체크인 미응답","퇴원 후 경과일","수술 유형","기타"],
 adoption:["퇴원환자 상태 확인","확인이 필요한 환자 선별","전화업무 효율화","환자 만족도","재방문 관리","병원 서비스 차별화","의료진 간 업무 공유","도입 이유가 크지 않음","기타"]
};

function Single({values,value,onChange}:{values:string[];value?:string;onChange:(v:string)=>void}){return <div className="grid gap-3 sm:grid-cols-2">{values.map(v=><button type="button" key={v} onClick={()=>onChange(v)} className={`min-h-14 rounded-2xl border-2 px-4 py-3 text-left font-bold transition ${value===v?"border-[#315E50] bg-[#E8F1EA] text-[#24483D]":"border-slate-200 bg-white hover:border-[#9CB7A8]"}`}><span className="flex items-center gap-3"><span className={`grid size-6 shrink-0 place-items-center rounded-full border ${value===v?"border-[#315E50] bg-[#315E50] text-white":"border-slate-300"}`}>{value===v?<Check size={15}/>:null}</span>{v}</span></button>)}</div>}
function Multi({values,value,onChange,max}:{values:string[];value:string[];onChange:(v:string[])=>void;max?:number}){return <div className="grid gap-3 sm:grid-cols-2">{values.map(v=>{const on=value.includes(v);return <button type="button" key={v} onClick={()=>{if(on)onChange(value.filter(x=>x!==v));else if(!max||value.length<max)onChange([...value,v])}} className={`min-h-14 rounded-2xl border-2 px-4 py-3 text-left font-bold ${on?"border-[#315E50] bg-[#E8F1EA]":"border-slate-200 bg-white"}`}><span className="flex gap-3"><span className={`mt-0.5 grid size-6 shrink-0 place-items-center rounded-md border ${on?"border-[#315E50] bg-[#315E50] text-white":"border-slate-300"}`}>{on?<Check size={15}/>:null}</span>{v}</span></button>})}</div>}
function Likert({value,onChange}:{value?:number;onChange:(v:number)=>void}){return <div className="grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>onChange(n)} className={`min-h-14 rounded-xl border-2 text-lg font-black ${value===n?"border-[#315E50] bg-[#315E50] text-white":"border-slate-200 bg-white"}`}>{n}</button>)}</div>}
const Label=({children}:{children:React.ReactNode})=><h2 className="mb-4 text-xl font-black leading-8 text-slate-900">{children}</h2>;
const Text=({value,onChange,placeholder,required=false}:{value?:string;onChange:(v:string)=>void;placeholder?:string;required?:boolean})=><textarea required={required} value={value||""} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="min-h-28 w-full rounded-2xl border-2 border-slate-200 bg-white p-4 leading-7 outline-none focus:border-[#315E50]"/>;

export function OrthopedicsResearch(){
 const [phase,setPhase]=useState<"landing"|"survey"|"done">("landing"),[step,setStep]=useState(1),[data,setData]=useState<ResearchResponse|null>(null),[lead,setLead]=useState({hospitalName:"",name:"",email:"",phone:"",consent:false}),[caseOrder,setCaseOrder]=useState<string[]>([]);
 useEffect(()=>{try{const saved=localStorage.getItem(DRAFT_KEY);if(saved){const x=JSON.parse(saved);setData(x.data);setStep(x.step||1);setCaseOrder(x.caseOrder||[]);setPhase("survey")}}catch{}},[]);
 useEffect(()=>{if(data&&phase==="survey")localStorage.setItem(DRAFT_KEY,JSON.stringify({data,step,caseOrder}))},[data,step,caseOrder,phase]);
 const patch=(p:Partial<ResearchResponse>)=>setData(d=>d?{...d,...p}:d);
 const start=()=>{const d=emptyResponse();const order=[...CASES.map(c=>c.id)].sort(()=>Math.random()-.5);setData(d);setCaseOrder(order);setStep(1);setPhase("survey")};
 const finish=()=>{if(!data)return;const complete={...data,completedAt:new Date().toISOString()};saveList(RESPONSE_KEY,[...readList<ResearchResponse>(RESPONSE_KEY),complete]);if((data.pilotInterest==="관심 있음"||data.pilotInterest==="조금 더 알아보고 싶음")&&lead.consent&&(lead.email||lead.phone)){const l:ResearchLead={id:crypto.randomUUID(),researchResponseId:data.id,hospitalName:lead.hospitalName,name:lead.name,email:lead.email,phone:lead.phone,consent:true,createdAt:new Date().toISOString()};saveList(LEAD_KEY,[...readList<ResearchLead>(LEAD_KEY),l])}localStorage.removeItem(DRAFT_KEY);setPhase("done")};
 const canNext=useMemo(()=>{if(!data)return false;return [!!data.role&&!!data.organizationType&&!!data.experience,data.currentWorkflow.length>0&&!!data.contactFrequency&&!!data.criticalPeriod,data.workflowPainPoints.length>0,!!data.patientUxScore&&!!data.checkinUsefulnessScore, data.caseResponses.length===4&&data.caseResponses.every(x=>x.reason.trim())&&data.importantSignals.length>0,!!data.dashboardFirstFocus&&!!data.dashboardPriorityScore&&!!data.dashboardReasonScore&&!!data.painDecisionPriority&&!!data.painScaleAppropriateness&&!!data.importantConcerns?.length&&!!data.trendUsefulnessScore,!!data.followupAdequacy&&!!data.handlerVisibility&&!!data.doctorEscalation,!!data.expectedOperator&&!!data.manageableAlerts&&!!data.acceptableHandlingTime,data.adoptionReasons.length>0&&!!data.nonAdoptionReason?.trim(),!!data.pilotInterest][step-1]},[data,step]);
 if(phase==="landing")return <main className="min-h-screen bg-[#FFF9F0] px-5 py-10 text-slate-900"><div className="mx-auto max-w-5xl"><header className="flex items-center gap-3 font-black text-[#315E50]"><HeartHandshake/>오늘안부 Care</header><section className="mt-14 grid items-center gap-12 lg:grid-cols-[1fr_360px]"><div><p className="font-black text-[#E9652B]">정형외과 의료진 제품 검증</p><h1 className="mt-5 text-4xl font-black leading-tight sm:text-6xl">퇴원환자 관리,<br/>실제 병원에서는<br/>어떻게 하고 계신가요?</h1><p className="mt-6 max-w-2xl text-lg font-semibold leading-8 text-slate-600">정형외과 의료진의 실제 업무 경험을 바탕으로 오늘안부의 퇴원 후 관리 방식을 검증하고 있습니다.</p><div className="mt-8 flex flex-wrap gap-3">{[[Clock3,"약 15~20분"],[FlaskConical,"제품 검증 목적"],[ShieldCheck,"환자 개인정보 입력 불필요"]].map(([I,t])=>{const Icon=I as typeof Clock3;return <span key={t as string} className="flex items-center gap-2 rounded-full bg-white px-4 py-3 font-bold shadow-sm"><Icon size={18}/>{t as string}</span>})}</div><button onClick={start} className="mt-9 min-h-16 rounded-2xl bg-[#315E50] px-8 text-xl font-black text-white">검증 시작하기 <ArrowRight className="ml-2 inline"/></button></div><div className="rounded-[36px] bg-[#E8F1EA] p-7"><Image src="/assets/characters/care-default.png" alt="오늘안부 Care Companion" width={420} height={420} className="mx-auto"/></div></section></div></main>;
 if(phase==="done")return <main className="grid min-h-screen place-items-center bg-[#FFF9F0] p-5 text-center"><section className="max-w-lg"><Image src="/assets/characters/care-complete.png" alt="감사 인사를 전하는 Care Companion" width={240} height={240} className="mx-auto"/><h1 className="mt-6 text-4xl font-black">의견을 들려주셔서 감사합니다.</h1><p className="mt-5 text-lg font-semibold leading-8 text-slate-600">보내주신 의견은 오늘안부의 정형외과 퇴원 후 관리 방식을 개선하는 데 참고하겠습니다.</p></section></main>;
 if(!data)return null;
 const caseById=(id:string)=>CASES.find(c=>c.id===id)!;
 return <main className="min-h-screen bg-[#F4F7F5] text-slate-900"><header className="sticky top-0 z-10 border-b bg-white/95 px-5 py-4 backdrop-blur"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between"><b className="text-[#315E50]">오늘안부 Care</b><span className="font-black">{step} / {TOTAL}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#315E50] transition-all" style={{width:`${step/TOTAL*100}%`}}/></div></div></header><form onSubmit={e=>{e.preventDefault();if(step<TOTAL)setStep(s=>s+1);else finish()}} className="mx-auto max-w-3xl px-5 py-8"><section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-8">
 {step===1&&<div className="space-y-8"><div><Label>현재 역할을 알려주세요.</Label><Single values={opts.role} value={data.role} onChange={v=>patch({role:v})}/></div><div><Label>근무기관 유형</Label><Single values={opts.org} value={data.organizationType} onChange={v=>patch({organizationType:v})}/></div><div><Label>정형외과 관련 업무 경험</Label><Single values={opts.exp} value={data.experience} onChange={v=>patch({experience:v})}/></div></div>}
 {step===2&&<div className="space-y-8"><div><Label>현재 수술 후 퇴원환자의 상태를 어떻게 확인하고 있나요?</Label><Multi values={opts.workflow} value={data.currentWorkflow} onChange={v=>patch({currentWorkflow:v})}/></div><div><Label>병원에서 먼저 퇴원환자에게 연락하는 경우가 있나요?</Label><Single values={["자주 있다","가끔 있다","거의 없다","전혀 없다"]} value={data.contactFrequency} onChange={v=>patch({contactFrequency:v})}/></div><div><Label>먼저 연락한다면 어떤 환자인가요?</Label><Text value={data.contactCriteria} onChange={v=>patch({contactCriteria:v})} placeholder="예: 통증이 심한 환자, 수술부위 이상을 호소한 환자 등"/></div><div><Label>퇴원 후 특히 확인이 필요하다고 느끼는 시기가 있나요?</Label><Single values={opts.period} value={data.criticalPeriod} onChange={v=>patch({criticalPeriod:v})}/></div></div>}
 {step===3&&<div><Label>퇴원환자 관리에서 가장 어려운 점은 무엇인가요? <span className="text-sm text-slate-500">최대 3개</span></Label><Multi max={3} values={opts.pain} value={data.workflowPainPoints} onChange={v=>patch({workflowPainPoints:v})}/></div>}
 {step===4&&<div className="space-y-8"><div className="rounded-3xl bg-[#E8F1EA] p-5"><p className="text-sm font-black text-[#315E50]">RESEARCH 전용 환자 화면</p><h2 className="mt-2 text-2xl font-black">오늘 몸은 어떠세요?</h2><p className="mt-2 text-slate-600">1분이면 오늘 확인이 끝나요.</p><div className="mt-5 grid gap-2 sm:grid-cols-3">{["통증","움직임","추가 불편"].map((x,i)=><div key={x} className="rounded-2xl bg-white p-4 font-bold"><span className="text-[#E9652B]">{i+1}</span> {x} 확인</div>)}</div><p className="mt-4 text-xs font-bold text-slate-500">가상 화면이며 병원 Dashboard 데이터에 저장되지 않습니다.</p></div><div><Label>60~70대 퇴원환자가 혼자 사용할 수 있다고 생각하시나요?</Label><Likert value={data.patientUxScore} onChange={v=>patch({patientUxScore:v})}/><div className="mt-2 flex justify-between text-sm font-bold text-slate-500"><span>매우 어렵다</span><span>매우 쉽다</span></div></div><div><Label>현재 질문이 퇴원 후 상태 확인에 도움이 된다고 생각하시나요?</Label><Likert value={data.checkinUsefulnessScore} onChange={v=>patch({checkinUsefulnessScore:v})}/></div><div><Label>불필요하다고 생각되는 질문이 있나요?</Label><Multi values={["통증","움직임","추가 불편","없음","기타"]} value={data.unnecessaryQuestions} onChange={v=>patch({unnecessaryQuestions:v})}/></div><div><Label>반드시 추가되어야 한다고 생각하는 항목이 있나요?</Label><Text value={data.missingQuestions} onChange={v=>patch({missingQuestions:v})}/></div></div>}
 {step===5&&<div className="space-y-8"><div><p className="font-black text-[#E9652B]">가상환자 판단</p><h2 className="mt-2 text-2xl font-black">각 환자에게 병원에서 먼저 연락하시겠습니까?</h2><p className="mt-2 text-slate-500">실제 환자가 아닌 제품 검증용 가상 사례입니다.</p></div>{caseOrder.map((id,index)=>{const c=caseById(id),r=data.caseResponses.find(x=>x.caseId===id);return <article key={id} className="rounded-3xl border-2 border-slate-200 p-5"><p className="text-sm font-black text-[#315E50]">CASE {index+1}</p><h3 className="mt-1 text-xl font-black">{c.title} · {c.meta}</h3><ul className="mt-3 space-y-1 text-slate-600">{c.facts.map(f=><li key={f}>{f}</li>)}</ul><div className="mt-5"><Single values={["연락한다","연락하지 않는다","판단하기 어렵다"]} value={r?.decision==="contact"?"연락한다":r?.decision==="no_contact"?"연락하지 않는다":r?.decision==="unsure"?"판단하기 어렵다":undefined} onChange={v=>{const decision=v==="연락한다"?"contact":v==="연락하지 않는다"?"no_contact":"unsure";patch({caseResponses:[...data.caseResponses.filter(x=>x.caseId!==id),{caseId:id,displayOrder:index+1,decision,reason:r?.reason||""}]})}}/></div><div className="mt-4"><Text value={r?.reason} onChange={reason=>patch({caseResponses:[...data.caseResponses.filter(x=>x.caseId!==id),{caseId:id,displayOrder:index+1,decision:r?.decision||"unsure",reason}]})} placeholder="그렇게 판단한 가장 중요한 이유"/></div></article>})}<div><Label>먼저 확인해야 할 환자를 판단할 때 중요한 정보는 무엇인가요? <span className="text-sm text-slate-500">최대 3개</span></Label><Multi max={3} values={opts.signals} value={data.importantSignals} onChange={v=>patch({importantSignals:v})}/></div></div>}
 {step===6&&<div className="space-y-8"><div className="rounded-3xl bg-slate-950 p-5 text-white"><p className="text-sm font-black text-emerald-300">RESEARCH 전용 병원 화면</p><h2 className="mt-2 text-2xl font-black">아침 업무를 시작했다고 생각하고 확인해주세요.</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["오늘 확인 필요","6명"],["미응답","4명"],["관리 환자","50명"]].map(x=><div key={x[0]} className="rounded-2xl bg-white/10 p-4"><p className="text-sm text-slate-300">{x[0]}</p><b className="mt-2 block text-2xl">{x[1]}</b></div>)}</div><div className="mt-4 rounded-2xl bg-white p-4 text-slate-900"><b>환자 B · 오늘 확인 필요</b><p className="mt-1 text-sm text-rose-700">통증 5 → 7 · 움직임 어려움 · 붓기</p></div></div><div><Label>화면을 처음 보고 가장 먼저 확인한 것은 무엇인가요?</Label><Single values={["오늘 확인 필요 환자","전체 관리 환자 수","미응답 환자","환자 이름","수술 유형","검색/필터","기타"]} value={data.dashboardFirstFocus} onChange={v=>patch({dashboardFirstFocus:v})}/></div><div><Label>누구에게 먼저 연락해야 하는지 바로 이해할 수 있었나요?</Label><Likert value={data.dashboardPriorityScore} onChange={v=>patch({dashboardPriorityScore:v})}/></div><div><Label>‘오늘 확인 필요’ 이유가 충분히 이해되었나요?</Label><Likert value={data.dashboardReasonScore} onChange={v=>patch({dashboardReasonScore:v})}/></div><div><Label>연락 여부 판단에 통증 정보 중 무엇이 가장 중요한가요?</Label><Single values={["통증 절대값","전일 대비 변화","최근 며칠간 추세"]} value={data.painDecisionPriority} onChange={v=>patch({painDecisionPriority:v})}/></div><div><Label>통증 0~10 척도가 실제 병원에서 이해하고 활용하기 적절한가요?</Label><Likert value={data.painScaleAppropriateness} onChange={v=>patch({painScaleAppropriateness:v})}/></div><div><Label>퇴원 후 확인에 중요한 불편 항목은 무엇인가요? <span className="text-sm text-slate-500">최대 3개</span></Label><Multi max={3} values={["붓기","발열/열감","수술부위","감각 이상","보행","낙상","약 복용","기타"]} value={data.importantConcerns||[]} onChange={v=>patch({importantConcerns:v})}/></div><div><Label>통증과 움직임의 시간별 그래프가 환자 확인에 도움이 되나요?</Label><Likert value={data.trendUsefulnessScore} onChange={v=>patch({trendUsefulnessScore:v})}/></div><div><Label>연락 여부 판단에 추가로 필요한 정보가 있나요?</Label><Text value={data.dashboardMissingInfo} onChange={v=>patch({dashboardMissingInfo:v})}/></div></div>}
 {step===7&&<div className="space-y-8"><div><Label>실제 업무에서 이 정도 후속조치 기록이면 충분합니까?</Label><div className="mb-4 flex flex-wrap gap-2">{["전화 확인","추가 관찰","내원 안내","특이사항 없음","기타"].map(x=><span key={x} className="rounded-full bg-[#E8F1EA] px-3 py-2 text-sm font-bold text-[#315E50]">{x}</span>)}</div><Single values={["충분하다","일부 수정이 필요하다","많이 부족하다"]} value={data.followupAdequacy} onChange={v=>patch({followupAdequacy:v})}/></div>{data.followupAdequacy!=="충분하다"&&<div><Label>어떤 기록이 추가되어야 하나요?</Label><Text value={data.followupMissing} onChange={v=>patch({followupMissing:v})}/></div>}<div><Label>누가 연락했는지 다른 직원이 확인할 필요가 있나요?</Label><Single values={["반드시 필요","있으면 좋음","필요 없음"]} value={data.handlerVisibility} onChange={v=>patch({handlerVisibility:v})}/></div><div><Label>의사에게 별도로 전달해야 하는 경우를 구분할 필요가 있나요?</Label><Single values={["반드시 필요","있으면 좋음","필요 없음"]} value={data.doctorEscalation} onChange={v=>patch({doctorEscalation:v})}/></div></div>}
 {step===8&&<div className="space-y-8"><div><Label>누가 매일 확인하는 것이 가장 현실적이라고 생각하시나요?</Label><Single values={["의사","외래 간호사","병동 간호사","코디네이터","원무/CS","별도 환자관리 담당자","기타"]} value={data.expectedOperator} onChange={v=>patch({expectedOperator:v})}/></div><div><Label>관리 환자 50명 중 하루 몇 명까지 ‘오늘 확인 필요’로 처리 가능할까요?</Label><Single values={["1~5명","6~10명","11~15명","16~20명","20명 이상","판단하기 어려움"]} value={data.manageableAlerts} onChange={v=>patch({manageableAlerts:v})}/></div><div><Label>한 명을 검토하고 조치를 기록하는 데 허용 가능한 시간은?</Label><Single values={["1분 이내","1~3분","3~5분","5~10분","10분 이상"]} value={data.acceptableHandlingTime} onChange={v=>patch({acceptableHandlingTime:v})}/></div></div>}
 {step===9&&<div className="space-y-8"><div><Label>오늘안부를 도입할 가장 큰 이유는 무엇인가요? <span className="text-sm text-slate-500">최대 2개</span></Label><Multi max={2} values={opts.adoption} value={data.adoptionReasons} onChange={v=>patch({adoptionReasons:v})}/></div><div><Label>반대로 병원에서 사용하지 않게 된다면 가장 큰 이유는 무엇일까요?</Label><Text required value={data.nonAdoptionReason} onChange={v=>patch({nonAdoptionReason:v})}/></div></div>}
 {step===10&&<div className="space-y-8"><div><Label>오늘안부의 실제 병원 적용 테스트에 관심이 있으신가요?</Label><Single values={["관심 있음","조금 더 알아보고 싶음","현재는 관심 없음"]} value={data.pilotInterest} onChange={v=>patch({pilotInterest:v})}/></div>{data.pilotInterest!=="현재는 관심 없음"&&data.pilotInterest&&<div className="rounded-3xl bg-[#F4F7F5] p-5"><h2 className="text-xl font-black">연락처 남기기 <span className="text-sm text-slate-500">선택</span></h2><p className="mt-2 text-sm text-slate-600">Research 답변과 분리해 저장합니다.</p><div className="mt-5 grid gap-3">{[["hospitalName","병원명"],["name","성명"],["email","이메일"],["phone","휴대전화"]].map(([k,p])=><input key={k} value={lead[k as keyof typeof lead] as string} onChange={e=>setLead(l=>({...l,[k]:e.target.value}))} placeholder={p} className="min-h-14 rounded-xl border-2 border-slate-200 px-4"/>)}</div><label className="mt-4 flex gap-3 rounded-xl bg-white p-4 font-bold"><input type="checkbox" checked={lead.consent} onChange={e=>setLead(l=>({...l,consent:e.target.checked}))} className="size-5"/>오늘안부 제품 검증 및 Pilot 관련 연락을 받는 것에 동의합니다.</label><p className="mt-3 text-xs text-slate-500">동의하지 않거나 이메일·휴대전화가 없으면 연락처는 저장되지 않습니다.</p></div>}</div>}
 </section><div className="mt-5 flex gap-3">{step>1&&<button type="button" onClick={()=>setStep(s=>s-1)} className="min-h-14 flex-1 rounded-2xl border-2 border-[#315E50] font-black text-[#315E50]"><ArrowLeft className="mr-2 inline"/>이전</button>}<button type="submit" disabled={!canNext} className="min-h-14 flex-[1.5] rounded-2xl bg-[#315E50] px-5 font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">{step===TOTAL?"의견 제출하기":"다음"}<ArrowRight className="ml-2 inline"/></button></div><p className="mt-4 text-center text-xs font-bold text-slate-500">각 단계가 이 브라우저에 임시 저장됩니다.</p></form></main>
}
