import Link from "next/link";
import { ArrowRight, Check, EyeOff, Footprints, HelpCircle, HeartHandshake, LockKeyhole, Phone, SkipForward, UsersRound } from "lucide-react";

const parentSteps = [["평소처럼 생활합니다.",Footprints],["질문이 오면 하나만 누릅니다.",HelpCircle],["어려운 날은 건너뛰어도 됩니다.",SkipForward]] as const;
const simpleFlow = ["평소 생활","다른 흐름","질문 하나","가족 연락"];
const whoNeedsIt = ["부모님이 혼자 생활하시는 분","자주 전화하지 못해 늘 마음이 쓰이는 분","부모님이 ‘괜찮다’만 말씀하시는 분","작은 생활 변화를 놓치고 싶지 않은 분"];

export function ParentFirstLanding(){return <main className="senior-landing">
  <header className="senior-header"><div className="senior-header-inner"><Link href="/" className="senior-brand"><img src="/brand/brand-icon.png?v=6" alt="" width="52" height="52"/><span>오늘안부</span></Link><Link href="/start" className="senior-guide-link">가족으로 보기</Link></div></header>
  <section className="senior-hero"><div className="senior-hero-copy"><p className="senior-kicker"><HeartHandshake aria-hidden/> 부모님과 가족을 위한 오늘안부</p><h1>부모님은 매일<br/>기록하지 않아도 됩니다.</h1><div className="readable-sentences senior-summary"><p>필요한 날에만 질문 하나에 답합니다.</p><p>가족은 필요한 날만 확인합니다.</p></div><p className="mt-6 text-xl font-black leading-9 text-[#2F6B46]">매일 전화하지 못해도 괜찮습니다.<br/>필요한 날만 먼저 알려드립니다.</p><div className="senior-actions"><Link href="/parents" className="senior-button senior-button-primary">부모 사용법 보기 <ArrowRight aria-hidden/></Link></div><p className="mt-5"><Link href="/app?role=family" className="text-lg font-black text-[#52635C] underline underline-offset-4">가족 화면 체험하기</Link></p><div className="mt-7 grid gap-3 text-left text-lg font-black text-[#40534B]"><p className="flex items-start gap-3"><Check className="mt-1 shrink-0 text-[#2F6B46]"/>부모님은 필요한 날에만 답합니다.</p><p className="flex items-start gap-3"><UsersRound className="mt-1 shrink-0 text-[#2F6B46]"/>가족은 필요한 날만 확인합니다.</p><p className="flex items-start gap-3"><LockKeyhole className="mt-1 shrink-0 text-[#2F6B46]"/>개인정보는 부모님 동의 후에만 연결됩니다.</p></div></div><div className="senior-hero-image ansimi-hero-once"><img src="/brand/hero-ansimi-phone-v1.png" alt="차를 마시며 휴대폰의 질문 하나와 가족 사진을 확인하는 오늘안부 캐릭터 안심이" width="1536" height="1024" fetchPriority="high"/></div></section>
  <section className="bg-white px-5 py-16 sm:py-24"><div className="mx-auto max-w-[1040px]"><p className="senior-section-label text-center">이런 분들에게 필요합니다</p><div className="mx-auto mt-9 grid max-w-[900px] gap-4 md:grid-cols-2">{whoNeedsIt.map(item=><p key={item} className="flex items-center gap-4 rounded-[22px] bg-[#F2F7EF] p-5 text-lg font-black"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-[#2F6B46] text-white"><Check size={22}/></span>{item}</p>)}</div></div></section>
  <section className="bg-white px-5 py-16 sm:py-24"><div className="mx-auto max-w-[1040px] text-center"><p className="senior-section-label">부모님이 하실 일</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">이것뿐입니다.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{parentSteps.map(([text,Icon],index)=><article key={text} className="rounded-[26px] border-2 border-[#DFE7DC] bg-[#FAFCF9] p-7"><span className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#EAF3E5] text-[#2F6B46]"><Icon size={32}/></span><p className="mt-5 text-sm font-black text-[#E9652B]">{index+1}</p><h3 className="mt-2 text-2xl font-black">{text}</h3></article>)}</div></div></section>
  <section className="bg-[#FFF5E8] px-5 py-16 sm:py-24"><div className="mx-auto grid max-w-[1040px] gap-8 md:grid-cols-2 md:items-center"><div className="overflow-hidden rounded-[30px] bg-[#F5E8D3]"><img src="/brand/hero-ansimi-phone-v1.png" alt="평소처럼 쉬다가 필요한 질문 하나만 확인하는 안심이" className="aspect-[4/3] w-full object-cover object-center"/></div><div><p className="senior-section-label">가족이 안심할 수 있도록</p><h2 className="mt-3 text-3xl font-black leading-tight sm:text-5xl">매일 연락하지 않아도<br/>괜찮습니다.</h2><div className="readable-sentences mt-5 text-xl font-bold leading-9 text-[#56675E]"><p>부모님은 평소처럼 지냅니다.</p><p>필요한 날에만 가족이 먼저 연락합니다.</p></div></div></div></section>
  <section className="bg-[#EAF3E5] px-5 py-16 sm:py-24"><div className="mx-auto max-w-[900px] text-center"><EyeOff className="mx-auto text-[#2F6B46]" size={48}/><h2 className="mt-5 text-3xl font-black sm:text-5xl">부모님을 감시하는<br/>서비스가 아닙니다.</h2><div className="readable-sentences mt-6 text-xl font-bold leading-9 text-[#52635C]"><p>위치나 대화 내용을 들여다보지 않습니다.</p><p>동의한 정보만 사용할 수 있습니다.</p><p>언제든 연결을 끊을 수 있습니다.</p></div><Link href="/permissions" className="mt-8 inline-flex min-h-16 items-center gap-2 rounded-2xl bg-white px-7 text-xl font-black text-[#315B3D]">내 정보 확인하기 <ArrowRight size={22}/></Link></div></section>
  <section className="bg-white px-5 py-16 sm:py-24"><div className="mx-auto max-w-[1040px]"><p className="senior-section-label text-center">실제 화면으로 확인하세요</p><h2 className="mt-3 text-center text-3xl font-black sm:text-5xl">질문 하나가 가족의 행동으로 이어집니다.</h2><div className="mt-10 grid gap-6 md:grid-cols-2"><Scene title="부모님 화면 · 질문 하나" message="오늘은 평소보다 조금 피곤하신가요?" action="조금 피곤해요"/><Scene title="가족 화면 · 행동 하나" message="피곤하다는 답이 이어졌어요." action="어머니께 전화하기"/></div><p className="mt-7 text-center text-lg font-black text-[#52635C]">화면에는 필요한 내용과 행동 하나만 보여드립니다.</p></div></section>
  <section className="senior-how"><p className="senior-section-label">쉬운 작동 방식</p><h2>필요한 날만 이어집니다.</h2><div className="mx-auto mt-10 grid max-w-[980px] gap-4 md:grid-cols-4">{simpleFlow.map((item,index)=><article key={item} className="rounded-[24px] bg-white p-6"><span className="senior-step-number">{index+1}</span><h3 className="mt-5 text-2xl font-black">{item}</h3></article>)}</div></section>
  <section className="bg-white px-5 py-16 text-center sm:py-24"><p className="senior-section-label">생활 변화 레이더</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">부모님의 평소와 비교합니다.</h2><p className="mx-auto mt-5 max-w-[680px] text-xl font-bold leading-9 text-[#56675E]">평소와 다른 흐름이<br/>이어지는지만 살펴봅니다.</p><Link href="/technology" className="mt-7 inline-flex min-h-14 items-center gap-2 font-black text-[#315B3D] underline underline-offset-4">자세한 기술 설명 보기 <ArrowRight size={20}/></Link></section>
  <section className="bg-[#173F35] px-5 py-16 text-center text-white sm:py-24"><h2 className="text-3xl font-black sm:text-5xl">질문이 오면<br/>하나만 눌러 주세요.</h2><Link href="/app?role=parent" className="mt-8 inline-flex min-h-[68px] items-center gap-2 rounded-2xl bg-white px-8 text-xl font-black text-[#173F35]">부모 화면 미리보기 <ArrowRight size={22}/></Link></section>
  <section className="mx-auto w-[calc(100%-40px)] max-w-[900px] py-16"><p className="senior-section-label">자주 묻는 질문</p><div className="mt-7 space-y-3"><Faq q="매일 답해야 하나요?" a="아닙니다. 필요한 날에만 질문 하나를 드립니다."/><Faq q="답하지 못하면 어떻게 되나요?" a="건너뛰어도 괜찮습니다."/><Faq q="제 위치를 계속 확인하나요?" a="아닙니다. 동의한 정보만 사용합니다."/><Faq q="자녀에게 어떤 정보가 보이나요?" a="평소와 다른 흐름과 답변한 내용만 확인할 수 있습니다."/><Faq q="사용을 그만두고 싶으면 어떻게 하나요?" a="설정에서 언제든 연결을 끊을 수 있습니다."/></div></section>
  <footer className="senior-footer">오늘안부 · 필요한 날에만 함께합니다.</footer>
</main>}

function Scene({title,message,action}:{title:string;message:string;action:string}){return <article className="rounded-[30px] bg-[#F2F7EF] p-7"><p className="text-lg font-black text-[#2F6B46]">{title}</p><h3 className="mt-4 text-2xl font-black leading-9">{message}</h3><div className="mt-6 flex min-h-16 items-center justify-center rounded-2xl bg-[#E9652B] px-5 text-xl font-black text-white">{action}</div></article>}
function Faq({q,a}:{q:string;a:string}){return <details className="rounded-[20px] border border-[#DFE6DC] bg-white p-5"><summary className="cursor-pointer text-xl font-black">{q}</summary><p className="mt-4 text-lg font-bold leading-8 text-[#586960]">{a}</p></details>}
