"use client";

import Link from "next/link";
import { useState } from "react";
import { Activity, ArrowLeft, Building2, Check, CheckCircle2, ChevronRight, HeartPulse, Phone, ShieldCheck } from "lucide-react";

type Screen="home"|"pain"|"medicine"|"done"|"journey"|"hospital";

export function PatientJourneyApp(){
  const [screen,setScreen]=useState<Screen>("home");
  const [senior,setSenior]=useState(false);
  if(screen==="pain") return <Question progress="1 / 2" question="오늘 많이 아프세요?" options={["안 아파요","조금 아파요","많이 아파요"]} next={()=>setScreen("medicine")} senior={senior}/>;
  if(screen==="medicine") return <Question progress="2 / 2" question="오늘 약은 챙겨 드셨나요?" options={["네, 먹었어요","아직이에요","먹기 어려워요"]} next={()=>setScreen("done")} senior={senior}/>;
  if(screen==="done") return <PatientFrame><div className="flex min-h-[calc(100dvh-69px)] flex-col justify-center px-6 py-10 text-center"><span className="mx-auto grid size-20 place-items-center rounded-full bg-[#daf0e7] text-[#1d6b5b]"><Check size={38}/></span><p className="mt-7 text-base font-black text-[#1d6b5b]">오늘 상태가 기록되었어요</p><h1 className="mt-3 text-3xl font-black">잘 알려주셨어요,<br/>김○○님.</h1><p className="mt-5 text-lg font-semibold leading-8 text-[#5f716a]">서울온병원과 현재 회복 흐름을 계속 확인하고 있어요. 추가 확인이 필요한 경우 병원 관리 절차에 따라 안내될 수 있어요.</p><button onClick={()=>setScreen("home")} className="mt-8 min-h-16 rounded-2xl bg-[#1d6b5b] text-lg font-black text-white">오늘 할 일 보기</button></div></PatientFrame>;
  if(screen==="journey") return <PatientFrame><div className="p-5 pb-28"><Back action={()=>setScreen("home")}/><p className="mt-6 text-base font-black text-[#1d6b5b]">MY RECOVERY</p><h1 className="mt-2 text-3xl font-black">회복 8일차예요.</h1><div className="mt-5 rounded-3xl bg-[#e9f3ef] p-6"><p className="font-black text-[#1d6b5b]">현재 회복 과정</p><h2 className="mt-2 text-2xl font-black">조금 더 살펴볼게요</h2><p className="mt-3 text-lg font-semibold leading-8 text-[#5c7068]">병원 관리 절차에 따라 오늘의 변화가 전달되었어요.</p></div><h2 className="mt-7 text-xl font-black">지금까지의 기록</h2><div className="mt-3 space-y-3">{[["체크인","7일"],["약 챙기기","8회"],["10분 걷기","5회"]].map(([a,b])=><div key={a} className="flex min-h-16 items-center justify-between rounded-2xl border border-[#dfe7e3] p-5"><span className="font-bold">{a}</span><strong>{b}</strong></div>)}</div><div className="mt-6 rounded-2xl border border-[#dfe7e3] p-5"><p className="font-bold text-[#74837e]">다음 외래</p><p className="mt-2 text-xl font-black">8월 28일 오전 10:30</p><p className="mt-1 font-semibold text-[#65756f]">서울온병원 정형외과</p></div></div><PatientNav onMove={setScreen} active="journey"/></PatientFrame>;
  if(screen==="hospital") return <PatientFrame><div className="p-5 pb-28"><Back action={()=>setScreen("home")}/><p className="mt-6 text-base font-black text-[#1d6b5b]">CONNECTED HOSPITAL</p><h1 className="mt-2 text-3xl font-black">서울온병원</h1><div className="mt-4 flex items-center gap-3 rounded-2xl bg-[#e7f3ee] p-4 font-black text-[#1d6b5b]"><ShieldCheck/>무릎 회복관리 Program과 연결됨</div><div className="mt-5 divide-y rounded-2xl border border-[#dfe7e3] px-5">{[["담당 진료과","정형외과"],["다음 예정 진료","8월 28일 오전 10:30"],["병원 전화","02-000-0000"],["운영시간","평일 09:00–18:00"]].map(([a,b])=><div key={a} className="py-4"><p className="font-bold text-[#778681]">{a}</p><p className="mt-1 text-lg font-black">{b}</p></div>)}</div><a href="tel:020000000" className="mt-5 flex min-h-16 items-center justify-center gap-2 rounded-2xl bg-[#123f35] text-lg font-black text-white"><Phone/>병원에 전화하기</a><div className="mt-5 rounded-2xl bg-[#fff6ed] p-5"><p className="text-lg font-black">긴급한 증상이 있나요?</p><p className="mt-2 font-semibold leading-7 text-[#6f6258]">오늘안부는 상태를 기록하고 치료 Journey를 연결하는 서비스예요. 새로운 증상이나 긴급한 상담은 병원 또는 119에 문의해주세요.</p></div></div><PatientNav onMove={setScreen} active="hospital"/></PatientFrame>;
  return <PatientFrame><div className="px-5 pb-28 pt-6"><div className="rounded-2xl border border-[#cfe0da] bg-[#f0f7f4] p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#1d6b5b] text-white"><Building2 size={20}/></span><div><p className="font-black">서울온병원과 함께 관리 중</p><p className="mt-0.5 font-bold text-[#62766e]">무릎 회복관리 Program · <span className="text-[#1d6b5b]">연결됨</span></p></div></div></div><div className="mt-5 flex justify-end"><button onClick={()=>setSenior(!senior)} className="min-h-12 rounded-full border border-[#ccd8d3] px-4 font-black">{senior?"기본 글씨":"큰 글씨"}</button></div><p className="mt-5 text-lg font-bold text-[#63756e]">김○○님, 오늘은</p><h1 className="mt-2 text-4xl font-black">치료 8일째예요.</h1><div className="mt-5 rounded-3xl bg-[#e9f3ef] p-6"><p className="font-black text-[#1d6b5b]">오늘의 회복 안내</p><h2 className="mt-2 text-2xl font-black">조금 더 살펴볼게요</h2><p className="mt-3 text-lg font-semibold leading-8 text-[#5f716a]">오늘 상태를 알려주시면 병원 관리 절차에 따라 확인할게요.</p></div><h2 className="mt-7 text-xl font-black">오늘은 세 가지만 해주세요.</h2><div className="mt-3 space-y-3"><Task done text="아침 약 챙기기"/><Task text="10분 걷기"/><Task text="오늘 상태 알려주기"/></div><button onClick={()=>setScreen("pain")} className="mt-5 min-h-[72px] w-full rounded-2xl bg-[#1d6b5b] text-xl font-black text-white">오늘 상태 알려주기</button><p className="mt-4 text-center font-semibold leading-6 text-[#6f7e79]">긴급한 증상은 병원이나 119에 연락해주세요.</p></div><PatientNav onMove={setScreen} active="home"/></PatientFrame>;
}

function PatientFrame({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-[#eef3f0] text-[#172720]"><div className="mx-auto min-h-screen max-w-[520px] bg-white shadow-xl"><header className="flex min-h-[69px] items-center justify-between border-b border-[#e3eae7] px-5"><Link href="/" className="flex items-center gap-2 text-lg font-black text-[#123f35]"><HeartPulse size={22}/>오늘안부</Link><span className="font-black text-[#6f7e79]">Journey D+8</span></header>{children}</div></div>}
function Back({action}:{action:()=>void}){return <button onClick={action} className="flex min-h-12 items-center gap-2 text-lg font-black"><ArrowLeft/>오늘</button>}
function Task({text,done}:{text:string;done?:boolean}){return <div className="flex min-h-[68px] items-center gap-4 rounded-2xl border border-[#dce5e1] p-4"><span className={`grid size-8 place-items-center rounded-full ${done?"bg-[#1d6b5b] text-white":"border-2 border-[#b7c8c1]"}`}>{done&&<Check size={17}/>}</span><span className={`text-lg font-black ${done?"text-[#70817b] line-through":""}`}>{text}</span></div>}
function PatientNav({onMove,active}:{onMove:(s:Screen)=>void;active:Screen}){return <nav className="fixed inset-x-0 bottom-0 mx-auto flex max-w-[520px] justify-around border-t border-[#dfe7e3] bg-white px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-3"><NavButton onClick={()=>onMove("home")} active={active==="home"} icon={<CheckCircle2/>} label="오늘"/><NavButton onClick={()=>onMove("journey")} active={active==="journey"} icon={<Activity/>} label="내 회복"/><NavButton onClick={()=>onMove("hospital")} active={active==="hospital"} icon={<Building2/>} label="병원"/></nav>}
function NavButton({onClick,active,icon,label}:{onClick:()=>void;active:boolean;icon:React.ReactNode;label:string}){return <button onClick={onClick} className={`grid min-h-12 place-items-center text-sm font-black ${active?"text-[#1d6b5b]":"text-[#6f7e79]"}`}><span className="[&>svg]:size-[22px]">{icon}</span>{label}</button>}
function Question({progress,question,options,next,senior}:{progress:string;question:string;options:string[];next:()=>void;senior:boolean}){return <PatientFrame><div className={`flex min-h-[calc(100dvh-69px)] flex-col px-6 py-7 ${senior?"text-[1.15rem]":""}`}><div className="h-2 overflow-hidden rounded-full bg-[#e5ebe8]"><div className={`h-full bg-[#1d6b5b] ${progress.startsWith("1")?"w-1/2":"w-full"}`}/></div><p className="mt-7 text-base font-black text-[#1d6b5b]">{progress}</p><h1 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">{question}</h1><p className="mt-3 text-lg font-semibold text-[#6a7974]">가장 가까운 답을 눌러주세요.</p><div className="mt-7 space-y-3">{options.map((x,i)=><button onClick={next} key={x} className={`min-h-[76px] w-full rounded-2xl border-2 px-5 text-left text-xl font-black ${i===2?"border-[#e7bfb4] bg-[#fff8f5] text-[#a33f27]":"border-[#cedbd6]"}`}>{x}<ChevronRight className="float-right"/></button>)}</div></div></PatientFrame>}
