"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,Check,ChevronRight,HeartPulse,Hospital,ShieldCheck } from "lucide-react";
import { evaluatePatientStatus,loadCareState,mobilityLabels,painLabels,saveCareState,TODAY,type CareState,type Patient } from "@/lib/care-mvp";
import { trackCareEvent } from "@/lib/care-analytics";
import { CareCompanion } from "@/components/care-companion";
import { findInvitation,getPatientSession,verifyPatientIdentity } from "@/lib/demo-auth";

type Mode="home"|"onboarding"|"checkin"|"history";
export function PatientCareMvp({mode}:{mode:Mode}){
  const [state,setState]=useState<CareState|null>(null),[patient,setPatient]=useState<Patient|null>(null),[invalid,setInvalid]=useState(false),[onboardStep,setOnboardStep]=useState(0),[question,setQuestion]=useState(0),[pain,setPain]=useState<number|null>(null),[mobility,setMobility]=useState<number|null>(null),[hasConcern,setHasConcern]=useState<boolean|null>(null),[concernText,setConcernText]=useState(""),[saved,setSaved]=useState(false);
  useEffect(()=>{const next=loadCareState(),params=new URLSearchParams(location.search),token=params.get("token"),invitation=token?findInvitation(token):null,session=getPatientSession();const id=mode==="onboarding"?invitation?.patientId:session?.patientId;const found=next.patients.find(p=>p.id===id&&((mode==="onboarding"&&p.hospitalId===invitation?.hospitalId)||(mode!=="onboarding"&&p.hospitalId===session?.hospitalId)));setState(next);setPatient(found||null);setInvalid(!found);if(mode==="onboarding"&&found)trackCareEvent("patient_onboarding_started",{patientId:found.id});if(mode==="checkin"&&found)trackCareEvent("checkin_started",{patientId:found.id})},[mode]);
  const hospital=state?.hospitals.find(h=>h.id===patient?.hospitalId);const todayCheck=state?.checkIns.find(c=>c.patientId===patient?.id&&c.date===TODAY);const history=useMemo(()=>state?.checkIns.filter(c=>c.patientId===patient?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))||[],[state,patient]);
  if(invalid)return <PatientShell><Empty title="초대 링크를 확인할 수 없어요" text="병원에서 받은 링크를 다시 확인하거나 병원에 문의해 주세요."/></PatientShell>;
  if(!state||!patient)return <PatientShell><p className="py-24 text-center text-lg font-bold">정보를 불러오고 있어요.</p></PatientShell>;
  if(mode==="onboarding"){
    if(onboardStep===0)return <PatientShell><div className="py-10"><Hospital className="text-[#315E50]" size={42}/><p className="mt-5 text-lg font-black text-[#315E50]">{hospital?.name}</p><h1 className="mt-3 text-3xl font-black leading-tight">퇴원 후 회복 확인을 위해<br/>오늘안부를 안내했습니다.</h1><div className="mt-8 rounded-3xl bg-white p-6"><p className="text-xl font-black">{patient.name}님 맞으신가요?</p><p className="mt-2 text-lg text-[#617069]">회원가입이나 비밀번호 없이 시작합니다.</p></div><button onClick={()=>setOnboardStep(1)} className="primary">네, 시작할게요</button></div></PatientShell>;
    return <PatientShell><div className="py-10"><ShieldCheck className="text-[#315E50]" size={44}/><h1 className="mt-5 text-3xl font-black">매일 오래 입력하지 않아도 됩니다.</h1><ul className="mt-7 space-y-4 text-lg font-bold leading-8"><li>✓ 하루 한 번 간단히 확인합니다.</li><li>✓ 회복 상태를 병원과 함께 확인할 수 있습니다.</li><li>✓ 전화·문자 내용이나 개인 사진을 확인하지 않습니다.</li></ul><button onClick={()=>{const token=new URLSearchParams(location.search).get("token");if(!token||!verifyPatientIdentity(token)){setInvalid(true);return}const next={...state,patients:state.patients.map(p=>p.id===patient.id?{...p,status:"onboarded" as const}:p)};saveCareState(next);trackCareEvent("patient_onboarding_completed",{patientId:patient.id});location.href="/app/patient"}} className="primary">확인했어요</button></div></PatientShell>;
  }
  if(mode==="checkin"){
    if(todayCheck||saved)return <PatientShell><div className="py-12 text-center"><span className="mx-auto grid size-20 place-items-center rounded-full bg-[#DDEDE3] text-[#315E50]"><Check size={42}/></span><h1 className="mt-6 text-3xl font-black">오늘 확인이 끝났어요.</h1><p className="mt-3 text-lg font-bold text-[#46574F]">알려주셔서 감사합니다.</p><Link href="/app/patient" className="primary">홈으로</Link><p className="mt-6 rounded-2xl bg-white p-4 text-left text-[16px] font-bold leading-7 text-[#46574F]">갑자기 많이 아프거나 급한 상황이라면 오늘안부를 기다리지 말고 안내받은 병원 또는 119를 이용해주세요.</p></div></PatientShell>;
    const choices=question===0?painLabels:question===1?mobilityLabels:["없어요","있어요"];const value=question===0?pain:question===1?mobility:hasConcern===null?null:hasConcern?1:0;
    return <PatientShell><div className="flex min-h-[calc(100dvh-40px)] flex-col py-5"><p className="text-base font-black text-[#315E50]">{question+1} / 3</p><div className="mt-5 h-2 rounded-full bg-[#DDE5E0]"><div className="h-full rounded-full bg-[#315E50] transition-all" style={{width:`${(question+1)*33.33}%`}}/></div><h1 className="mt-10 text-3xl font-black leading-tight">{question===0?"오늘 통증은 어떠세요?":question===1?"오늘 움직이기는 어떠셨어요?":"평소와 다른 불편함이 있나요?"}</h1><div className="mt-7 grid gap-3">{choices.map((label,i)=><button key={label} onClick={()=>question===0?setPain(i):question===1?setMobility(i):setHasConcern(i===1)} className={`min-h-[64px] rounded-2xl border-2 px-5 text-left text-lg font-black ${value===i?"border-[#315E50] bg-[#E8F1EA]":"border-[#C8D3CD] bg-white"}`}>{label}</button>)}</div>{question===2&&hasConcern?<textarea value={concernText} onChange={e=>setConcernText(e.target.value)} placeholder="예: 붓기가 있어요 (선택)" maxLength={100} className="mt-4 min-h-24 rounded-2xl border-2 border-[#C8D3CD] bg-white p-4 text-lg"/>:null}<div className="mt-auto flex gap-3 pt-8">{question>0?<button onClick={()=>setQuestion(q=>q-1)} className="min-h-[60px] rounded-2xl border-2 border-[#315E50] px-5 text-lg font-black"><ArrowLeft/></button>:null}<button disabled={value===null} onClick={()=>{if(question<2){setQuestion(q=>q+1);return}if(pain===null||mobility===null||hasConcern===null)return;const check={id:`check_${Date.now()}`,patientId:patient.id,date:TODAY,pain,mobility,hasConcern,concernText,createdAt:new Date().toISOString()};const previous=history[0];const status=evaluatePatientStatus(check,previous);const next={...state,checkIns:[...state.checkIns,check],statuses:[...state.statuses.filter(s=>s.patientId!==patient.id),status]};try{saveCareState(next);setState(next);setSaved(true);trackCareEvent("checkin_completed",{patientId:patient.id});trackCareEvent("patient_status_changed",{patientId:patient.id,level:status.level})}catch{alert("저장하지 못했어요. 잠시 후 다시 시도해 주세요.")}}} className="min-h-[60px] flex-1 rounded-2xl bg-[#315E50] text-xl font-black text-white disabled:bg-[#B7C2BC]">{question===2?"오늘 확인 마치기":"다음"}</button></div></div></PatientShell>;
  }
  if(mode==="history")return <PatientShell><header className="py-5"><Link href={`/app/patient?id=${patient.id}`} className="flex items-center gap-2 font-black text-[#315E50]"><ArrowLeft/> 홈</Link><h1 className="mt-7 text-3xl font-black">지난 기록</h1></header>{history.length?<div className="space-y-3">{history.map(c=><article key={c.id} className="rounded-2xl bg-white p-5"><p className="font-black">{c.date===TODAY?"오늘":c.date}</p><p className="mt-3 text-lg">통증: <strong>{painLabels[c.pain]}</strong></p><p className="mt-1 text-lg">움직임: <strong>{mobilityLabels[c.mobility]}</strong></p>{c.hasConcern?<p className="mt-1 text-lg">추가 불편: <strong>{c.concernText||"있어요"}</strong></p>:null}</article>)}</div>:<Empty title="아직 회복 기록이 없습니다" text="오늘 상태를 알려주시면 여기에 기록됩니다." action={`/patient/checkin?id=${patient.id}`}/>}</PatientShell>;
  return <PatientShell><header className="flex items-center gap-2 py-5 text-xl font-black text-[#315E50]"><HeartPulse/> 오늘안부 Care</header><section className="mt-2 rounded-[28px] bg-white p-6"><p className="flex items-center gap-2 text-lg font-black text-[#315E50]"><Hospital size={21}/>{hospital?.name}와 함께하는 회복 확인</p><div className="mx-auto mt-3 w-[120px]"><CareCompanion state={todayCheck?"completed":"welcome"} compact/></div><h1 className="mt-3 text-[2.05rem] font-black leading-tight">오늘 몸은 어떠세요?</h1>{todayCheck?<><div className="mt-5 rounded-2xl bg-[#E8F1EA] p-5"><p className="text-xl font-black text-[#315E50]">오늘 확인을 마쳤어요.</p><p className="mt-2 text-lg font-bold text-[#46574F]">알려주셔서 감사합니다.</p></div><Link href="/patient/history" className="secondary">지난 기록 보기 <ChevronRight/></Link></>:<><p className="mt-3 text-xl font-bold leading-8 text-[#46574F]">1분이면 오늘 확인이 끝나요.<br/>간단하게 알려주세요.</p><Link href="/patient/checkin" className="primary">오늘 상태 확인하기 <ChevronRight/></Link></>}</section><p className="mt-5 rounded-2xl bg-white p-4 text-[16px] font-bold leading-7 text-[#46574F]">갑자기 많이 아프거나 급한 상황이라면 병원 또는 119에 연락하세요.</p></PatientShell>;
}
function PatientShell({children}:{children:React.ReactNode}){return <main className="min-h-[100dvh] bg-[#F1F0E9] px-5 text-[#202923] [font-size:18px]"><div className="mx-auto max-w-[520px]">{children}</div></main>}
function Empty({title,text,action}:{title:string;text:string;action?:string}){return <div className="rounded-3xl bg-white p-8 text-center"><h1 className="text-2xl font-black">{title}</h1><p className="mt-3 text-lg text-[#617069]">{text}</p>{action?<Link href={action} className="primary">오늘 상태 확인하기</Link>:null}</div>}
