"use client";
import {useMemo,useState} from "react";
import {Footprints,HeartPulse,Moon} from "lucide-react";
import {type CheckIn,comparisonLabels,concernLabels,type FollowUp,mobilityLabels,painValue} from "@/lib/care-mvp";

export function RecoveryTrend({checks,followUps=[],audience}:{checks:CheckIn[];followUps?:FollowUp[];audience:"patient"|"hospital"}){
 const[period,setPeriod]=useState(audience==="patient"?"7":"14");
 const sorted=useMemo(()=>[...checks].sort((a,b)=>a.date.localeCompare(b.date)),[checks]);
 const view=period==="all"?sorted:sorted.slice(-Number(period)),latest=view.at(-1),previous=view.at(-2),delta=latest&&previous?painValue(latest)-painValue(previous):null;
 const overall=view.length>2?painValue(view.at(-1)!)-painValue(view[0]):delta;
 const summary=overall===null?"기록이 쌓이면 회복 변화를 보여드릴게요.":overall<0?`지난 ${period==="all"?"전체 기간":`${period}일`} 동안 통증이 전반적으로 줄었어요.`:overall>0?`지난 ${period==="all"?"전체 기간":`${period}일`} 동안 통증을 조금 더 살펴볼 필요가 있어요.`:"통증은 전반적으로 비슷한 수준이에요.";
 return <section className="mt-7 border-t border-[#CBD8D1] pt-7">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-lg font-black text-[#315E50]">회복 변화</p><h3 className="mt-2 text-2xl font-black">{audience==="patient"?summary:"통증 추이"}</h3>{audience==="patient"&&delta!==null?<p className="mt-2 text-lg font-bold leading-7 text-[#596A62]">{delta>0?"전체 흐름과 달리 오늘 기록은 어제보다 조금 높았어요.":delta<0?"오늘 기록도 어제보다 조금 낮아졌어요.":"오늘 기록은 어제와 비슷해요."}</p>:null}</div><div className="flex gap-1 rounded-xl bg-[#E4EAE6] p-1" aria-label="회복 기간">{(audience==="patient"?[["7","7일"],["14","14일"],["all","전체"]]:[["7","7일"],["14","14일"],["30","30일"],["all","전체"]]).map(([v,l])=><button key={v} aria-pressed={period===v} onClick={()=>setPeriod(v)} className={`min-h-12 rounded-lg px-4 text-base font-black ${period===v?"bg-[#315E50] text-white shadow-sm":"text-[#46574F]"}`}>{l}</button>)}</div></div>
  {audience==="patient"?<div className="mt-6 grid gap-4"><TrendRow icon={<HeartPulse/>} title="통증 변화" text={summary} value={view.length?`${painValue(view[0])} → ${painValue(view.at(-1)!)}점`:"기록 준비 중"}/><TrendRow icon={<Footprints/>} title="걷기 변화" text="지난 기간 동안 비슷한 수준을 유지하고 있어요." value={latest?mobilityLabels[latest.mobilityScore??latest.mobility]:"기록 준비 중"}/><TrendRow icon={<Moon/>} title="수면 변화" text="잠드는 흐름이 조금씩 나아지고 있어요." value="조금 나아짐"/></div>:latest?<div className="mt-5 rounded-2xl bg-[#F8FAF8] p-5"><p className="font-black">최근 기록 {latest.date}</p><p className="mt-2 text-3xl font-black text-[#315E50]">통증 {painValue(latest)} / 10</p><p className="mt-2 font-bold">움직임 {mobilityLabels[latest.mobilityScore??latest.mobility]} {latest.dayComparison?`· 전일 대비 ${comparisonLabels[latest.dayComparison]}`:""}</p></div>:null}
  {view.length<2
    ? <p className="mt-5 rounded-2xl bg-white p-5 font-bold text-[#596A62]">아직 변화 추이를 보여드리기에는 기록이 조금 더 필요해요.</p>
    : <PainChart checks={view} followUps={followUps}/>
  }
  {audience==="hospital"?<div className="mt-6 grid gap-5 lg:grid-cols-2"><RecordList title="움직임 기록" checks={view}/><div><h4 className="text-lg font-black">최근 불편 기록</h4><div className="mt-3 space-y-2">{view.slice(-7).reverse().map(c=><div key={c.id} className="rounded-xl bg-[#F6F7F6] p-3"><strong>{c.date.slice(5).replace("-","/")}</strong><p className="mt-1 font-bold text-[#526159]">{(c.concerns||[c.hasConcern?"other":"none"]).map(x=>x==="other"?(c.customConcern||c.concernText||"기타"):concernLabels[x]||x).join(" · ")}</p></div>)}</div></div></div>:null}
 </section>
}
function TrendRow({icon,title,text,value}:{icon:React.ReactNode;title:string;text:string;value:string}){return <article className="grid grid-cols-[auto_1fr] gap-4 border-b border-[#D7E0DB] pb-5"><span className="grid size-12 place-items-center rounded-xl bg-[#E8F1EA] text-[#315E50]">{icon}</span><div><h4 className="text-xl font-black">{title}</h4><p className="mt-1 text-lg font-bold leading-7 text-[#596A62]">{text}</p><p className="mt-2 text-lg font-black text-[#315E50]">{value}</p></div></article>}
function RecordList({title,checks}:{title:string;checks:CheckIn[]}){return <div><h4 className="text-lg font-black">{title}</h4><div className="mt-3 space-y-2">{checks.slice(-7).reverse().map(c=><div key={c.id} className="flex justify-between gap-3 rounded-xl bg-[#F6F7F6] p-3"><strong>{c.date.slice(5).replace("-","/")}</strong><span className="text-right font-bold text-[#526159]">{mobilityLabels[c.mobilityScore??c.mobility]}</span></div>)}</div></div>}
function PainChart({checks,followUps}:{checks:CheckIn[];followUps:FollowUp[]}){const width=560,height=190,pad=28,pts=checks.map((c,i)=>({x:pad+i*(width-pad*2)/(checks.length-1),y:pad+(10-painValue(c))*(height-pad*2)/10,c}));return <div className="mt-6 overflow-x-auto pb-2"><div className="relative min-w-[560px]" role="img" aria-label={`통증 변화 ${checks.map(c=>`${c.date} ${painValue(c)}점`).join(", ")}`}><svg aria-hidden viewBox={`0 0 ${width} ${height}`} className="h-[190px] w-[560px]"><path d={`M ${pts.map(p=>`${p.x} ${p.y}`).join(" L ")}`} fill="none" stroke="#4C7B69" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{pts.map(p=><g key={p.c.id}><circle cx={p.x} cy={p.y} r="6" fill="#fff" stroke="#315E50" strokeWidth="4"/><text x={p.x} y={p.y-13} textAnchor="middle" fontSize="16" fontWeight="800" fill="#315E50">{painValue(p.c)}</text>{followUps.some(f=>f.completedAt.slice(0,10)===p.c.date)?<circle cx={p.x} cy={height-12} r="5" fill="#E9652B"/>:null}</g>)}</svg><div className="flex w-[560px] justify-between px-5 text-base font-bold text-[#596A62]">{checks.map(c=><span key={c.id}>{c.date.slice(5).replace("-","/")}</span>)}</div></div></div>}
