"use client";
import { useMemo, useState } from "react";
import { CheckIn, comparisonLabels, concernLabels, FollowUp, mobilityLabels, painValue } from "@/lib/care-mvp";

export function RecoveryTrend({checks,followUps=[],audience}:{checks:CheckIn[];followUps?:FollowUp[];audience:"patient"|"hospital"}){
 const [period,setPeriod]=useState(audience==="patient"?"7":"14");
 const sorted=useMemo(()=>[...checks].sort((a,b)=>a.date.localeCompare(b.date)),[checks]);
 const view=period==="all"?sorted:sorted.slice(-Number(period));const latest=view.at(-1),previous=view.at(-2),delta=latest&&previous?painValue(latest)-painValue(previous):null;
 return <section className="mt-5 rounded-3xl border border-[#DDE5E0] bg-white p-5 sm:p-6">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-black">{audience==="patient"?"최근 통증 변화":"통증 추이"}</h3><p className="mt-1 text-sm font-semibold text-[#68766F]">최근 기록을 날짜별로 보여드려요. 평가나 진단을 의미하지 않습니다.</p></div><div className="flex gap-1 rounded-xl bg-[#EEF3F0] p-1">{(audience==="patient"?[["7","7일"],["14","14일"],["all","전체"]]:[["7","7일"],["14","14일"],["30","30일"],["all","전체"]]).map(([v,l])=><button key={v} onClick={()=>setPeriod(v)} className={`min-h-10 rounded-lg px-3 text-sm font-black ${period===v?"bg-white text-[#315E50] shadow-sm":"text-[#68766F]"}`}>{l}</button>)}</div></div>
  {latest?<div className="mt-5 grid grid-cols-2 gap-3"><Metric label="오늘 통증" value={`${painValue(latest)} / 10`}/><Metric label={previous?"이전 기록":"기록일"} value={previous?`${painValue(previous)} / 10`:latest.date.slice(5).replace("-","/")}/></div>:null}
  {view.length<2?<p className="mt-5 rounded-2xl bg-[#F3F5F3] p-5 font-bold text-[#68766F]">{audience==="patient"?"아직 변화 추이를 보여드리기에는 기록이 조금 더 필요해요. 오늘 기록은 저장되었습니다.":"추이 분석을 위한 기록이 아직 부족합니다."}</p>:<PainChart checks={view} followUps={followUps}/>} 
  {audience==="hospital"&&delta!==null?<p className="mt-4 rounded-xl bg-[#EEF4F0] p-4 font-black text-[#315E50]">오늘 {painValue(latest!)} / 10 · 전일 대비 {delta>0?`+${delta}`:delta} · 최근 3회 {view.slice(-3).map(painValue).join(" → ")}</p>:null}
  <div className="mt-6 grid gap-5 lg:grid-cols-2"><div><h4 className="font-black">움직임 기록</h4><div className="mt-3 space-y-2">{view.slice(-7).reverse().map(c=><div key={c.id} className="flex justify-between gap-3 rounded-xl bg-[#F6F7F6] p-3 text-sm"><strong>{c.date.slice(5).replace("-","/")}</strong><span className="text-right font-bold text-[#526159]">{mobilityLabels[c.mobilityScore??c.mobility]}</span></div>)}</div></div><div><h4 className="font-black">{audience==="hospital"?"Concern Timeline":"최근 불편 기록"}</h4><div className="mt-3 space-y-2">{view.slice(-7).reverse().map(c=><div key={c.id} className="rounded-xl bg-[#F6F7F6] p-3 text-sm"><strong>{c.date.slice(5).replace("-","/")}</strong><p className="mt-1 font-bold text-[#526159]">{(c.concerns||[c.hasConcern?"other":"none"]).map(x=>x==="other"?(c.customConcern||c.concernText||"기타"):concernLabels[x]||x).join(" · ")}</p>{c.dayComparison?<p className="mt-1 text-[#68766F]">어제 대비 {comparisonLabels[c.dayComparison]}</p>:null}{followUps.filter(f=>f.completedAt.slice(0,10)===c.date).map(f=><details key={f.id} className="mt-2 rounded-lg bg-[#E8F1EA] p-2"><summary className="cursor-pointer font-black text-[#315E50]">병원 후속조치 · {f.action}</summary><p className="mt-1">{f.handledBy} · {new Date(f.completedAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</p>{f.note?<p>{f.note}</p>:null}</details>)}</div>)}</div></div></div>
 </section>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-[#EEF4F0] p-4"><p className="text-sm font-bold text-[#68766F]">{label}</p><p className="mt-1 text-2xl font-black text-[#315E50]">{value}</p></div>}
function PainChart({checks,followUps}:{checks:CheckIn[];followUps:FollowUp[]}){const width=560,height=190,pad=24,pts=checks.map((c,i)=>({x:pad+(checks.length===1?0:i*(width-pad*2)/(checks.length-1)),y:pad+(10-painValue(c))*(height-pad*2)/10,c}));return <div className="mt-5 overflow-x-auto"><div className="relative min-w-[560px]" role="img" aria-label={`최근 통증 기록 ${checks.map(c=>`${c.date} ${painValue(c)}점`).join(", ")}`}><div className="absolute left-0 top-0 flex h-[190px] flex-col justify-between py-4 text-xs font-bold text-[#68766F]"><span>10</span><span>5</span><span>0</span></div><svg aria-hidden="true" viewBox={`0 0 ${width} ${height}`} className="ml-5 h-[190px] w-[560px]"><path d={`M ${pts.map(p=>`${p.x} ${p.y}`).join(" L ")}`} fill="none" stroke="#4C7B69" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{pts.map(p=><g key={p.c.id}><circle cx={p.x} cy={p.y} r="6" fill="#FFF" stroke="#315E50" strokeWidth="4"/><text x={p.x} y={p.y-12} textAnchor="middle" fontSize="13" fontWeight="800" fill="#315E50">{painValue(p.c)}</text>{followUps.some(f=>f.completedAt.slice(0,10)===p.c.date)?<circle cx={p.x} cy={height-11} r="5" fill="#E9652B"/>:null}</g>)}</svg><div className="ml-5 flex w-[560px] justify-between px-5 text-xs font-bold text-[#68766F]">{checks.map(c=><span key={c.id}>{c.date.slice(5).replace("-","/")}</span>)}</div><table className="sr-only"><caption>최근 통증 기록</caption><tbody>{checks.map(c=><tr key={c.id}><th>{c.date}</th><td>{painValue(c)}점</td></tr>)}</tbody></table></div></div>}
