"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Download, Filter, FlaskConical, Users } from "lucide-react";
import { CASES, readList, RESPONSE_KEY, ResearchResponse, SEED_RESPONSES } from "@/lib/orthopedics-research";

const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;
const avg=(xs:(number|undefined)[])=>{const v=xs.filter((x):x is number=>typeof x==="number");return v.length?(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):"-"};
function count(values:(string|undefined)[]){return Object.entries(values.filter(Boolean).reduce<Record<string,number>>((a,v)=>(a[v!]=(a[v!]||0)+1,a),{})).sort((a,b)=>b[1]-a[1])}
function Bars({items,total}:{items:[string,number][];total:number}){return <div className="space-y-3">{items.map(([label,n])=><div key={label}><div className="mb-1 flex justify-between gap-3 text-sm font-bold"><span>{label}</span><span>{n} · {pct(n,total)}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#4C7B69]" style={{width:`${pct(n,total)}%`}}/></div></div>)}</div>}

export function ResearchAdmin(){
 const [saved,setSaved]=useState<ResearchResponse[]>([]),[role,setRole]=useState("전체"),[org,setOrg]=useState("전체"),[exp,setExp]=useState("전체"),[complete,setComplete]=useState("전체");
 useEffect(()=>setSaved(readList<ResearchResponse>(RESPONSE_KEY)),[]);
 const all=useMemo(()=>[...SEED_RESPONSES,...saved],[saved]);
 const rows=useMemo(()=>all.filter(r=>(role==="전체"||r.role===role)&&(org==="전체"||r.organizationType===org)&&(exp==="전체"||r.experience===exp)&&(complete==="전체"||(complete==="완료")===!!r.completedAt)),[all,role,org,exp,complete]);
 const done=rows.filter(r=>r.completedAt),pilot=done.filter(r=>r.pilotInterest==="관심 있음"||r.pilotInterest==="조금 더 알아보고 싶음");
 const multi=(key:"importantSignals"|"adoptionReasons")=>count(done.flatMap(r=>r[key]));
 const csv=()=>{const headers=["id","researchVersion","startedAt","completedAt","role","organizationType","experience","caseResponses","importantSignals","dashboardPriorityScore","dashboardReasonScore","followupAdequacy","expectedOperator","manageableAlerts","acceptableHandlingTime","adoptionReasons","nonAdoptionReason","pilotInterest","isDemo"];const escape=(v:unknown)=>`"${String(typeof v==="object"?JSON.stringify(v):v??"").replaceAll('"','""')}"`;const text=[headers.join(","),...rows.map(r=>headers.map(h=>escape(r[h as keyof ResearchResponse])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\uFEFF"+text],{type:"text/csv;charset=utf-8"}));a.download=`oneul-anbu-orthopedics-research-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <main className="min-h-screen bg-slate-100 text-slate-950"><div className="mx-auto flex min-h-screen max-w-[1600px]"><aside className="hidden w-64 shrink-0 bg-slate-950 px-5 py-7 text-white lg:block"><Link href="/admin" className="text-xl font-black">오늘안부 Admin</Link><p className="mt-2 text-xs text-slate-400">내부 운영 전용</p><nav className="mt-10 space-y-2"><Link href="/admin" className="flex items-center gap-3 rounded-xl px-3 py-3 font-bold text-slate-300"><BarChart3 size={18}/>운영 대시보드</Link><span className="flex items-center gap-3 rounded-xl bg-teal-500 px-3 py-3 font-black text-slate-950"><FlaskConical size={18}/>의료진 제품 검증</span></nav></aside><section className="min-w-0 flex-1 px-4 py-7 sm:px-8 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-black text-teal-700">제품 검증 · 초기 Evidence</p><h1 className="mt-1 text-3xl font-black">의료진 검증 현황</h1><p className="mt-2 text-sm text-slate-500">의료적 기준이 아닌 제품 설계를 위한 의료진 응답입니다.</p></div><button onClick={csv} className="flex min-h-12 items-center gap-2 rounded-xl bg-slate-950 px-5 font-black text-white"><Download size={18}/>익명 CSV</button></div>
 <section className="mt-6 rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center gap-2 font-black"><Filter size={18}/>필터</div><div className="grid gap-3 sm:grid-cols-4">{[[role,setRole,["전체",...new Set(all.map(r=>r.role).filter(Boolean))]],[org,setOrg,["전체",...new Set(all.map(r=>r.organizationType).filter(Boolean))]],[exp,setExp,["전체",...new Set(all.map(r=>r.experience).filter(Boolean))]],[complete,setComplete,["전체","완료","진행 중"]]].map(([value,setter,values],i)=><select aria-label={["역할","기관 유형","경력","완료 여부"][i]} key={i} value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="min-h-12 rounded-xl border px-3 font-bold">{(values as string[]).map(v=><option key={v}>{v}</option>)}</select>)}</div></section>
 <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["시작 참여자",rows.length,"필터 기준"],["완료 참여자",done.length,"응답 완료"],["완료율",`${pct(done.length,rows.length)}%`,"완료/시작"],["평균 소요시간",done.length?`${Math.round(done.reduce((a,r)=>a+(new Date(r.completedAt!).getTime()-new Date(r.startedAt).getTime())/60000,0)/done.length)}분`:"-","브라우저 기록"],["Pilot 관심",pilot.length,"관심·추가정보"]].map(([l,v,n])=><article key={l as string} className="rounded-2xl border bg-white p-5"><p className="text-sm font-bold text-slate-500">{l}</p><p className="mt-2 text-3xl font-black">{v}</p><p className="mt-2 text-xs text-teal-700">{n}</p></article>)}</div>
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><Card title="참여자 구성"><h3 className="mb-3 font-black">역할</h3><Bars items={count(done.map(r=>r.role))} total={done.length}/><h3 className="mb-3 mt-6 font-black">기관 유형</h3><Bars items={count(done.map(r=>r.organizationType))} total={done.length}/></Card><Card title="환자 UX 결과"><div className="grid grid-cols-2 gap-3"><Metric label="고령환자 사용 가능성" value={`${avg(done.map(r=>r.patientUxScore))} / 5`}/><Metric label="Check-in 유용성" value={`${avg(done.map(r=>r.checkinUsefulnessScore))} / 5`}/></div><h3 className="mb-3 mt-6 font-black">불필요 질문 선택</h3><Bars items={count(done.flatMap(r=>r.unnecessaryQuestions))} total={done.length}/><Free title="추가 필요 항목" values={done.map(r=>r.missingQuestions)}/></Card></div>
 <Card title="가상환자 판단 결과" wide><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{CASES.map(c=>{const rs=done.flatMap(r=>r.caseResponses).filter(x=>x.caseId===c.id);return <article key={c.id} className="rounded-2xl border bg-slate-50 p-4"><h3 className="font-black">Case {c.id} · {c.meta}</h3><div className="mt-4"><Bars total={rs.length} items={[["연락한다",rs.filter(x=>x.decision==="contact").length],["연락하지 않는다",rs.filter(x=>x.decision==="no_contact").length],["판단 어려움",rs.filter(x=>x.decision==="unsure").length]]}/></div><details className="mt-4"><summary className="cursor-pointer text-sm font-black text-teal-700">판단 이유 보기</summary><ul className="mt-2 space-y-2 text-sm text-slate-600">{rs.slice(0,5).map((x,i)=><li key={i} className="rounded-lg bg-white p-2">{x.reason}</li>)}</ul></details></article>})}</div></Card>
 <div className="grid gap-5 xl:grid-cols-2"><Card title="의료진 응답에서 중요도가 높았던 항목"><Bars items={multi("importantSignals")} total={done.length}/></Card><Card title="Dashboard 평가"><div className="grid grid-cols-2 gap-3"><Metric label="우선순위 이해도" value={`${avg(done.map(r=>r.dashboardPriorityScore))} / 5`}/><Metric label="확인 이유 이해도" value={`${avg(done.map(r=>r.dashboardReasonScore))} / 5`}/></div><h3 className="mb-3 mt-6 font-black">처음 확인한 정보</h3><Bars items={count(done.map(r=>r.dashboardFirstFocus))} total={done.length}/><Free title="추가 필요 정보" values={done.map(r=>r.dashboardMissingInfo)}/></Card><Card title="Workflow 평가"><Bars items={count(done.map(r=>r.followupAdequacy))} total={done.length}/><h3 className="mb-3 mt-6 font-black">담당자 표시 필요도</h3><Bars items={count(done.map(r=>r.handlerVisibility))} total={done.length}/><h3 className="mb-3 mt-6 font-black">의사 전달 구분 필요도</h3><Bars items={count(done.map(r=>r.doctorEscalation))} total={done.length}/></Card><Card title="운영·도입 가능성"><h3 className="mb-3 font-black">예상 운영 담당자</h3><Bars items={count(done.map(r=>r.expectedOperator))} total={done.length}/><h3 className="mb-3 mt-6 font-black">처리 가능한 Alert</h3><Bars items={count(done.map(r=>r.manageableAlerts))} total={done.length}/><h3 className="mb-3 mt-6 font-black">도입 이유</h3><Bars items={multi("adoptionReasons")} total={done.length}/><h3 className="mb-3 mt-6 font-black">Pilot 관심</h3><Bars items={count(done.map(r=>r.pilotInterest))} total={done.length}/><Free title="비도입 이유" values={done.map(r=>r.nonAdoptionReason)}/></Card></div>
 <p className="mt-6 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-900"><Users className="mr-2 inline" size={17}/>Demo 응답 {SEED_RESPONSES.length}건과 이 브라우저에서 제출된 실제 제품 검증 응답을 함께 표시합니다. 연락처는 CSV와 분석 화면에서 제외됩니다.</p></section></div></main>
}
function Card({title,children,wide=false}:{title:string;children:React.ReactNode;wide?:boolean}){return <section className={`mt-5 rounded-2xl border bg-white p-5 shadow-sm ${wide?"xl:col-span-2":""}`}><h2 className="mb-5 text-xl font-black">{title}</h2>{children}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#EDF4F0] p-4"><p className="text-sm font-bold text-slate-600">{label}</p><b className="mt-2 block text-2xl text-[#315E50]">{value}</b></div>}
function Free({title,values}:{title:string;values:(string|undefined)[]}){const xs=values.filter((v):v is string=>!!v?.trim());return xs.length?<div className="mt-6"><h3 className="mb-3 font-black">{title}</h3><ul className="space-y-2">{xs.slice(0,6).map((v,i)=><li key={i} className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700">{v}</li>)}</ul></div>:null}
