"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, CheckCircle2, UserRoundPlus } from "lucide-react";
import { loadCareState,saveCareState,shiftCareDate,TODAY,type Laterality,type Patient,type SurgeryType } from "@/lib/care-mvp";
import { BODY_PARTS,PROCEDURES } from "@/domain/orthopedics-config";
import { DEMO_RULE_VERSION } from "@/services/prioritization";

const parts=[...BODY_PARTS],procedures=PROCEDURES;
export default function Register(){const [done,setDone]=useState<Patient|null>(null),[form,setForm]=useState({name:"",phone:"",age:"",bodyPart:"무릎",procedureDetail:"인공관절 전치환",customProcedureName:"",laterality:"오른쪽" as Laterality,surgeryDate:shiftCareDate(TODAY,-4),dischargeDate:TODAY,conditionCategory:"postoperative"});const list=[...(procedures[form.bodyPart]||["골절 수술","기타 수술"]),"목록에 없어요 / 직접 입력"];
 const patch=(key:string,value:string)=>setForm(f=>({...f,[key]:value,...(key==="bodyPart"?{procedureDetail:(procedures[value]||["기타 수술"])[0],laterality:value==="척추"?"해당 없음":"오른쪽"}:{}),...(key==="procedureDetail"&&value.includes("골절")?{conditionCategory:"fracture"}:key==="procedureDetail"?{conditionCategory:"postoperative"}:{})}));
 function submit(){if(!form.name||!form.phone||!form.age||!form.surgeryDate||!form.dischargeDate||form.procedureDetail.startsWith("목록에")&&!form.customProcedureName)return;const state=loadCareState(),surgeryType:SurgeryType=form.bodyPart==="척추"?"척추":form.conditionCategory==="fracture"?"골절":form.procedureDetail.includes("인공관절")?"인공관절":"기타",now=new Date().toISOString();const patient:Patient={id:`patient_${Date.now()}`,hospitalId:state.hospitals[0].id,name:form.name,phone:form.phone,age:Number(form.age),surgeryType,bodyPart:form.bodyPart,conditionCategory:form.conditionCategory,procedureCategory:surgeryType,procedureDetail:form.procedureDetail.startsWith("목록에")?"직접 입력":form.procedureDetail,customProcedureName:form.procedureDetail.startsWith("목록에")?form.customProcedureName:"",laterality:form.bodyPart==="척추"?"해당 없음":form.laterality,surgeryDate:form.surgeryDate,dischargeDate:form.dischargeDate,createdAt:now,status:"invited"},episode={id:`episode_${patient.id}`,patientId:patient.id,hospitalId:patient.hospitalId,bodyRegion:"musculoskeletal",bodyPart:patient.bodyPart||"기타",laterality:patient.laterality||"해당 없음",conditionCategory:patient.conditionCategory||"postoperative",procedureCategory:patient.procedureCategory||surgeryType,procedureDetail:patient.procedureDetail||surgeryType,customProcedureName:patient.customProcedureName||"",surgeryDate:patient.surgeryDate||patient.dischargeDate,dischargeDate:patient.dischargeDate,createdAt:now,updatedAt:now,source:"hospital_staff" as const,dataScope:"operational" as const};const next={...state,patients:[...state.patients,patient],episodes:[...state.episodes,episode],statuses:[...state.statuses,{patientId:patient.id,level:"no_response" as const,reason:"아직 체크인 응답이 없음",reasonCodes:["missed_checkin" as const],ruleVersion:DEMO_RULE_VERSION,source:"system" as const,updatedAt:now}]};saveCareState(next);setDone(patient)}
 return <main className="min-h-screen bg-[#F3F5F1] p-5 text-[#202923]"><div className="mx-auto max-w-[760px]"><Link href="/care/hospital" className="flex min-h-12 items-center gap-2 font-black text-[#53675E]"><ArrowLeft/>병원 Dashboard</Link>{done?<section className="mt-10 rounded-[28px] bg-white p-8 text-center"><CheckCircle2 className="mx-auto text-[#315E50]" size={58}/><h1 className="mt-5 text-3xl font-black">환자를 등록했습니다.</h1><div className="mt-6 rounded-2xl bg-[#EEF4F0] p-5 text-left font-bold"><p>{done.laterality} {done.bodyPart}</p><p>{done.customProcedureName||done.procedureDetail}</p><p>수술일 {done.surgeryDate} · 퇴원일 {done.dischargeDate}</p></div><Link href="/care/hospital" className="primary">병원 Dashboard로</Link></section>:<><header className="mt-4"><p className="text-sm font-black text-[#315E50]">PATIENT ENROLLMENT</p><h1 className="mt-2 text-4xl font-black">환자 수술·치료 정보</h1><p className="mt-3 font-semibold text-[#66736C]">병원이 알고 있는 Context만 입력합니다. 목록은 의료진 의견에 따라 변경 가능한 Demo 분류입니다.</p></header><section className="mt-7 rounded-[26px] bg-white p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="환자 이름" value={form.name} onChange={v=>patch("name",v)}/><Field label="휴대전화" value={form.phone} onChange={v=>patch("phone",v)}/><Field label="연령" type="number" value={form.age} onChange={v=>patch("age",v)}/><Select label="치료 부위" value={form.bodyPart} values={parts} onChange={v=>patch("bodyPart",v)}/><Select label="수술/치료 종류" value={form.procedureDetail} values={list} onChange={v=>patch("procedureDetail",v)}/>{form.procedureDetail.startsWith("목록에")?<Field label="수술 또는 치료명을 입력해주세요" placeholder="예: 우측 슬개골 골절 수술" value={form.customProcedureName} onChange={v=>patch("customProcedureName",v)}/>:null}{form.bodyPart!=="척추"?<Select label="좌/우" value={form.laterality} values={["왼쪽","오른쪽","양쪽","해당 없음"]} onChange={v=>patch("laterality",v)}/>:null}<Field label="수술일" type="date" value={form.surgeryDate} onChange={v=>patch("surgeryDate",v)}/><Field label="퇴원일" type="date" value={form.dischargeDate} onChange={v=>patch("dischargeDate",v)}/></div><button onClick={submit} className="mt-6 flex min-h-14 w-full items-center justify-center gap-2 rounded-xl bg-[#315E50] text-lg font-black text-white"><UserRoundPlus/>환자 등록하기</button></section></>}</div></main>}
function Field({label,value,onChange,type="text",placeholder}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="font-black">{label}<input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-14 w-full rounded-xl border-2 border-[#D7E0DB] px-4"/></label>}
function Select({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <label className="font-black">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-14 w-full rounded-xl border-2 border-[#D7E0DB] bg-white px-4">{values.map(x=><option key={x}>{x}</option>)}</select></label>}
