import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {Activity,ArrowDown,ArrowRight,Building2,CheckCircle2,ClipboardCheck,Database,HeartPulse,ShieldCheck,Stethoscope,UserRound} from "lucide-react";
export const metadata:Metadata={title:"오늘안부 Care | 정형외과 퇴원환자 회복관리 플랫폼",description:"정형외과 수술환자의 퇴원 후 회복 변화를 기록하고, 병원이 먼저 확인할 환자를 찾도록 돕는 퇴원환자 관리 플랫폼 오늘안부 Care.",openGraph:{title:"오늘안부 Care | 정형외과 퇴원환자 회복관리 플랫폼",description:"수술 Context부터 퇴원 후 회복 변화와 병원 후속조치까지 연결합니다.",images:[{url:"/og.png",width:1200,height:630,alt:"오늘안부 Care"}]}};
const contact="mailto:pilot@oneulanbu.kr?subject=%EC%98%A4%EB%8A%98%EC%95%88%EB%B6%80%20%EB%B3%91%EC%9B%90%20%EB%8F%84%EC%9E%85%20%EB%AC%B8%EC%9D%98";
const flow=["병원에서 수술 Context 등록","환자가 매일 약 1분 Check-in","시간에 따른 변화 구조화","확인 필요 환자 우선 확인","Follow-up 및 결과 기록"];
export default function Company(){return <main className="bg-[#F7F4EC] text-[#1D2923] [font-size:17px]"><Header/>
<section className="border-b border-[#D9E1DC] px-5 py-20 sm:py-28"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><Kicker>오늘안부 Care</Kicker><h1 className="mt-5 text-[2.7rem] font-black leading-[1.1] tracking-[-.045em] sm:text-[4.4rem]">수술과 퇴원 이후의 회복까지<br/><span className="text-[#315E50]">병원과 연결합니다.</span></h1><p className="mt-7 max-w-[710px] text-xl font-semibold leading-9 text-[#56675F]">오늘안부는 정형외과 수술환자의 퇴원 후 회복 변화를 구조화하고, 병원이 먼저 확인할 환자를 찾도록 돕는 퇴원환자 관리 플랫폼입니다.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/hospital" className="primary-link">병원용 서비스 보기 <ArrowRight size={20}/></Link><Link href="/hospital/dashboard" className="secondary-link">제품 체험하기</Link></div><p className="mt-5 font-bold text-[#6A7972]">정형외과 퇴원환자 관리부터 시작합니다.</p></div><HeroProduct/></div></section>
<Section n="01" name="PROBLEM" title={<>퇴원하는 순간,<br/>병원에서 보이지 않는 시간이 시작됩니다.</>}><Process/><p className="mt-7 max-w-[820px] text-xl font-semibold leading-9 text-[#56675F]">환자는 집에서 회복을 이어가지만 병원에서는 통증, 움직임, 새로운 불편과 같은 변화를 지속적으로 확인하기 어렵습니다.</p><Grid>{[["환자 상태가 보이지 않습니다","퇴원 후 다음 외래까지 상태 변화가 단절됩니다."],["모든 환자에게 전화할 수 없습니다","관리 대상이 많아질수록 동일한 방식의 전화관리는 어렵습니다."],["먼저 봐야 할 환자를 찾기 어렵습니다","판단할 정보가 부족합니다."]].map(([a,b])=><Card key={a} title={a} text={b}/>)}</Grid></Section>
<Section id="service" n="02" name="SOLUTION / HOW IT WORKS" green title={<>모든 환자를 보는 것이 아니라<br/>먼저 확인할 환자를 찾습니다.</>}><div className="mt-10 grid gap-3 lg:grid-cols-5">{flow.map((x,i)=><div key={x} className="relative rounded-2xl bg-white p-5 shadow-sm"><span className="text-sm font-black text-[#3F7563]">0{i+1}</span><strong className="mt-3 block text-xl leading-8">{x}</strong>{i<4?<ArrowRight className="absolute -right-5 top-1/2 z-10 hidden -translate-y-1/2 text-[#6A8A7E] lg:block"/>:null}</div>)}</div><ProductPreview/></Section>
<Section n="03" name="PATIENT / HOSPITAL VALUE" title="하나의 회복 흐름을 환자와 병원이 함께 봅니다."><div className="mt-10 grid gap-5 lg:grid-cols-2"><Value icon={<UserRound/>} label="환자" title="매일 1분, 내 회복을 기록합니다." items={["통증 0~10","움직임","새로운/악화된 불편","전일 대비 상태","내 회복 추이"]}/><Value icon={<Building2/>} label="병원" title="오늘 누구를 먼저 볼지 알 수 있습니다." items={["환자 상태 변화","회복 Trend","확인 필요 이유","후속조치","처리 이력"]}/></div></Section>
<Section n="04" name="FOCUS & DIFFERENTIATION" cream title="정형외과의 수술과 퇴원 이후에 집중합니다."><Focus/><Grid four>{[["Orthopedics","정형외과 수술환자부터 시작합니다."],["Post-discharge","수술과 다음 외래 사이의 관리 공백."],["Lightweight","복잡한 장비 없이 간단한 Check-in부터."],["Workflow","병원의 확인·후속조치까지 연결."]].map(([a,b])=><Card key={a} title={a} text={b}/>)}</Grid></Section>
<Section n="05" name="DATA ARCHITECTURE" title="회복을 하나의 연결된 데이터로 만듭니다."><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["수술 Context","퇴원 후 일일 Check-in","회복 Trend","병원 판단","Follow-up","처리 결과"].map(x=><div key={x} className="flex min-h-20 items-center gap-3 rounded-2xl border bg-white p-5 font-black"><CheckCircle2 className="text-[#315E50]"/>{x}</div>)}</div><ArrowDown className="mx-auto my-6 text-[#315E50]"/><div className="mx-auto max-w-[680px] rounded-[28px] bg-[#29483D] p-8 text-center text-white"><Database className="mx-auto text-[#A9D2C2]"/><h3 className="mt-4 text-3xl font-black">Longitudinal Recovery Data</h3></div><p className="mx-auto mt-7 max-w-[850px] text-center text-xl font-semibold leading-9 text-[#56675F]">어떤 수술을 받은 환자가, 퇴원 후 어떤 변화를 보였고, 병원이 언제 어떤 조치를 했는지를 하나의 흐름으로 연결합니다.</p></Section>
<Section n="06" name="DATA FLYWHEEL" green title="사용할수록 더 나은 관리로 이어집니다."><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{["병원 도입","수술환자 등록","퇴원 후 Check-in","회복 데이터","병원 Follow-up","조치 결과","관리기준 개선","더 나은 환자관리 ↺"].map((x,i)=><div key={x} className="rounded-2xl bg-white p-5 text-center font-black"><span className="mb-2 block text-sm text-[#4F7A6B]">{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div><p className="mt-7 text-center text-xl font-black text-[#315E50]">단순한 환자 수가 아니라 환자 상태 변화와 병원의 실제 행동이 함께 축적됩니다.</p></Section>
<Section n="07" name="AI VISION" title={<>기록에서 시작해<br/>의료진의 판단을 돕는 AI로.</>}><div className="mt-10 grid gap-4 md:grid-cols-4"><Phase label="NOW" title="Structured Recovery Data" text="Context + Check-in + Trend + Follow-up"/><Phase label="NEXT" title="Recovery Analytics" text="시간에 따른 변화를 더 쉽게 파악"/><Phase label="AI PHASE 1" title="의료진용 변화 요약" text="통증, 움직임, 새 불편 변화를 근거와 함께 요약"/><Phase label="AI PHASE 2" title="우선확인 추천 지원" text="충분한 데이터와 의료진 검증을 전제로 개발"/></div><div className="mt-7 flex items-start gap-4 rounded-2xl border bg-white p-5"><ShieldCheck className="shrink-0 text-[#315E50]"/><p className="font-semibold leading-8 text-[#56675F]">현재 AI 진단이나 자동 치료 추천을 제공하지 않습니다. 장기적으로 의료진 업무지원, 데이터 요약, 우선확인 후보 추천을 검증 가능한 방식으로 개발합니다.</p></div></Section>
<Section n="08" name="BUSINESS MODEL" cream title={<>병원이 지속적으로 사용하는<br/>B2B Care Workflow를 만듭니다.</>}><div className="mt-10 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[28px] bg-[#29483D] p-8 text-white"><p className="text-sm font-black text-[#A9D2C2]">초기 모델 · 검증 중</p><h3 className="mt-3 text-3xl font-black">B2B SaaS</h3><p className="mt-6 text-lg font-bold leading-8">병원 단위 구독<br/>관리환자 기반 과금</p></div><div className="grid gap-3 sm:grid-cols-2">{[["Phase 1","정형외과 퇴원환자 관리"],["Phase 2","B2B SaaS"],["Phase 3","병원 Data / System 연동"],["Phase 4","AI 의료진 업무지원"]].map(([a,b])=><Card key={a} title={a} text={b}/>)}</div></div></Section>
<Section n="09" name="VALIDATION" title="지금 검증하고 있습니다."><p className="mt-5 max-w-[800px] text-xl font-semibold leading-9 text-[#56675F]">근거 없는 성과 숫자를 제시하지 않습니다. 실제 의료진과 퇴원환자가 필요로 하고 반복 사용할 수 있는 흐름인지부터 확인합니다.</p><div className="mt-9 grid gap-5 lg:grid-cols-2"><Validation title="의료진" items={["실제 퇴원환자 관리 Workflow","필요한 Check-in 데이터","먼저 확인할 환자 판단 기준","Dashboard 유용성과 후속조치 방식","도입 장벽과 병원 지불의사"]}/><Validation title="퇴원환자" items={["고령 사용자 사용 가능성","Check-in 완료율","반복사용","회복추이 이해도","입력 부담"]}/></div></Section>
<Section n="10" name="ROADMAP" green title="정형외과 퇴원환자 관리에서 시작합니다."><div className="mt-10 grid gap-3 lg:grid-cols-5">{[["01","MVP","Patient ↔ Hospital E2E"],["02","Validation","의료진 + 퇴원환자"],["03","Pilot","실제 정형외과 소규모 운영"],["04","Scale","다기관 확대 / 반복 과금"],["05","AI","의료진 업무지원"]].map(([n,t,d])=><div key={n} className="rounded-2xl bg-white p-5"><span className="font-black text-[#4F7A6B]">{n}</span><h3 className="mt-4 text-2xl font-black">{t}</h3><p className="mt-3 font-semibold leading-7 text-[#617069]">{d}</p></div>)}</div></Section>
<section className="px-5 py-24"><div className="mx-auto max-w-[1050px] rounded-[36px] bg-[#29483D] p-8 text-white sm:p-14"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><Kicker>오늘안부 Care</Kicker><h2 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">퇴원 이후의 회복까지<br/>병원과 연결합니다.</h2><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/hospital" className="inline-flex min-h-14 items-center justify-center rounded-xl bg-white px-6 font-black text-[#29483D]">병원용 서비스 보기</Link><a href={contact} className="inline-flex min-h-14 items-center justify-center rounded-xl border-2 border-white/35 px-6 font-black">도입 문의</a></div><Link href="/research/orthopedics" className="mt-5 inline-flex items-center gap-2 font-black text-[#C5E1D6]">의료진 제품 검증 참여 <ArrowRight size={18}/></Link></div><Image src="/assets/characters/care-default.png" alt="오늘안부 Care 캐릭터" width={150} height={150} className="mx-auto h-auto w-[130px]"/></div></div></section><Footer/></main>}
function Header(){return <header className="sticky top-0 z-40 border-b bg-[#F7F4EC]/95 backdrop-blur"><div className="mx-auto flex min-h-[74px] max-w-[1200px] items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 text-xl font-black text-[#29483D]"><HeartPulse/>오늘안부 Care</Link><nav className="hidden items-center gap-7 md:flex"><a href="#service" className="font-bold">서비스</a><Link href="/hospital" className="font-bold">병원용</Link><Link href="/company" className="font-black text-[#315E50]">오늘안부 소개</Link><Link href="/research/orthopedics" className="font-bold">의료진 검증</Link></nav><Link href="/hospital/dashboard" className="inline-flex min-h-11 items-center rounded-xl bg-[#315E50] px-4 font-black text-white">제품 체험</Link></div></header>}
function Footer(){return <footer className="border-t px-5 py-10"><div className="mx-auto flex max-w-[1200px] flex-col justify-between gap-5 sm:flex-row"><div><p className="font-black text-[#29483D]">오늘안부 Care</p><p className="mt-2 text-sm font-semibold text-[#68766F]">퇴원 후 회복을 병원과 연결합니다.</p></div><nav className="flex flex-wrap gap-5 font-bold text-[#52645B]"><Link href="/">서비스</Link><Link href="/hospital">병원용</Link><Link href="/company">오늘안부 소개</Link><Link href="/research/orthopedics">의료진 검증</Link></nav></div></footer>}
function Section({n,name,title,children,green=false,cream=false,id}:{n:string;name:string;title:React.ReactNode;children:React.ReactNode;green?:boolean;cream?:boolean;id?:string}){return <section id={id} className={`px-5 py-20 sm:py-24 ${green?"bg-[#EAF2ED]":cream?"bg-[#F2EEE4]":"bg-[#FFFCF7]"}`}><div className="mx-auto max-w-[1120px]"><Kicker>{n} · {name}</Kicker><h2 className="mt-4 text-[2.2rem] font-black leading-[1.2] tracking-[-.035em] sm:text-[3.3rem]">{title}</h2>{children}</div></section>}
function Kicker({children}:{children:React.ReactNode}){return <p className="text-sm font-black tracking-[.12em] text-[#3F7563]">{children}</p>}
function Grid({children,four=false}:{children:React.ReactNode;four?:boolean}){return <div className={`mt-9 grid gap-4 ${four?"sm:grid-cols-2 lg:grid-cols-4":"md:grid-cols-3"}`}>{children}</div>}
function Card({title,text}:{title:string;text:string}){return <article className="rounded-2xl border bg-white p-6"><h3 className="text-xl font-black">{title}</h3><p className="mt-3 font-semibold leading-7 text-[#617069]">{text}</p></article>}
function Process(){return <div className="mt-9 grid gap-3 md:grid-cols-5">{["수술","입원","퇴원","집에서 회복","다음 외래"].map((x,i)=><div key={x} className={`relative rounded-2xl border p-5 text-center font-black ${i===3?"border-[#C97755] bg-[#FFF0E8] text-[#9B452B]":"bg-white"}`}>{x}{i<4?<ArrowRight className="absolute -right-5 top-1/2 z-10 hidden -translate-y-1/2 md:block" size={20}/>:null}</div>)}</div>}
function HeroProduct(){return <div className="mx-auto w-full max-w-[520px]"><div className="ml-auto w-[84%] rounded-[26px] border bg-white p-5 shadow-xl"><p className="text-sm font-black text-[#97482F]">오늘 확인 필요</p><h3 className="mt-2 text-xl font-black">통증 5 → 7 · 붓기 응답</h3><div className="mt-4 grid grid-cols-3 gap-2">{["통증 변화","움직임","새 불편"].map(x=><span key={x} className="rounded-xl bg-[#F2F5F3] p-3 text-center text-sm font-bold">{x}</span>)}</div></div><div className="relative -mt-7 w-[70%] rounded-[26px] bg-[#315E50] p-5 text-white shadow-xl"><p className="text-sm font-black text-[#B7D8CB]">오늘 상태 확인</p><p className="mt-2 text-3xl font-black">통증 6 / 10</p><div className="mt-4 h-2 rounded-full bg-white/20"><div className="h-full w-3/5 rounded-full bg-[#D9A16B]"/></div></div></div>}
function ProductPreview(){return <div className="mt-10 grid gap-5 lg:grid-cols-2"><div className="rounded-[28px] bg-[#F1F0E9] p-6"><p className="text-sm font-black text-[#315E50]">PATIENT CHECK-IN</p><h3 className="mt-2 text-2xl font-black">오늘 상태를 약 1분 안에</h3><div className="mt-5 grid grid-cols-2 gap-3">{["통증 0–10","움직임","새로운 불편","어제 대비"].map(x=><div key={x} className="rounded-xl bg-white p-4 font-black">{x}</div>)}</div></div><div className="rounded-[28px] bg-[#29483D] p-6 text-white"><p className="text-sm font-black text-[#A9D2C2]">HOSPITAL WORKLIST</p><h3 className="mt-2 text-2xl font-black">먼저 확인할 환자와 이유</h3>{[["김OO","통증 5 → 7 · 붓기"],["박OO","움직임이 더 불편해짐"]].map(([a,b])=><div key={a} className="mt-3 rounded-xl bg-white/10 p-4"><strong>{a}</strong><p className="mt-1 text-white/75">{b}</p></div>)}</div></div>}
function Value({icon,label,title,items}:{icon:React.ReactNode;label:string;title:string;items:string[]}){return <article className="rounded-[28px] border bg-white p-7"><span className="grid size-12 place-items-center rounded-xl bg-[#E5F0EA] text-[#315E50]">{icon}</span><p className="mt-5 font-black text-[#3F7563]">{label}</p><h3 className="mt-2 text-2xl font-black">{title}</h3><ul className="mt-6 grid gap-3 sm:grid-cols-2">{items.map(x=><li key={x} className="flex gap-2 font-bold"><CheckCircle2 size={19} className="shrink-0 text-[#56806F]"/>{x}</li>)}</ul></article>}
function Focus(){return <div className="mt-10 rounded-[30px] border bg-white p-6 sm:p-9"><div className="grid gap-5 lg:grid-cols-[1fr_auto_1fr] lg:items-center"><div><p className="text-sm font-black text-[#74827B]">병원 안</p><div className="mt-3 space-y-3"><div className="flex gap-3 rounded-xl bg-[#F2F4F1] p-4 font-bold"><Activity className="text-[#315E50]"/>입원 Monitoring · Vital · Wearable</div><div className="flex gap-3 rounded-xl bg-[#F2F4F1] p-4 font-bold"><Stethoscope className="text-[#315E50]"/>수술 · 입원 · 퇴원</div></div></div><ArrowRight className="mx-auto hidden lg:block"/><div className="rounded-[24px] bg-[#315E50] p-6 text-white"><p className="text-sm font-black text-[#B7D8CB]">집 · 다음 외래 사이</p><h3 className="mt-2 text-3xl font-black">오늘안부</h3><p className="mt-3 font-semibold leading-7 text-white/75">퇴원 후 회복 변화 확인<br/>병원 Follow-up 연결</p></div></div></div>}
function Phase({label,title,text}:{label:string;title:string;text:string}){return <article className="rounded-2xl border bg-white p-5"><span className="text-sm font-black text-[#3F7563]">{label}</span><h3 className="mt-4 text-xl font-black leading-7">{title}</h3><p className="mt-3 font-semibold leading-7 text-[#617069]">{text}</p></article>}
function Validation({title,items}:{title:string;items:string[]}){return <article className="rounded-[26px] border bg-white p-7"><h3 className="text-2xl font-black">{title}</h3><ul className="mt-5 space-y-3">{items.map(x=><li key={x} className="flex gap-3 font-semibold leading-7"><ClipboardCheck className="shrink-0 text-[#315E50]" size={20}/>{x}</li>)}</ul></article>}
